MtEmber_Exterior_Frlg_MapScripts::
	.byte 0

MtEmber_Exterior_EventScript_BattleGrunt1::
	end

MtEmber_Exterior_EventScript_BattleGrunt2::
	end

MtEmber_Exterior_EventScript_Beth::
	end

MtEmber_Exterior_EventScript_DefeatedBothGrunts::
	end

MtEmber_Exterior_EventScript_DefeatedGrunt2::
	end

MtEmber_Exterior_EventScript_Grunt1::
	end

MtEmber_Exterior_EventScript_Grunt1Defeated::
	end

MtEmber_Exterior_EventScript_Grunt2::
	end

MtEmber_Exterior_EventScript_Jocelyn::
	end

MtEmber_Exterior_EventScript_Logan::
	end

MtEmber_Exterior_EventScript_OpenCave::
	end

MtEmber_Exterior_EventScript_RocketPasswordScene::
	end

MtEmber_Exterior_EventScript_RocketsFaceDown::
	end

MtEmber_Exterior_OnLoad::
	end

MtEmber_Exterior_OnTransition::
	end

MtEmber_Exterior_Text_BethDefeat::
	end

MtEmber_Exterior_Text_BethIntro::
	end

MtEmber_Exterior_Text_BethPostBattle::
	end

MtEmber_Exterior_Text_FirstPasswordGoldeen::
	end

MtEmber_Exterior_Text_Grunt1Defeat::
	end

MtEmber_Exterior_Text_Grunt1Intro::
	end

MtEmber_Exterior_Text_Grunt1PostBattle::
	end

MtEmber_Exterior_Text_Grunt2Defeat::
	end

MtEmber_Exterior_Text_Grunt2Intro::
	end

MtEmber_Exterior_Text_Grunt2PostBattle::
	end

MtEmber_Exterior_Text_JocelynDefeat::
	end

MtEmber_Exterior_Text_JocelynIntro::
	end

MtEmber_Exterior_Text_JocelynPostBattle::
	end

MtEmber_Exterior_Text_LoganDefeat::
	end

MtEmber_Exterior_Text_LoganIntro::
	end

MtEmber_Exterior_Text_LoganPostBattle::
	end

MtEmber_Exterior_Text_PunchedThroughAtLast::
	end

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
	end

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
	end

MtEmber_Exterior_Text_WellTryDiggingHere::
	end

MtEmber_Exterior_Text_WhatsPasswordAgain::
	end

MtEmber_Exterior_Text_YoureInTheWayGetLost::
	end

