Route27_Frlg_MapScripts::
	.byte 0

Route27_EventScript_BaobaCall::
	end

Route27_EventScript_Blake::
	end

Route27_EventScript_Brian::
	end

Route27_EventScript_Fatman::
	end

Route27_EventScript_FirstSteps::
	end

Route27_EventScript_FirstStepsWalkBot::
	end

Route27_EventScript_FirstStepsWalkTop::
	end

Route27_EventScript_Gilbert::
	end

Route27_EventScript_Item_Moonstone::
	end

Route27_EventScript_Item_RareCandy::
	end

Route27_EventScript_Item_Revive::
	end

Route27_EventScript_Item_SolarBeam::
	end

Route27_EventScript_Jose::
	end

Route27_EventScript_Megan::
	end

Route27_EventScript_Reena::
	end

Route27_EventScript_Scott::
	end

Route27_EventScript_TohjoFallsSign::
	end
