PewterCity_Museum_1F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_1F_EventScript_Bones::
	end

PewterCity_Museum_1F_EventScript_ClawFossil::
	end

PewterCity_Museum_1F_EventScript_FossilWoman::
	end

PewterCity_Museum_1F_EventScript_FossilWoman2::
	end

PewterCity_Museum_1F_EventScript_Oldman::
	end

PewterCity_Museum_1F_EventScript_Receptionist::
	end

PewterCity_Museum_1F_EventScript_RootFossil::
	end


RuinsOfAlph_Lab_EventScript_FossilScientist::
	end
