ThreeIsland_BerryForest_Frlg_MapScripts::
	.byte 0

ThreeIsland_BerryForest_EventScript_BewareSign::
	end

ThreeIsland_BerryForest_EventScript_Lostelle::
	end

ThreeIsland_BerryForest_EventScript_NoRoomForBerry::
	end

ThreeIsland_BerryForest_EventScript_WelcomeSign::
	end

ThreeIsland_BerryForest_Movement_LostelleLookAround::
	end

ThreeIsland_BerryForest_OnTransition::
	end

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
	end

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
	end

ThreeIsland_BerryForest_Text_HelpScaryPokemon::
	end

ThreeIsland_BerryForest_Text_HereItComesAgain::
	end

ThreeIsland_BerryForest_Text_LetsGoHome::
	end

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
	end

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
	end

