SixIsland_PatternBush_Frlg_MapScripts::
	.byte 0

SixIsland_PatternBush_EventScript_Allison::
	end

SixIsland_PatternBush_EventScript_Bethany::
	end

SixIsland_PatternBush_EventScript_Cordell::
	end

SixIsland_PatternBush_EventScript_Dalia::
	end

SixIsland_PatternBush_EventScript_Garret::
	end

SixIsland_PatternBush_EventScript_Joana::
	end

SixIsland_PatternBush_EventScript_Jonah::
	end

SixIsland_PatternBush_EventScript_Layton::
	end

SixIsland_PatternBush_EventScript_Marcy::
	end

SixIsland_PatternBush_EventScript_Nash::
	end

SixIsland_PatternBush_EventScript_Riley::
	end

SixIsland_PatternBush_EventScript_SetEscapeLeftExit::
	end

SixIsland_PatternBush_EventScript_SetEscapeRightExit::
	end

SixIsland_PatternBush_EventScript_Vance::
	end

SixIsland_PatternBush_OnTransition::
	end

SixIsland_PatternBush_Text_AllisonDefeat::
	end

SixIsland_PatternBush_Text_AllisonIntro::
	end

SixIsland_PatternBush_Text_AllisonPostBattle::
	end

SixIsland_PatternBush_Text_BethanyDefeat::
	end

SixIsland_PatternBush_Text_BethanyIntro::
	end

SixIsland_PatternBush_Text_BethanyPostBattle::
	end

SixIsland_PatternBush_Text_CordellDefeat::
	end

SixIsland_PatternBush_Text_CordellIntro::
	end

SixIsland_PatternBush_Text_CordellPostBattle::
	end

SixIsland_PatternBush_Text_DaliaDefeat::
	end

SixIsland_PatternBush_Text_DaliaIntro::
	end

SixIsland_PatternBush_Text_DaliaPostBattle::
	end

SixIsland_PatternBush_Text_GarretDefeat::
	end

SixIsland_PatternBush_Text_GarretIntro::
	end

SixIsland_PatternBush_Text_GarretPostBattle::
	end

SixIsland_PatternBush_Text_JoanaDefeat::
	end

SixIsland_PatternBush_Text_JoanaIntro::
	end

SixIsland_PatternBush_Text_JoanaPostBattle::
	end

SixIsland_PatternBush_Text_JonahDefeat::
	end

SixIsland_PatternBush_Text_JonahIntro::
	end

SixIsland_PatternBush_Text_JonahPostBattle::
	end

SixIsland_PatternBush_Text_LaytonDefeat::
	end

SixIsland_PatternBush_Text_LaytonIntro::
	end

SixIsland_PatternBush_Text_LaytonPostBattle::
	end

SixIsland_PatternBush_Text_MarcyDefeat::
	end

SixIsland_PatternBush_Text_MarcyIntro::
	end

SixIsland_PatternBush_Text_MarcyPostBattle::
	end

SixIsland_PatternBush_Text_NashDefeat::
	end

SixIsland_PatternBush_Text_NashIntro::
	end

SixIsland_PatternBush_Text_NashPostBattle::
	end

SixIsland_PatternBush_Text_RileyDefeat::
	end

SixIsland_PatternBush_Text_RileyIntro::
	end

SixIsland_PatternBush_Text_RileyPostBattle::
	end

SixIsland_PatternBush_Text_VanceDefeat::
	end

SixIsland_PatternBush_Text_VanceIntro::
	end

SixIsland_PatternBush_Text_VancePostBattle::
	end

