CeruleanCity_Frlg_MapScripts::
	.byte 0

CeruleanCity_EventScript_BikeShopSign::
	end

CeruleanCity_EventScript_Boy::
	end

CeruleanCity_EventScript_CapeSign::
	end

CeruleanCity_EventScript_CityEnter::
	end

CeruleanCity_EventScript_CooltrainerM1::
	end

CeruleanCity_EventScript_CooltrainerMReturnedPart::
	end

CeruleanCity_EventScript_Fisher::
	end

CeruleanCity_EventScript_FisherDuringRocket::
	end

CeruleanCity_EventScript_Guard::
	end

CeruleanCity_EventScript_GymSign::
	end

CeruleanCity_EventScript_PoliceSign::
	end

CeruleanCity_EventScript_Sign::
	end

CeruleanCity_EventScript_Slowbro::
	end

CeruleanCity_EventScript_SlowbroWoman::
	end

CeruleanCity_EventScript_Youngster::
	end

CeruleanCity_Text_ThisIsCeruleanCave::
	end
