ViridianCity_Gym_Frlg_MapScripts::
	.byte 0

ViridianCity_Gym_EventScript_Blue::
	end

ViridianCity_Gym_EventScript_BlueGotoDojo::
	end

ViridianCity_Gym_EventScript_Blue_Defeated::
	end

ViridianCity_Gym_EventScript_GymGuy::
	end

ViridianCity_Gym_EventScript_GymGuyAfter::
	end

ViridianCity_Gym_EventScript_GymStatue::
	end

ViridianCity_Gym_EventScript_GymStatuePostVictory::
	end

ViridianCity_Gym_Text_GymStatue::
	end

ViridianCity_Gym_Text_GymStatuePlayerWon::
	end
