FuchsiaCity_Frlg_MapScripts::
	.byte 0

FuchsiaCity_EventScript_BaobaCall::
	end

FuchsiaCity_EventScript_CityEnter::
	end

FuchsiaCity_EventScript_CitySign::
	end

FuchsiaCity_EventScript_Cubone::
	end

FuchsiaCity_EventScript_Dratini::
	end

FuchsiaCity_EventScript_GymSign::
	end

FuchsiaCity_EventScript_Kabuto::
	end

FuchsiaCity_EventScript_Kangaskhan::
	end

FuchsiaCity_EventScript_Omanyte::
	end

FuchsiaCity_EventScript_PokefanM::
	end

FuchsiaCity_EventScript_SafariZone::
	end

FuchsiaCity_EventScript_Teacher::
	end

FuchsiaCity_EventScript_Youngster::
	end

FuchsiaCity_OnFrame::
	end
