SaffronCity_Frlg_MapScripts::
	.byte 0

EcruteakCity_EventScript_Vulpix::
	end

SaffronCity_EventScript_BaobaCall::
	end

SaffronCity_EventScript_CityEnter::
	end

SaffronCity_EventScript_CitySign::
	end

SaffronCity_EventScript_CooltrainerF::
	end

SaffronCity_EventScript_CooltrainerM::
	end

SaffronCity_EventScript_DojoSign::
	end

SaffronCity_EventScript_Elli::
	end

SaffronCity_EventScript_Fisher::
	end

SaffronCity_EventScript_Fisher2::
	end

SaffronCity_EventScript_GymSign::
	end

SaffronCity_EventScript_Lass1A::
	end

SaffronCity_EventScript_Lass1B::
	end

SaffronCity_EventScript_Lass2::
	end

SaffronCity_EventScript_MagnetTrainSign::
	end

SaffronCity_EventScript_MrPsychicSign::
	end

SaffronCity_EventScript_PokefanM::
	end

SaffronCity_EventScript_PokefanM2::
	end

SaffronCity_EventScript_SilphCoSign::
	end

SaffronCity_EventScript_Youngster1::
	end

SaffronCity_EventScript_Youngster2::
	end

SaffronCity_OnFrame::
	end
