#ifndef GUARD_CONSTANTS_FLAGS_KANTO_H
#define GUARD_CONSTANTS_FLAGS_KANTO_H

// Kanto (FRLG) flag compatibility for Emerald+Kanto cross-region builds.
// Generated from flags_frlg.h: defines only the flags used in FRLG map events
// that are NOT already defined with a non-zero value in Emerald flags.h.
// Hidden item flags use a dedicated Kanto base (0x400) to avoid colliding
// with Emerald hidden items (base 0x1F4).  All values are >= FLAG_HIDDEN_ITEMS_START.

#define FLAG_KANTO_HIDDEN_ITEMS_START 0x400

// Kanto hidden item flags
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS              (FLAG_KANTO_HIDDEN_ITEMS_START +   51)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_10           (FLAG_KANTO_HIDDEN_ITEMS_START +   60)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_11           (FLAG_KANTO_HIDDEN_ITEMS_START +   61)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_12           (FLAG_KANTO_HIDDEN_ITEMS_START +   62)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_2            (FLAG_KANTO_HIDDEN_ITEMS_START +   52)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_3            (FLAG_KANTO_HIDDEN_ITEMS_START +   53)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_4            (FLAG_KANTO_HIDDEN_ITEMS_START +   54)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_5            (FLAG_KANTO_HIDDEN_ITEMS_START +   55)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_6            (FLAG_KANTO_HIDDEN_ITEMS_START +   56)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_7            (FLAG_KANTO_HIDDEN_ITEMS_START +   57)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_8            (FLAG_KANTO_HIDDEN_ITEMS_START +   58)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_9            (FLAG_KANTO_HIDDEN_ITEMS_START +   59)
#define FLAG_HIDDEN_ITEM_CELADON_CITY_PP_UP                          (FLAG_KANTO_HIDDEN_ITEMS_START +   47)
#define FLAG_HIDDEN_ITEM_CERULEAN_CAVE_1F_ULTRA_BALL                 (FLAG_KANTO_HIDDEN_ITEMS_START +   39)
#define FLAG_HIDDEN_ITEM_CERULEAN_CITY_RARE_CANDY                    (FLAG_KANTO_HIDDEN_ITEMS_START +   49)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BIG_PEARL       (FLAG_KANTO_HIDDEN_ITEMS_START +  170)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BLUK_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +  173)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_RAZZ_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +  171)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_SITRUS_BERRY    (FLAG_KANTO_HIDDEN_ITEMS_START +  172)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_NEST_BALL       (FLAG_KANTO_HIDDEN_ITEMS_START +  174)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST        (FLAG_KANTO_HIDDEN_ITEMS_START +  175)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST_2      (FLAG_KANTO_HIDDEN_ITEMS_START +  177)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STAR_PIECE      (FLAG_KANTO_HIDDEN_ITEMS_START +  176)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NEST_BALL      (FLAG_KANTO_HIDDEN_ITEMS_START +   68)
#define FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NET_BALL       (FLAG_KANTO_HIDDEN_ITEMS_START +   69)
#define FLAG_HIDDEN_ITEM_FOUR_ISLAND_PEARL                           (FLAG_KANTO_HIDDEN_ITEMS_START +  168)
#define FLAG_HIDDEN_ITEM_FOUR_ISLAND_ULTRA_BALL                      (FLAG_KANTO_HIDDEN_ITEMS_START +  169)
#define FLAG_HIDDEN_ITEM_FUCHSIA_CITY_MAX_REVIVE                     (FLAG_KANTO_HIDDEN_ITEMS_START +  133)
#define FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_FIRE_STONE                (FLAG_KANTO_HIDDEN_ITEMS_START +  158)
#define FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_ULTRA_BALL                (FLAG_KANTO_HIDDEN_ITEMS_START +  162)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM                    (FLAG_KANTO_HIDDEN_ITEMS_START +   87)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_2                  (FLAG_KANTO_HIDDEN_ITEMS_START +   88)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_3                  (FLAG_KANTO_HIDDEN_ITEMS_START +   89)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM                   (FLAG_KANTO_HIDDEN_ITEMS_START +   84)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_2                 (FLAG_KANTO_HIDDEN_ITEMS_START +   85)
#define FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_3                 (FLAG_KANTO_HIDDEN_ITEMS_START +   86)
#define FLAG_HIDDEN_ITEM_MT_MOON_B2F_ETHER                           (FLAG_KANTO_HIDDEN_ITEMS_START +    3)
#define FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE                      (FLAG_KANTO_HIDDEN_ITEMS_START +    2)
#define FLAG_HIDDEN_ITEM_NAVEL_ROCK_SUMMIT_SACRED_ASH                (FLAG_KANTO_HIDDEN_ITEMS_START +  160)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_BIG_PEARL         (FLAG_KANTO_HIDDEN_ITEMS_START +  110)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL             (FLAG_KANTO_HIDDEN_ITEMS_START +  105)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL_2           (FLAG_KANTO_HIDDEN_ITEMS_START +  106)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST          (FLAG_KANTO_HIDDEN_ITEMS_START +  103)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST_2        (FLAG_KANTO_HIDDEN_ITEMS_START +  104)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STAR_PIECE        (FLAG_KANTO_HIDDEN_ITEMS_START +  109)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL        (FLAG_KANTO_HIDDEN_ITEMS_START +  107)
#define FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL_2      (FLAG_KANTO_HIDDEN_ITEMS_START +  108)
#define FLAG_HIDDEN_ITEM_PEWTER_CITY_POKE_BALL                       (FLAG_KANTO_HIDDEN_ITEMS_START +  112)
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_1F_MOON_STONE               (FLAG_KANTO_HIDDEN_ITEMS_START +   31)
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_3F_RARE_CANDY               (FLAG_KANTO_HIDDEN_ITEMS_START +   32)
#define FLAG_HIDDEN_ITEM_POKEMON_MANSION_B1F_ELIXIR                  (FLAG_KANTO_HIDDEN_ITEMS_START +   33)
#define FLAG_HIDDEN_ITEM_POKEMON_TOWER_5F_BIG_MUSHROOM               (FLAG_KANTO_HIDDEN_ITEMS_START +   14)
#define FLAG_HIDDEN_ITEM_POKEMON_TOWER_7F_SOOTHE_BELL                (FLAG_KANTO_HIDDEN_ITEMS_START +  159)
#define FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR                      (FLAG_KANTO_HIDDEN_ITEMS_START +   27)
#define FLAG_HIDDEN_ITEM_POWER_PLANT_THUNDER_STONE                   (FLAG_KANTO_HIDDEN_ITEMS_START +   28)
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP                    (FLAG_KANTO_HIDDEN_ITEMS_START +   11)
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B3F_NUGGET                   (FLAG_KANTO_HIDDEN_ITEMS_START +   12)
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NEST_BALL                (FLAG_KANTO_HIDDEN_ITEMS_START +   13)
#define FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NET_BALL                 (FLAG_KANTO_HIDDEN_ITEMS_START +  134)
#define FLAG_HIDDEN_ITEM_ROUTE10_CHERI_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  126)
#define FLAG_HIDDEN_ITEM_ROUTE10_MAX_ETHER                           (FLAG_KANTO_HIDDEN_ITEMS_START +   10)
#define FLAG_HIDDEN_ITEM_ROUTE10_NANAB_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  151)
#define FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY                        (FLAG_KANTO_HIDDEN_ITEMS_START +  125)
#define FLAG_HIDDEN_ITEM_ROUTE10_SUPER_POTION                        (FLAG_KANTO_HIDDEN_ITEMS_START +    9)
#define FLAG_HIDDEN_ITEM_ROUTE11_ESCAPE_ROPE                         (FLAG_KANTO_HIDDEN_ITEMS_START +   41)
#define FLAG_HIDDEN_ITEM_ROUTE12_HYPER_POTION                        (FLAG_KANTO_HIDDEN_ITEMS_START +   42)
#define FLAG_HIDDEN_ITEM_ROUTE12_LEFTOVERS                           (FLAG_KANTO_HIDDEN_ITEMS_START +  131)
#define FLAG_HIDDEN_ITEM_ROUTE12_RARE_CANDY                          (FLAG_KANTO_HIDDEN_ITEMS_START +  130)
#define FLAG_HIDDEN_ITEM_ROUTE13_PP_UP                               (FLAG_KANTO_HIDDEN_ITEMS_START +   15)
#define FLAG_HIDDEN_ITEM_ROUTE14_PINAP_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  157)
#define FLAG_HIDDEN_ITEM_ROUTE14_ZINC                                (FLAG_KANTO_HIDDEN_ITEMS_START +  149)
#define FLAG_HIDDEN_ITEM_ROUTE16_LEFTOVERS                           (FLAG_KANTO_HIDDEN_ITEMS_START +  132)
#define FLAG_HIDDEN_ITEM_ROUTE17_FULL_RESTORE                        (FLAG_KANTO_HIDDEN_ITEMS_START +   18)
#define FLAG_HIDDEN_ITEM_ROUTE17_MAX_ELIXIR                          (FLAG_KANTO_HIDDEN_ITEMS_START +   21)
#define FLAG_HIDDEN_ITEM_ROUTE17_MAX_REVIVE                          (FLAG_KANTO_HIDDEN_ITEMS_START +   20)
#define FLAG_HIDDEN_ITEM_ROUTE17_PP_UP                               (FLAG_KANTO_HIDDEN_ITEMS_START +   19)
#define FLAG_HIDDEN_ITEM_ROUTE17_RARE_CANDY                          (FLAG_KANTO_HIDDEN_ITEMS_START +   17)
#define FLAG_HIDDEN_ITEM_ROUTE20_STARDUST                            (FLAG_KANTO_HIDDEN_ITEMS_START +  153)
#define FLAG_HIDDEN_ITEM_ROUTE21_NORTH_PEARL                         (FLAG_KANTO_HIDDEN_ITEMS_START +  154)
#define FLAG_HIDDEN_ITEM_ROUTE23_ASPEAR_BERRY                        (FLAG_KANTO_HIDDEN_ITEMS_START +  147)
#define FLAG_HIDDEN_ITEM_ROUTE23_FULL_RESTORE                        (FLAG_KANTO_HIDDEN_ITEMS_START +   34)
#define FLAG_HIDDEN_ITEM_ROUTE23_LEPPA_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  148)
#define FLAG_HIDDEN_ITEM_ROUTE23_LUM_BERRY                           (FLAG_KANTO_HIDDEN_ITEMS_START +  145)
#define FLAG_HIDDEN_ITEM_ROUTE23_MAX_ELIXIR                          (FLAG_KANTO_HIDDEN_ITEMS_START +  155)
#define FLAG_HIDDEN_ITEM_ROUTE23_MAX_ETHER                           (FLAG_KANTO_HIDDEN_ITEMS_START +   36)
#define FLAG_HIDDEN_ITEM_ROUTE23_SITRUS_BERRY                        (FLAG_KANTO_HIDDEN_ITEMS_START +  146)
#define FLAG_HIDDEN_ITEM_ROUTE23_ULTRA_BALL                          (FLAG_KANTO_HIDDEN_ITEMS_START +   35)
#define FLAG_HIDDEN_ITEM_ROUTE24_PECHA_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  115)
#define FLAG_HIDDEN_ITEM_ROUTE25_BLUK_BERRY                          (FLAG_KANTO_HIDDEN_ITEMS_START +  117)
#define FLAG_HIDDEN_ITEM_ROUTE25_ELIXIR                              (FLAG_KANTO_HIDDEN_ITEMS_START +    4)
#define FLAG_HIDDEN_ITEM_ROUTE25_ETHER                               (FLAG_KANTO_HIDDEN_ITEMS_START +    5)
#define FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY                          (FLAG_KANTO_HIDDEN_ITEMS_START +  116)
#define FLAG_HIDDEN_ITEM_ROUTE3_ORAN_BERRY                           (FLAG_KANTO_HIDDEN_ITEMS_START +  113)
#define FLAG_HIDDEN_ITEM_ROUTE4_GREAT_BALL                           (FLAG_KANTO_HIDDEN_ITEMS_START +   50)
#define FLAG_HIDDEN_ITEM_ROUTE4_PERSIM_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  114)
#define FLAG_HIDDEN_ITEM_ROUTE4_RAZZ_BERRY                           (FLAG_KANTO_HIDDEN_ITEMS_START +  156)
#define FLAG_HIDDEN_ITEM_ROUTE6_RARE_CANDY                           (FLAG_KANTO_HIDDEN_ITEMS_START +  119)
#define FLAG_HIDDEN_ITEM_ROUTE6_SITRUS_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  118)
#define FLAG_HIDDEN_ITEM_ROUTE7_WEPEAR_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  152)
#define FLAG_HIDDEN_ITEM_ROUTE8_LEPPA_BERRY                          (FLAG_KANTO_HIDDEN_ITEMS_START +  129)
#define FLAG_HIDDEN_ITEM_ROUTE8_LUM_BERRY                            (FLAG_KANTO_HIDDEN_ITEMS_START +  128)
#define FLAG_HIDDEN_ITEM_ROUTE8_RAWST_BERRY                          (FLAG_KANTO_HIDDEN_ITEMS_START +  127)
#define FLAG_HIDDEN_ITEM_ROUTE9_CHESTO_BERRY                         (FLAG_KANTO_HIDDEN_ITEMS_START +  150)
#define FLAG_HIDDEN_ITEM_ROUTE9_ETHER                                (FLAG_KANTO_HIDDEN_ITEMS_START +    6)
#define FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY                           (FLAG_KANTO_HIDDEN_ITEMS_START +  123)
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_CENTER_LEAF_STONE               (FLAG_KANTO_HIDDEN_ITEMS_START +   22)
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_WEST_REVIVE                     (FLAG_KANTO_HIDDEN_ITEMS_START +   23)
#define FLAG_HIDDEN_ITEM_SAFFRON_CITY_COPYCATS_HOUSE_2F_NUGGET       (FLAG_KANTO_HIDDEN_ITEMS_START +   26)
#define FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B3F_NUGGET                  (FLAG_KANTO_HIDDEN_ITEMS_START +   29)
#define FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B4F_WATER_STONE             (FLAG_KANTO_HIDDEN_ITEMS_START +   30)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_CHERI_BERRY     (FLAG_KANTO_HIDDEN_ITEMS_START +   63)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE_RAWST_BERRY (FLAG_KANTO_HIDDEN_ITEMS_START +  188)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE       (FLAG_KANTO_HIDDEN_ITEMS_START +   65)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_2     (FLAG_KANTO_HIDDEN_ITEMS_START +   66)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_3     (FLAG_KANTO_HIDDEN_ITEMS_START +   67)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_4     (FLAG_KANTO_HIDDEN_ITEMS_START +   64)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_BIG_PEARL        (FLAG_KANTO_HIDDEN_ITEMS_START +  185)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_NANAB_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +  187)
#define FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_PEARL            (FLAG_KANTO_HIDDEN_ITEMS_START +  186)
#define FLAG_HIDDEN_ITEM_SILPH_CO_10F_HP_UP                          (FLAG_KANTO_HIDDEN_ITEMS_START +  143)
#define FLAG_HIDDEN_ITEM_SILPH_CO_11F_REVIVE                         (FLAG_KANTO_HIDDEN_ITEMS_START +  144)
#define FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL                      (FLAG_KANTO_HIDDEN_ITEMS_START +  135)
#define FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN                         (FLAG_KANTO_HIDDEN_ITEMS_START +  136)
#define FLAG_HIDDEN_ITEM_SILPH_CO_4F_IRON                            (FLAG_KANTO_HIDDEN_ITEMS_START +  137)
#define FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR                          (FLAG_KANTO_HIDDEN_ITEMS_START +   24)
#define FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP                           (FLAG_KANTO_HIDDEN_ITEMS_START +  138)
#define FLAG_HIDDEN_ITEM_SILPH_CO_6F_CARBOS                          (FLAG_KANTO_HIDDEN_ITEMS_START +  139)
#define FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC                            (FLAG_KANTO_HIDDEN_ITEMS_START +  140)
#define FLAG_HIDDEN_ITEM_SILPH_CO_8F_NUGGET                          (FLAG_KANTO_HIDDEN_ITEMS_START +  141)
#define FLAG_HIDDEN_ITEM_SILPH_CO_9F_CALCIUM                         (FLAG_KANTO_HIDDEN_ITEMS_START +  142)
#define FLAG_HIDDEN_ITEM_SILPH_CO_9F_MAX_POTION                      (FLAG_KANTO_HIDDEN_ITEMS_START +   25)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_GREEN_PATH_ULTRA_BALL            (FLAG_KANTO_HIDDEN_ITEMS_START +  180)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_LEPPA_BERRY                      (FLAG_KANTO_HIDDEN_ITEMS_START +  184)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_NET_BALL          (FLAG_KANTO_HIDDEN_ITEMS_START +  179)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_STAR_PIECE        (FLAG_KANTO_HIDDEN_ITEMS_START +  178)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ASPEAR_BERRY          (FLAG_KANTO_HIDDEN_ITEMS_START +  181)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ORAN_BERRY            (FLAG_KANTO_HIDDEN_ITEMS_START +  182)
#define FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_PINAP_BERRY           (FLAG_KANTO_HIDDEN_ITEMS_START +  183)
#define FLAG_HIDDEN_ITEM_SSANNE_B1F_CORRIDOR_HYPER_POTION            (FLAG_KANTO_HIDDEN_ITEMS_START +    8)
#define FLAG_HIDDEN_ITEM_SSANNE_EXTERIOR_LAVA_COOKIE                 (FLAG_KANTO_HIDDEN_ITEMS_START +  190)
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHERI_BERRY                  (FLAG_KANTO_HIDDEN_ITEMS_START +  121)
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHESTO_BERRY                 (FLAG_KANTO_HIDDEN_ITEMS_START +  122)
#define FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_PECHA_BERRY                  (FLAG_KANTO_HIDDEN_ITEMS_START +  120)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ASPEAR_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +   99)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_BLUK_BERRY        (FLAG_KANTO_HIDDEN_ITEMS_START +   91)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHERI_BERRY       (FLAG_KANTO_HIDDEN_ITEMS_START +   95)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHESTO_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +   96)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_LUM_BERRY         (FLAG_KANTO_HIDDEN_ITEMS_START +  102)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_NANAB_BERRY       (FLAG_KANTO_HIDDEN_ITEMS_START +   92)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ORAN_BERRY        (FLAG_KANTO_HIDDEN_ITEMS_START +   94)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PECHA_BERRY       (FLAG_KANTO_HIDDEN_ITEMS_START +   97)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PERSIM_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +  100)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PINAP_BERRY       (FLAG_KANTO_HIDDEN_ITEMS_START +  101)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAWST_BERRY       (FLAG_KANTO_HIDDEN_ITEMS_START +   98)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAZZ_BERRY        (FLAG_KANTO_HIDDEN_ITEMS_START +   90)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_WEPEAR_BERRY      (FLAG_KANTO_HIDDEN_ITEMS_START +   93)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_MAX_REPEL          (FLAG_KANTO_HIDDEN_ITEMS_START +  165)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_PEARL              (FLAG_KANTO_HIDDEN_ITEMS_START +  166)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_STARDUST           (FLAG_KANTO_HIDDEN_ITEMS_START +  167)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_DUNSPARCE_TUNNEL_NUGGET        (FLAG_KANTO_HIDDEN_ITEMS_START +  163)
#define FLAG_HIDDEN_ITEM_THREE_ISLAND_PP_UP                          (FLAG_KANTO_HIDDEN_ITEMS_START +  164)
#define FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_PP_MAX                (FLAG_KANTO_HIDDEN_ITEMS_START +  161)
#define FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_RARE_CANDY            (FLAG_KANTO_HIDDEN_ITEMS_START +  111)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ANTIDOTE  (FLAG_KANTO_HIDDEN_ITEMS_START +   78)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_AWAKENING (FLAG_KANTO_HIDDEN_ITEMS_START +   80)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_BURN_HEAL (FLAG_KANTO_HIDDEN_ITEMS_START +   81)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ETHER     (FLAG_KANTO_HIDDEN_ITEMS_START +   83)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ICE_HEAL  (FLAG_KANTO_HIDDEN_ITEMS_START +   82)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_PARALYZE_HEAL (FLAG_KANTO_HIDDEN_ITEMS_START +   79)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_POTION    (FLAG_KANTO_HIDDEN_ITEMS_START +   77)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ANTIDOTE (FLAG_KANTO_HIDDEN_ITEMS_START +   71)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_AWAKENING (FLAG_KANTO_HIDDEN_ITEMS_START +   73)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_BURN_HEAL (FLAG_KANTO_HIDDEN_ITEMS_START +   74)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ETHER   (FLAG_KANTO_HIDDEN_ITEMS_START +   76)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ICE_HEAL (FLAG_KANTO_HIDDEN_ITEMS_START +   75)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_PARALYZE_HEAL (FLAG_KANTO_HIDDEN_ITEMS_START +   72)
#define FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_POTION  (FLAG_KANTO_HIDDEN_ITEMS_START +   70)
#define FLAG_HIDDEN_ITEM_VERMILION_CITY_MAX_ETHER                    (FLAG_KANTO_HIDDEN_ITEMS_START +   48)
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_FULL_RESTORE                (FLAG_KANTO_HIDDEN_ITEMS_START +   38)
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL                  (FLAG_KANTO_HIDDEN_ITEMS_START +   37)
#define FLAG_HIDDEN_ITEM_VIRIDIAN_CITY_GYM_MACHO_BRACE               (FLAG_KANTO_HIDDEN_ITEMS_START +  189)
#define FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_ANTIDOTE                    (FLAG_KANTO_HIDDEN_ITEMS_START +    1)
#define FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_POTION                      (FLAG_KANTO_HIDDEN_ITEMS_START +    0)

// Other Kanto-specific flags (events, trainer-defeated, etc.)
#define FLAG_HIDE_ARTICUNO                                           0x082
#define FLAG_HIDE_BILL_CLEFAIRY                                      0x032
#define FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE                             0x033
#define FLAG_HIDE_BIRTH_ISLAND_METEORITE                             0x09A
#define FLAG_HIDE_BULBASAUR_BALL                                     0x028
#define FLAG_HIDE_CELADON_CITY_ETHER                                 0x1D1
#define FLAG_HIDE_CELADON_ROCKETS                                    0x05F
#define FLAG_HIDE_CERULEAN_CAVE_1F_FULL_RESTORE                      0x1B3
#define FLAG_HIDE_CERULEAN_CAVE_1F_MAX_ELIXIR                        0x1B1
#define FLAG_HIDE_CERULEAN_CAVE_1F_NUGGET                            0x1B2
#define FLAG_HIDE_CERULEAN_CAVE_2F_FULL_RESTORE                      0x1B4
#define FLAG_HIDE_CERULEAN_CAVE_2F_PP_UP                             0x1B5
#define FLAG_HIDE_CERULEAN_CAVE_2F_ULTRA_BALL                        0x1B6
#define FLAG_HIDE_CERULEAN_CAVE_B1F_MAX_REVIVE                       0x1B7
#define FLAG_HIDE_CERULEAN_CAVE_B1F_ULTRA_BALL                       0x1B8
#define FLAG_HIDE_CERULEAN_CAVE_GUARD                                0x05C
#define FLAG_HIDE_CERULEAN_RIVAL                                     0x03C
#define FLAG_HIDE_CERULEAN_ROCKET                                    0x03B
#define FLAG_HIDE_CHARMANDER_BALL                                    0x02A
#define FLAG_HIDE_CINNABAR_BILL                                      0x062
#define FLAG_HIDE_CINNABAR_POKECENTER_BILL                           0x0A2
#define FLAG_HIDE_CINNABAR_SEAGALLOP                                 0x06B
#define FLAG_HIDE_CREDITS_OAK                                        0x0A4
#define FLAG_HIDE_CREDITS_RIVAL                                      0x0A3
#define FLAG_HIDE_DOJO_HITMONCHAN_BALL                               0x061
#define FLAG_HIDE_DOJO_HITMONLEE_BALL                                0x060
#define FLAG_HIDE_DOME_FOSSIL                                        0x02F
#define FLAG_HIDE_DOTTED_HOLE_SCIENTIST                              0x090
#define FLAG_HIDE_EEVEE_BALL                                         0x057
#define FLAG_HIDE_FAME_CHECKER_ERIKA_JOURNALS                        0x09E
#define FLAG_HIDE_FAME_CHECKER_KOGA_JOURNAL                          0x09F
#define FLAG_HIDE_FAME_CHECKER_LT_SURGE_JOURNAL                      0x0A0
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM10_SILK_SCARF            0x1F8
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM11_LAX_INCENSE           0x1F9
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM12_SEA_INCENSE           0x1FA
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM13_MAX_REVIVE            0x1FB
#define FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM14_RARE_CANDY            0x1FC
#define FLAG_HIDE_FIVE_ISLAND_MEADOW_MAX_POTION                      0x1DE
#define FLAG_HIDE_FIVE_ISLAND_MEADOW_PP_UP                           0x1DF
#define FLAG_HIDE_FIVE_ISLAND_MEMORIAL_PILLAR_METAL_COAT             0x1E0
#define FLAG_HIDE_FIVE_ISLAND_ROCKETS                                0x088
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_BIG_PEARL             0x1F4
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_PEARL                 0x1F6
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_TM36                  0x1F5
#define FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_UP_GRADE              0x1F7
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_HM07                   0x1F1
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_ULTRA_BALL             0x1F0
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_FULL_RESTORE          0x1F2
#define FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_NEVER_MELT_ICE        0x1F3
#define FLAG_HIDE_FOUR_ISLAND_RIVAL                                  0x097
#define FLAG_HIDE_FOUR_ISLAND_STARDUST                               0x1DA
#define FLAG_HIDE_FOUR_ISLAND_STAR_PIECE                             0x1D9
#define FLAG_HIDE_FUCHSIA_CITY_WARDENS_HOUSE_RARE_CANDY              0x1B9
#define FLAG_HIDE_GAME_CORNER_ROCKET                                 0x05B
#define FLAG_HIDE_HELIX_FOSSIL                                       0x030
#define FLAG_HIDE_HIDEOUT_GIOVANNI                                   0x038
#define FLAG_HIDE_ICEFALL_CAVE_LORELEI                               0x08B
#define FLAG_HIDE_ICEFALL_CAVE_ROCKETS                               0x08D
#define FLAG_HIDE_LIFT_KEY                                           0x036
#define FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL                         0x0AA
#define FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL                         0x0AC
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL                      0x0A7
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL                      0x0A9
#define FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL                        0x0AB
#define FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL                         0x0A6
#define FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL                      0x0A8
#define FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL                          0x0A5
#define FLAG_HIDE_LORELEI_IN_HER_HOUSE                               0x08C
#define FLAG_HIDE_LOSTELLE_IN_BERRY_FOREST                           0x07A
#define FLAG_HIDE_LOSTELLE_IN_HER_HOME                               0x076
#define FLAG_HIDE_LOST_CAVE_SELPHY                                   0x093
#define FLAG_HIDE_MEWTWO                                             0x081
#define FLAG_HIDE_MG_DELIVERYMEN                                     0x070
#define FLAG_HIDE_MISC_KANTO_ROCKETS                                 0x0AD
#define FLAG_HIDE_MOLTRES                                            0x052
#define FLAG_HIDE_MT_EMBER_EXTERIOR_DIRE_HIT                         0x1EF
#define FLAG_HIDE_MT_EMBER_EXTERIOR_FIRE_STONE                       0x1EE
#define FLAG_HIDE_MT_EMBER_EXTERIOR_ROCKETS                          0x089
#define FLAG_HIDE_MT_EMBER_EXTERIOR_ULTRA_BALL                       0x1ED
#define FLAG_HIDE_MT_MOON_1F_ESCAPE_ROPE                             0x15D
#define FLAG_HIDE_MT_MOON_1F_MOON_STONE                              0x15E
#define FLAG_HIDE_MT_MOON_1F_PARALYZE_HEAL                           0x159
#define FLAG_HIDE_MT_MOON_1F_POTION                                  0x15B
#define FLAG_HIDE_MT_MOON_1F_RARE_CANDY                              0x15C
#define FLAG_HIDE_MT_MOON_1F_TM09                                    0x15A
#define FLAG_HIDE_MT_MOON_B2F_ANTIDOTE                               0x1C0
#define FLAG_HIDE_MT_MOON_B2F_REVIVE                                 0x1BF
#define FLAG_HIDE_MT_MOON_B2F_STAR_PIECE                             0x15F
#define FLAG_HIDE_MT_MOON_B2F_TM46                                   0x160
#define FLAG_HIDE_NUGGET_BRIDGE_ROCKET                               0x031
#define FLAG_HIDE_OAK_IN_CHAMP_ROOM                                  0x05A
#define FLAG_HIDE_OAK_IN_HIS_LAB                                     0x02B
#define FLAG_HIDE_OAK_IN_PALLET_TOWN                                 0x02C
#define FLAG_HIDE_OLD_AMBER                                          0x056
#define FLAG_HIDE_ONE_ISLAND_BILL                                    0x071
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_CARBOS                      0x1DD
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_ETHER                       0x1DB
#define FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_MAX_REPEL                   0x1DC
#define FLAG_HIDE_ONE_ISLAND_POKECENTER_BILL                         0x072
#define FLAG_HIDE_ONE_ISLAND_POKECENTER_CELIO                        0x073
#define FLAG_HIDE_PEWTER_CITY_GYM_GUIDE                              0x02E
#define FLAG_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY                      0x092
#define FLAG_HIDE_PEWTER_MUSEUM_GUIDE                                0x050
#define FLAG_HIDE_POKEDEX                                            0x03A
#define FLAG_HIDE_POKEHOUSE_FUJI                                     0x035
#define FLAG_HIDE_POKEMON_MANSION_1F_CARBOS                          0x19F
#define FLAG_HIDE_POKEMON_MANSION_1F_ESCAPE_ROPE                     0x1A0
#define FLAG_HIDE_POKEMON_MANSION_1F_PROTEIN                         0x1CA
#define FLAG_HIDE_POKEMON_MANSION_2F_CALCIUM                         0x1A1
#define FLAG_HIDE_POKEMON_MANSION_2F_HP_UP                           0x1CC
#define FLAG_HIDE_POKEMON_MANSION_2F_ZINC                            0x1CB
#define FLAG_HIDE_POKEMON_MANSION_3F_IRON                            0x1A3
#define FLAG_HIDE_POKEMON_MANSION_3F_MAX_POTION                      0x1A2
#define FLAG_HIDE_POKEMON_MANSION_B1F_FULL_RESTORE                   0x1A5
#define FLAG_HIDE_POKEMON_MANSION_B1F_SECRET_KEY                     0x1A8
#define FLAG_HIDE_POKEMON_MANSION_B1F_TM14                           0x1A4
#define FLAG_HIDE_POKEMON_MANSION_B1F_TM22                           0x1A7
#define FLAG_HIDE_POKEMON_TOWER_3F_ESCAPE_ROPE                       0x177
#define FLAG_HIDE_POKEMON_TOWER_4F_AWAKENING                         0x179
#define FLAG_HIDE_POKEMON_TOWER_4F_ELIXIR                            0x178
#define FLAG_HIDE_POKEMON_TOWER_4F_GREAT_BALL                        0x17A
#define FLAG_HIDE_POKEMON_TOWER_5F_CLEANSE_TAG                       0x1D0
#define FLAG_HIDE_POKEMON_TOWER_5F_NUGGET                            0x17B
#define FLAG_HIDE_POKEMON_TOWER_6F_RARE_CANDY                        0x17C
#define FLAG_HIDE_POKEMON_TOWER_6F_X_ACCURACY                        0x17D
#define FLAG_HIDE_POSTGAME_GOSSIPERS                                 0x09D
#define FLAG_HIDE_POWER_PLANT_ELECTRODE_1                            0x085
#define FLAG_HIDE_POWER_PLANT_ELECTRODE_2                            0x086
#define FLAG_HIDE_POWER_PLANT_ELIXIR                                 0x19E
#define FLAG_HIDE_POWER_PLANT_MAX_POTION                             0x19A
#define FLAG_HIDE_POWER_PLANT_THUNDER_STONE                          0x19D
#define FLAG_HIDE_POWER_PLANT_TM17                                   0x19B
#define FLAG_HIDE_POWER_PLANT_TM25                                   0x19C
#define FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY                      0x095
#define FLAG_HIDE_RESORT_GORGEOUS_SELPHY                             0x094
#define FLAG_HIDE_RIVAL_IN_LAB                                       0x02D
#define FLAG_HIDE_ROCKET_HIDEOUT_B1F_ESCAPE_ROPE                     0x16C
#define FLAG_HIDE_ROCKET_HIDEOUT_B1F_HYPER_POTION                    0x16D
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_MOON_STONE                      0x16F
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_SUPER_POTION                    0x171
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_TM12                            0x170
#define FLAG_HIDE_ROCKET_HIDEOUT_B2F_X_SPEED                         0x16E
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_BLACK_GLASSES                   0x1D2
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_RARE_CANDY                      0x172
#define FLAG_HIDE_ROCKET_HIDEOUT_B3F_TM21                            0x173
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_CALCIUM                         0x176
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_MAX_ETHER                       0x175
#define FLAG_HIDE_ROCKET_HIDEOUT_B4F_TM49                            0x174
#define FLAG_HIDE_ROCK_TUNNEL_1F_ESCAPE_ROPE                         0x1C5
#define FLAG_HIDE_ROCK_TUNNEL_1F_PEARL                               0x1C4
#define FLAG_HIDE_ROCK_TUNNEL_1F_REPEL                               0x1C3
#define FLAG_HIDE_ROCK_TUNNEL_B1F_MAX_ETHER                          0x1C7
#define FLAG_HIDE_ROCK_TUNNEL_B1F_REVIVE                             0x1C6
#define FLAG_HIDE_ROUTE11_AWAKENING                                  0x1CF
#define FLAG_HIDE_ROUTE11_GREAT_BALL                                 0x1CE
#define FLAG_HIDE_ROUTE11_X_DEFEND                                   0x1C1
#define FLAG_HIDE_ROUTE12_IRON                                       0x17F
#define FLAG_HIDE_ROUTE12_TM48                                       0x17E
#define FLAG_HIDE_ROUTE15_TM18                                       0x180
#define FLAG_HIDE_ROUTE24_TM45                                       0x162
#define FLAG_HIDE_ROUTE25_TM43                                       0x163
#define FLAG_HIDE_ROUTE2_ETHER                                       0x154
#define FLAG_HIDE_ROUTE2_PARALYZE_HEAL                               0x155
#define FLAG_HIDE_ROUTE4_TM05                                        0x161
#define FLAG_HIDE_ROUTE9_BURN_HEAL                                   0x1C2
#define FLAG_HIDE_ROUTE9_TM40                                        0x16B
#define FLAG_HIDE_ROUTE_12_SNORLAX                                   0x054
#define FLAG_HIDE_ROUTE_16_SNORLAX                                   0x080
#define FLAG_HIDE_ROUTE_22_RIVAL                                     0x04F
#define FLAG_HIDE_RUBY                                               0x08A
#define FLAG_HIDE_RUIN_VALLEY_SCIENTIST                              0x08E
#define FLAG_HIDE_SAFARI_ZONE_CENTER_NUGGET                          0x181
#define FLAG_HIDE_SAFARI_ZONE_EAST_FULL_RESTORE                      0x183
#define FLAG_HIDE_SAFARI_ZONE_EAST_LEAF_STONE                        0x185
#define FLAG_HIDE_SAFARI_ZONE_EAST_MAX_POTION                        0x182
#define FLAG_HIDE_SAFARI_ZONE_EAST_TM11                              0x184
#define FLAG_HIDE_SAFARI_ZONE_NORTH_PROTEIN                          0x186
#define FLAG_HIDE_SAFARI_ZONE_NORTH_QUICK_CLAW                       0x1D3
#define FLAG_HIDE_SAFARI_ZONE_NORTH_TM47                             0x187
#define FLAG_HIDE_SAFARI_ZONE_WEST_GOLD_TEETH                        0x189
#define FLAG_HIDE_SAFARI_ZONE_WEST_MAX_POTION                        0x18A
#define FLAG_HIDE_SAFARI_ZONE_WEST_MAX_REVIVE                        0x18B
#define FLAG_HIDE_SAFARI_ZONE_WEST_TM32                              0x188
#define FLAG_HIDE_SAFFRON_CITY_POKECENTER_SABRINA_JOURNALS           0x0AE
#define FLAG_HIDE_SAFFRON_CIVILIANS                                  0x03F
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY                            0x06F
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT                         0x06C
#define FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER                            0x06D
#define FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN                             0x06E
#define FLAG_HIDE_SAFFRON_ROCKETS                                    0x03E
#define FLAG_HIDE_SAPPHIRE                                           0x08F
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_1                               0x040
#define FLAG_HIDE_SEAFOAM_1F_BOULDER_2                               0x041
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_1                              0x042
#define FLAG_HIDE_SEAFOAM_B1F_BOULDER_2                              0x043
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_1                              0x044
#define FLAG_HIDE_SEAFOAM_B2F_BOULDER_2                              0x045
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_1                              0x046
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_2                              0x047
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_3                              0x048
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_4                              0x049
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_5                              0x04A
#define FLAG_HIDE_SEAFOAM_B3F_BOULDER_6                              0x04B
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_1                              0x04C
#define FLAG_HIDE_SEAFOAM_B4F_BOULDER_2                              0x04D
#define FLAG_HIDE_SEAFOAM_ISLANDS_1F_ICE_HEAL                        0x1D4
#define FLAG_HIDE_SEAFOAM_ISLANDS_B1F_REVIVE                         0x1D6
#define FLAG_HIDE_SEAFOAM_ISLANDS_B1F_WATER_STONE                    0x1D5
#define FLAG_HIDE_SEAFOAM_ISLANDS_B2F_BIG_PEARL                      0x1D7
#define FLAG_HIDE_SEAFOAM_ISLANDS_B4F_ULTRA_BALL                     0x1D8
#define FLAG_HIDE_SELPHYS_BUTLER                                     0x096
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE_LUCKY_PUNCH      0x1FD
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_KINGS_ROCK             0x1E7
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_MAX_ELIXIR             0x1E8
#define FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_NUGGET                 0x1E9
#define FLAG_HIDE_SILPH_CO_10F_CARBOS                                0x197
#define FLAG_HIDE_SILPH_CO_10F_RARE_CANDY                            0x199
#define FLAG_HIDE_SILPH_CO_10F_ULTRA_BALL                            0x198
#define FLAG_HIDE_SILPH_CO_11F_ZINC                                  0x1C9
#define FLAG_HIDE_SILPH_CO_3F_HYPER_POTION                           0x18C
#define FLAG_HIDE_SILPH_CO_4F_ESCAPE_ROPE                            0x18E
#define FLAG_HIDE_SILPH_CO_4F_FULL_HEAL                              0x18F
#define FLAG_HIDE_SILPH_CO_4F_MAX_REVIVE                             0x18D
#define FLAG_HIDE_SILPH_CO_4F_TM41                                   0x1FE
#define FLAG_HIDE_SILPH_CO_5F_CARD_KEY                               0x192
#define FLAG_HIDE_SILPH_CO_5F_PROTEIN                                0x190
#define FLAG_HIDE_SILPH_CO_5F_TM01                                   0x191
#define FLAG_HIDE_SILPH_CO_6F_HP_UP                                  0x193
#define FLAG_HIDE_SILPH_CO_6F_X_SPECIAL                              0x194
#define FLAG_HIDE_SILPH_CO_7F_CALCIUM                                0x195
#define FLAG_HIDE_SILPH_CO_7F_TM08                                   0x196
#define FLAG_HIDE_SILPH_CO_8F_IRON                                   0x1C8
#define FLAG_HIDE_SILPH_RIVAL                                        0x04E
#define FLAG_HIDE_SILPH_ROCKETS                                      0x053
#define FLAG_HIDE_SILPH_SCOPE                                        0x037
#define FLAG_HIDE_SIX_ISLAND_OUTCAST_ISLAND_PP_UP                    0x1E1
#define FLAG_HIDE_SIX_ISLAND_POKECENTER_RIVAL                        0x098
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_FULL_RESTORE                0x1E4
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_HP_UP                       0x1E5
#define FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_SUN_STONE                   0x1E6
#define FLAG_HIDE_SIX_ISLAND_WATER_PATH_DRAGON_SCALE                 0x1E3
#define FLAG_HIDE_SIX_ISLAND_WATER_PATH_ELIXIR                       0x1E2
#define FLAG_HIDE_SQUIRTLE_BALL                                      0x029
#define FLAG_HIDE_SSANNE_1F_ROOM2_TM31                               0x164
#define FLAG_HIDE_SSANNE_2F_ROOM2_STARDUST                           0x165
#define FLAG_HIDE_SSANNE_2F_ROOM4_X_ATTACK                           0x166
#define FLAG_HIDE_SSANNE_B1F_ROOM2_TM44                              0x167
#define FLAG_HIDE_SSANNE_B1F_ROOM3_ETHER                             0x168
#define FLAG_HIDE_SSANNE_B1F_ROOM5_SUPER_POTION                      0x169
#define FLAG_HIDE_SSANNE_KITCHEN_GREAT_BALL                          0x16A
#define FLAG_HIDE_SS_ANNE                                            0x087
#define FLAG_HIDE_SS_ANNE_RIVAL                                      0x03D
#define FLAG_HIDE_THREE_ISLAND_ANTIBIKERS                            0x07E
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_FULL_HEAL                0x1EB
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ELIXIR               0x1EC
#define FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ETHER                0x1EA
#define FLAG_HIDE_THREE_ISLAND_BIKERS                                0x079
#define FLAG_HIDE_THREE_ISLAND_LONE_BIKER                            0x091
#define FLAG_HIDE_THREE_ISLAND_ZINC                                  0x1BB
#define FLAG_HIDE_TOWER_FUJI                                         0x034
#define FLAG_HIDE_TOWER_RIVAL                                        0x051
#define FLAG_HIDE_TOWER_ROCKET_1                                     0x05E
#define FLAG_HIDE_TOWER_ROCKET_2                                     0x083
#define FLAG_HIDE_TOWER_ROCKET_3                                     0x084
#define FLAG_HIDE_TOWN_MAP                                           0x039
#define FLAG_HIDE_TWO_ISLAND_BEAUTY                                  0x07C
#define FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER                       0x074
#define FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE                    0x075
#define FLAG_HIDE_TWO_ISLAND_REVIVE                                  0x1BA
#define FLAG_HIDE_TWO_ISLAND_SUPER_NERD                              0x07D
#define FLAG_HIDE_TWO_ISLAND_WOMAN                                   0x07B
#define FLAG_HIDE_UNION_ROOM_PLAYER_1                                0x063
#define FLAG_HIDE_UNION_ROOM_PLAYER_2                                0x064
#define FLAG_HIDE_UNION_ROOM_PLAYER_3                                0x065
#define FLAG_HIDE_UNION_ROOM_PLAYER_4                                0x066
#define FLAG_HIDE_UNION_ROOM_PLAYER_5                                0x067
#define FLAG_HIDE_UNION_ROOM_PLAYER_6                                0x068
#define FLAG_HIDE_UNION_ROOM_PLAYER_7                                0x069
#define FLAG_HIDE_UNION_ROOM_PLAYER_8                                0x06A
#define FLAG_HIDE_VERMILION_CITY_OAKS_AIDE                           0x0A1
#define FLAG_HIDE_VICTORY_ROAD_1F_RARE_CANDY                         0x1A9
#define FLAG_HIDE_VICTORY_ROAD_1F_TM02                               0x1AA
#define FLAG_HIDE_VICTORY_ROAD_2F_BOULDER                            0x058
#define FLAG_HIDE_VICTORY_ROAD_2F_FULL_HEAL                          0x1AD
#define FLAG_HIDE_VICTORY_ROAD_2F_GUARD_SPEC                         0x1AB
#define FLAG_HIDE_VICTORY_ROAD_2F_TM07                               0x1AC
#define FLAG_HIDE_VICTORY_ROAD_2F_TM37                               0x1AE
#define FLAG_HIDE_VICTORY_ROAD_3F_BOULDER                            0x059
#define FLAG_HIDE_VICTORY_ROAD_3F_MAX_REVIVE                         0x1AF
#define FLAG_HIDE_VICTORY_ROAD_3F_TM50                               0x1B0
#define FLAG_HIDE_VIRIDIAN_CITY_POTION                               0x1CD
#define FLAG_HIDE_VIRIDIAN_FOREST_ANTIDOTE                           0x157
#define FLAG_HIDE_VIRIDIAN_FOREST_POKE_BALL                          0x156
#define FLAG_HIDE_VIRIDIAN_FOREST_POTION                             0x158
#define FLAG_HIDE_VIRIDIAN_FOREST_POTION_2                           0x1BE
#define FLAG_HIDE_VIRIDIAN_GIOVANNI                                  0x055
#define FLAG_HIDE_ZAPDOS                                             0x05D

// Kanto world-map (fly destination) flags — real values for Emerald+Kanto builds.
// Base 0x500 is above Kanto hidden items (max ~0x4B1) and well below FLAGS_COUNT.
#define FLAG_KANTO_WORLD_MAP_START                                   0x500
#define FLAG_WORLD_MAP_PALLET_TOWN                              (FLAG_KANTO_WORLD_MAP_START + 0x00)
#define FLAG_WORLD_MAP_VIRIDIAN_CITY                            (FLAG_KANTO_WORLD_MAP_START + 0x01)
#define FLAG_WORLD_MAP_PEWTER_CITY                              (FLAG_KANTO_WORLD_MAP_START + 0x02)
#define FLAG_WORLD_MAP_CERULEAN_CITY                            (FLAG_KANTO_WORLD_MAP_START + 0x03)
#define FLAG_WORLD_MAP_LAVENDER_TOWN                            (FLAG_KANTO_WORLD_MAP_START + 0x04)
#define FLAG_WORLD_MAP_VERMILION_CITY                           (FLAG_KANTO_WORLD_MAP_START + 0x05)
#define FLAG_WORLD_MAP_CELADON_CITY                             (FLAG_KANTO_WORLD_MAP_START + 0x06)
#define FLAG_WORLD_MAP_FUCHSIA_CITY                             (FLAG_KANTO_WORLD_MAP_START + 0x07)
#define FLAG_WORLD_MAP_CINNABAR_ISLAND                          (FLAG_KANTO_WORLD_MAP_START + 0x08)
#define FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR                  (FLAG_KANTO_WORLD_MAP_START + 0x09)
#define FLAG_WORLD_MAP_SAFFRON_CITY                             (FLAG_KANTO_WORLD_MAP_START + 0x0A)
#define FLAG_WORLD_MAP_ONE_ISLAND                               (FLAG_KANTO_WORLD_MAP_START + 0x0B)
#define FLAG_WORLD_MAP_TWO_ISLAND                               (FLAG_KANTO_WORLD_MAP_START + 0x0C)
#define FLAG_WORLD_MAP_THREE_ISLAND                             (FLAG_KANTO_WORLD_MAP_START + 0x0D)
#define FLAG_WORLD_MAP_FOUR_ISLAND                              (FLAG_KANTO_WORLD_MAP_START + 0x0E)
#define FLAG_WORLD_MAP_FIVE_ISLAND                              (FLAG_KANTO_WORLD_MAP_START + 0x0F)
#define FLAG_WORLD_MAP_SEVEN_ISLAND                             (FLAG_KANTO_WORLD_MAP_START + 0x10)
#define FLAG_WORLD_MAP_SIX_ISLAND                               (FLAG_KANTO_WORLD_MAP_START + 0x11)
#define FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F                 (FLAG_KANTO_WORLD_MAP_START + 0x12)
#define FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F                (FLAG_KANTO_WORLD_MAP_START + 0x13)
#define FLAG_WORLD_MAP_VIRIDIAN_FOREST                          (FLAG_KANTO_WORLD_MAP_START + 0x14)
#define FLAG_WORLD_MAP_MT_MOON_1F                               (FLAG_KANTO_WORLD_MAP_START + 0x15)
#define FLAG_WORLD_MAP_SSANNE_EXTERIOR                          (FLAG_KANTO_WORLD_MAP_START + 0x16)
#define FLAG_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL      (FLAG_KANTO_WORLD_MAP_START + 0x17)
#define FLAG_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL        (FLAG_KANTO_WORLD_MAP_START + 0x18)
#define FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F                        (FLAG_KANTO_WORLD_MAP_START + 0x19)
#define FLAG_WORLD_MAP_VICTORY_ROAD_1F                          (FLAG_KANTO_WORLD_MAP_START + 0x1A)
#define FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F                       (FLAG_KANTO_WORLD_MAP_START + 0x1B)
#define FLAG_WORLD_MAP_SILPH_CO_1F                              (FLAG_KANTO_WORLD_MAP_START + 0x1C)
#define FLAG_WORLD_MAP_POKEMON_MANSION_1F                       (FLAG_KANTO_WORLD_MAP_START + 0x1D)
#define FLAG_WORLD_MAP_SAFARI_ZONE_CENTER                       (FLAG_KANTO_WORLD_MAP_START + 0x1E)
#define FLAG_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM             (FLAG_KANTO_WORLD_MAP_START + 0x1F)
#define FLAG_WORLD_MAP_ROCK_TUNNEL_1F                           (FLAG_KANTO_WORLD_MAP_START + 0x20)
#define FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F                       (FLAG_KANTO_WORLD_MAP_START + 0x21)
#define FLAG_WORLD_MAP_POKEMON_TOWER_1F                         (FLAG_KANTO_WORLD_MAP_START + 0x22)
#define FLAG_WORLD_MAP_CERULEAN_CAVE_1F                         (FLAG_KANTO_WORLD_MAP_START + 0x23)
#define FLAG_WORLD_MAP_POWER_PLANT                              (FLAG_KANTO_WORLD_MAP_START + 0x24)
#define FLAG_WORLD_MAP_NAVEL_ROCK_EXTERIOR                      (FLAG_KANTO_WORLD_MAP_START + 0x25)
#define FLAG_WORLD_MAP_MT_EMBER_EXTERIOR                        (FLAG_KANTO_WORLD_MAP_START + 0x26)
#define FLAG_WORLD_MAP_THREE_ISLAND_BERRY_FOREST                (FLAG_KANTO_WORLD_MAP_START + 0x27)
#define FLAG_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE        (FLAG_KANTO_WORLD_MAP_START + 0x28)
#define FLAG_WORLD_MAP_FIVE_ISLAND_ROCKET_WAREHOUSE             (FLAG_KANTO_WORLD_MAP_START + 0x29)
#define FLAG_WORLD_MAP_TRAINER_TOWER_LOBBY                      (FLAG_KANTO_WORLD_MAP_START + 0x2A)
#define FLAG_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F                (FLAG_KANTO_WORLD_MAP_START + 0x2B)
#define FLAG_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE           (FLAG_KANTO_WORLD_MAP_START + 0x2C)
#define FLAG_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH                  (FLAG_KANTO_WORLD_MAP_START + 0x2D)
#define FLAG_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE                 (FLAG_KANTO_WORLD_MAP_START + 0x2E)
#define FLAG_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER (FLAG_KANTO_WORLD_MAP_START + 0x2F)
#define FLAG_WORLD_MAP_THREE_ISLAND_DUNSPARCE_TUNNEL            (FLAG_KANTO_WORLD_MAP_START + 0x30)
#define FLAG_WORLD_MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY   (FLAG_KANTO_WORLD_MAP_START + 0x31)
#define FLAG_WORLD_MAP_BIRTH_ISLAND_EXTERIOR                    (FLAG_KANTO_WORLD_MAP_START + 0x32)

// Kanto gym badge flags — separate from Hoenn's FLAG_BADGE01_GET..08_GET so that
// defeating a Hoenn gym never grants Kanto HM usage and vice versa.
// Slots 0x4B2–0x4B9 are unused in the main flags.h and within FLAGS_COUNT.
#define FLAG_KANTO_BADGE01_GET   0x4B2  // Boulder Badge  (Brock,     Pewter City)
#define FLAG_KANTO_BADGE02_GET   0x4B3  // Cascade Badge  (Misty,     Cerulean City)
#define FLAG_KANTO_BADGE03_GET   0x4B4  // Thunder Badge  (Lt. Surge, Vermilion City)
#define FLAG_KANTO_BADGE04_GET   0x4B5  // Rainbow Badge  (Erika,     Celadon City)
#define FLAG_KANTO_BADGE05_GET   0x4B6  // Soul Badge     (Koga,      Fuchsia City)
#define FLAG_KANTO_BADGE06_GET   0x4B7  // Marsh Badge    (Sabrina,   Saffron City)
#define FLAG_KANTO_BADGE07_GET   0x4B8  // Volcano Badge  (Blaine,    Cinnabar Island)
#define FLAG_KANTO_BADGE08_GET   0x4B9  // Earth Badge    (Giovanni,  Viridian City)
#define NUM_KANTO_BADGES         8

#endif // GUARD_CONSTANTS_FLAGS_KANTO_H
