#ifndef GUARD_CONSTANTS_OPPONENTS_KANTO_H
#define GUARD_CONSTANTS_OPPONENTS_KANTO_H

// Kanto (FRLG) trainer IDs for Emerald+Kanto cross-region builds.
// All FRLG trainer constants are re-defined with TRAINER_FRLG_OFFSET
// so they do not collide with Emerald's trainer array (max ID 855).
// Only included when FRLG_INCLUDE_KANTO_TILESETS=1 and IS_FRLG=0.

#ifndef TRAINER_FRLG_OFFSET
#define TRAINER_FRLG_OFFSET  1000
#endif

#undef  TRAINER_YOUNGSTER_BEN
#define TRAINER_YOUNGSTER_BEN                        (TRAINER_FRLG_OFFSET +    1)
#undef  TRAINER_YOUNGSTER_CALVIN
#define TRAINER_YOUNGSTER_CALVIN                     (TRAINER_FRLG_OFFSET +    2)
#undef  TRAINER_YOUNGSTER_JOSH
#define TRAINER_YOUNGSTER_JOSH                       (TRAINER_FRLG_OFFSET +    3)
#undef  TRAINER_YOUNGSTER_TIMMY
#define TRAINER_YOUNGSTER_TIMMY                      (TRAINER_FRLG_OFFSET +    4)
#undef  TRAINER_YOUNGSTER_JOEY
#define TRAINER_YOUNGSTER_JOEY                       (TRAINER_FRLG_OFFSET +    5)
#undef  TRAINER_YOUNGSTER_DAN
#define TRAINER_YOUNGSTER_DAN                        (TRAINER_FRLG_OFFSET +    6)
#undef  TRAINER_YOUNGSTER_CHAD
#define TRAINER_YOUNGSTER_CHAD                       (TRAINER_FRLG_OFFSET +    7)
#undef  TRAINER_YOUNGSTER_TYLER
#define TRAINER_YOUNGSTER_TYLER                      (TRAINER_FRLG_OFFSET +    8)
#undef  TRAINER_YOUNGSTER_EDDIE
#define TRAINER_YOUNGSTER_EDDIE                      (TRAINER_FRLG_OFFSET +    9)
#undef  TRAINER_YOUNGSTER_DILLON
#define TRAINER_YOUNGSTER_DILLON                     (TRAINER_FRLG_OFFSET +   10)
#undef  TRAINER_YOUNGSTER_YASU
#define TRAINER_YOUNGSTER_YASU                       (TRAINER_FRLG_OFFSET +   11)
#undef  TRAINER_YOUNGSTER_DAVE
#define TRAINER_YOUNGSTER_DAVE                       (TRAINER_FRLG_OFFSET +   12)
#undef  TRAINER_YOUNGSTER_BEN_2
#define TRAINER_YOUNGSTER_BEN_2                      (TRAINER_FRLG_OFFSET +   13)
#undef  TRAINER_BUG_CATCHER_RICK
#define TRAINER_BUG_CATCHER_RICK                     (TRAINER_FRLG_OFFSET +   14)
#undef  TRAINER_BUG_CATCHER_DOUG
#define TRAINER_BUG_CATCHER_DOUG                     (TRAINER_FRLG_OFFSET +   15)
#undef  TRAINER_BUG_CATCHER_SAMMY
#define TRAINER_BUG_CATCHER_SAMMY                    (TRAINER_FRLG_OFFSET +   16)
#undef  TRAINER_BUG_CATCHER_COLTON
#define TRAINER_BUG_CATCHER_COLTON                   (TRAINER_FRLG_OFFSET +   17)
#undef  TRAINER_BUG_CATCHER_GREG
#define TRAINER_BUG_CATCHER_GREG                     (TRAINER_FRLG_OFFSET +   18)
#undef  TRAINER_BUG_CATCHER_JAMES
#define TRAINER_BUG_CATCHER_JAMES                    (TRAINER_FRLG_OFFSET +   19)
#undef  TRAINER_BUG_CATCHER_KENT
#define TRAINER_BUG_CATCHER_KENT                     (TRAINER_FRLG_OFFSET +   20)
#undef  TRAINER_BUG_CATCHER_ROBBY
#define TRAINER_BUG_CATCHER_ROBBY                    (TRAINER_FRLG_OFFSET +   21)
#undef  TRAINER_BUG_CATCHER_CALE
#define TRAINER_BUG_CATCHER_CALE                     (TRAINER_FRLG_OFFSET +   22)
#undef  TRAINER_BUG_CATCHER_KEIGO
#define TRAINER_BUG_CATCHER_KEIGO                    (TRAINER_FRLG_OFFSET +   23)
#undef  TRAINER_BUG_CATCHER_ELIJAH
#define TRAINER_BUG_CATCHER_ELIJAH                   (TRAINER_FRLG_OFFSET +   24)
#undef  TRAINER_BUG_CATCHER_BRENT
#define TRAINER_BUG_CATCHER_BRENT                    (TRAINER_FRLG_OFFSET +   25)
#undef  TRAINER_BUG_CATCHER_CONNER
#define TRAINER_BUG_CATCHER_CONNER                   (TRAINER_FRLG_OFFSET +   26)
#undef  TRAINER_LASS_JANICE
#define TRAINER_LASS_JANICE                          (TRAINER_FRLG_OFFSET +   27)
#undef  TRAINER_LASS_SALLY
#define TRAINER_LASS_SALLY                           (TRAINER_FRLG_OFFSET +   28)
#undef  TRAINER_LASS_ROBIN
#define TRAINER_LASS_ROBIN                           (TRAINER_FRLG_OFFSET +   29)
#undef  TRAINER_LASS_CRISSY
#define TRAINER_LASS_CRISSY                          (TRAINER_FRLG_OFFSET +   30)
#undef  TRAINER_LASS_MIRIAM
#define TRAINER_LASS_MIRIAM                          (TRAINER_FRLG_OFFSET +   31)
#undef  TRAINER_LASS_IRIS
#define TRAINER_LASS_IRIS                            (TRAINER_FRLG_OFFSET +   32)
#undef  TRAINER_LASS_RELI
#define TRAINER_LASS_RELI                            (TRAINER_FRLG_OFFSET +   33)
#undef  TRAINER_LASS_ALI
#define TRAINER_LASS_ALI                             (TRAINER_FRLG_OFFSET +   34)
#undef  TRAINER_LASS_HALEY
#define TRAINER_LASS_HALEY                           (TRAINER_FRLG_OFFSET +   35)
#undef  TRAINER_LASS_ANN
#define TRAINER_LASS_ANN                             (TRAINER_FRLG_OFFSET +   36)
#undef  TRAINER_LASS_DAWN
#define TRAINER_LASS_DAWN                            (TRAINER_FRLG_OFFSET +   37)
#undef  TRAINER_LASS_PAIGE
#define TRAINER_LASS_PAIGE                           (TRAINER_FRLG_OFFSET +   38)
#undef  TRAINER_LASS_ANDREA
#define TRAINER_LASS_ANDREA                          (TRAINER_FRLG_OFFSET +   39)
#undef  TRAINER_LASS_MEGAN
#define TRAINER_LASS_MEGAN                           (TRAINER_FRLG_OFFSET +   40)
#undef  TRAINER_LASS_JULIA
#define TRAINER_LASS_JULIA                           (TRAINER_FRLG_OFFSET +   41)
#undef  TRAINER_LASS_KAY
#define TRAINER_LASS_KAY                             (TRAINER_FRLG_OFFSET +   42)
#undef  TRAINER_LASS_LISA
#define TRAINER_LASS_LISA                            (TRAINER_FRLG_OFFSET +   43)
#undef  TRAINER_SAILOR_EDMOND
#define TRAINER_SAILOR_EDMOND                        (TRAINER_FRLG_OFFSET +   44)
#undef  TRAINER_SAILOR_TREVOR
#define TRAINER_SAILOR_TREVOR                        (TRAINER_FRLG_OFFSET +   45)
#undef  TRAINER_SAILOR_LEONARD
#define TRAINER_SAILOR_LEONARD                       (TRAINER_FRLG_OFFSET +   46)
#undef  TRAINER_SAILOR_DUNCAN
#define TRAINER_SAILOR_DUNCAN                        (TRAINER_FRLG_OFFSET +   47)
#undef  TRAINER_SAILOR_HUEY
#define TRAINER_SAILOR_HUEY                          (TRAINER_FRLG_OFFSET +   48)
#undef  TRAINER_SAILOR_DYLAN
#define TRAINER_SAILOR_DYLAN                         (TRAINER_FRLG_OFFSET +   49)
#undef  TRAINER_SAILOR_PHILLIP
#define TRAINER_SAILOR_PHILLIP                       (TRAINER_FRLG_OFFSET +   50)
#undef  TRAINER_SAILOR_DWAYNE
#define TRAINER_SAILOR_DWAYNE                        (TRAINER_FRLG_OFFSET +   51)
#undef  TRAINER_CAMPER_LIAM
#define TRAINER_CAMPER_LIAM                          (TRAINER_FRLG_OFFSET +   52)
#undef  TRAINER_CAMPER_SHANE
#define TRAINER_CAMPER_SHANE                         (TRAINER_FRLG_OFFSET +   53)
#undef  TRAINER_CAMPER_ETHAN
#define TRAINER_CAMPER_ETHAN                         (TRAINER_FRLG_OFFSET +   54)
#undef  TRAINER_CAMPER_RICKY
#define TRAINER_CAMPER_RICKY                         (TRAINER_FRLG_OFFSET +   55)
#undef  TRAINER_CAMPER_JEFF
#define TRAINER_CAMPER_JEFF                          (TRAINER_FRLG_OFFSET +   56)
#undef  TRAINER_CAMPER_CHRIS
#define TRAINER_CAMPER_CHRIS                         (TRAINER_FRLG_OFFSET +   57)
#undef  TRAINER_CAMPER_DREW
#define TRAINER_CAMPER_DREW                          (TRAINER_FRLG_OFFSET +   58)
#undef  TRAINER_PICNICKER_DIANA
#define TRAINER_PICNICKER_DIANA                      (TRAINER_FRLG_OFFSET +   59)
#undef  TRAINER_PICNICKER_NANCY
#define TRAINER_PICNICKER_NANCY                      (TRAINER_FRLG_OFFSET +   60)
#undef  TRAINER_PICNICKER_ISABELLE
#define TRAINER_PICNICKER_ISABELLE                   (TRAINER_FRLG_OFFSET +   61)
#undef  TRAINER_PICNICKER_KELSEY
#define TRAINER_PICNICKER_KELSEY                     (TRAINER_FRLG_OFFSET +   62)
#undef  TRAINER_PICNICKER_ALICIA
#define TRAINER_PICNICKER_ALICIA                     (TRAINER_FRLG_OFFSET +   63)
#undef  TRAINER_PICNICKER_CAITLIN
#define TRAINER_PICNICKER_CAITLIN                    (TRAINER_FRLG_OFFSET +   64)
#undef  TRAINER_PICNICKER_HEIDI
#define TRAINER_PICNICKER_HEIDI                      (TRAINER_FRLG_OFFSET +   65)
#undef  TRAINER_PICNICKER_CAROL
#define TRAINER_PICNICKER_CAROL                      (TRAINER_FRLG_OFFSET +   66)
#undef  TRAINER_PICNICKER_SOFIA
#define TRAINER_PICNICKER_SOFIA                      (TRAINER_FRLG_OFFSET +   67)
#undef  TRAINER_PICNICKER_MARTHA
#define TRAINER_PICNICKER_MARTHA                     (TRAINER_FRLG_OFFSET +   68)
#undef  TRAINER_PICNICKER_TINA
#define TRAINER_PICNICKER_TINA                       (TRAINER_FRLG_OFFSET +   69)
#undef  TRAINER_PICNICKER_HANNAH
#define TRAINER_PICNICKER_HANNAH                     (TRAINER_FRLG_OFFSET +   70)
#undef  TRAINER_POKEMANIAC_MARK
#define TRAINER_POKEMANIAC_MARK                      (TRAINER_FRLG_OFFSET +   71)
#undef  TRAINER_POKEMANIAC_HERMAN
#define TRAINER_POKEMANIAC_HERMAN                    (TRAINER_FRLG_OFFSET +   72)
#undef  TRAINER_POKEMANIAC_COOPER
#define TRAINER_POKEMANIAC_COOPER                    (TRAINER_FRLG_OFFSET +   73)
#undef  TRAINER_POKEMANIAC_STEVE
#define TRAINER_POKEMANIAC_STEVE                     (TRAINER_FRLG_OFFSET +   74)
#undef  TRAINER_POKEMANIAC_WINSTON
#define TRAINER_POKEMANIAC_WINSTON                   (TRAINER_FRLG_OFFSET +   75)
#undef  TRAINER_POKEMANIAC_DAWSON
#define TRAINER_POKEMANIAC_DAWSON                    (TRAINER_FRLG_OFFSET +   76)
#undef  TRAINER_POKEMANIAC_ASHTON
#define TRAINER_POKEMANIAC_ASHTON                    (TRAINER_FRLG_OFFSET +   77)
#undef  TRAINER_SUPER_NERD_JOVAN
#define TRAINER_SUPER_NERD_JOVAN                     (TRAINER_FRLG_OFFSET +   78)
#undef  TRAINER_SUPER_NERD_MIGUEL
#define TRAINER_SUPER_NERD_MIGUEL                    (TRAINER_FRLG_OFFSET +   79)
#undef  TRAINER_SUPER_NERD_AIDAN
#define TRAINER_SUPER_NERD_AIDAN                     (TRAINER_FRLG_OFFSET +   80)
#undef  TRAINER_SUPER_NERD_GLENN
#define TRAINER_SUPER_NERD_GLENN                     (TRAINER_FRLG_OFFSET +   81)
#undef  TRAINER_SUPER_NERD_LESLIE
#define TRAINER_SUPER_NERD_LESLIE                    (TRAINER_FRLG_OFFSET +   82)
#undef  TRAINER_SUPER_NERD_ERIK
#define TRAINER_SUPER_NERD_ERIK                      (TRAINER_FRLG_OFFSET +   83)
#undef  TRAINER_SUPER_NERD_AVERY
#define TRAINER_SUPER_NERD_AVERY                     (TRAINER_FRLG_OFFSET +   84)
#undef  TRAINER_SUPER_NERD_DEREK
#define TRAINER_SUPER_NERD_DEREK                     (TRAINER_FRLG_OFFSET +   85)
#undef  TRAINER_SUPER_NERD_ZAC
#define TRAINER_SUPER_NERD_ZAC                       (TRAINER_FRLG_OFFSET +   86)
#undef  TRAINER_HIKER_MARCOS
#define TRAINER_HIKER_MARCOS                         (TRAINER_FRLG_OFFSET +   87)
#undef  TRAINER_HIKER_FRANKLIN
#define TRAINER_HIKER_FRANKLIN                       (TRAINER_FRLG_OFFSET +   88)
#undef  TRAINER_HIKER_NOB
#define TRAINER_HIKER_NOB                            (TRAINER_FRLG_OFFSET +   89)
#undef  TRAINER_HIKER_WAYNE
#define TRAINER_HIKER_WAYNE                          (TRAINER_FRLG_OFFSET +   90)
#undef  TRAINER_HIKER_ALAN
#define TRAINER_HIKER_ALAN                           (TRAINER_FRLG_OFFSET +   91)
#undef  TRAINER_HIKER_BRICE
#define TRAINER_HIKER_BRICE                          (TRAINER_FRLG_OFFSET +   92)
#undef  TRAINER_HIKER_CLARK
#define TRAINER_HIKER_CLARK                          (TRAINER_FRLG_OFFSET +   93)
#undef  TRAINER_HIKER_TRENT
#define TRAINER_HIKER_TRENT                          (TRAINER_FRLG_OFFSET +   94)
#undef  TRAINER_HIKER_DUDLEY
#define TRAINER_HIKER_DUDLEY                         (TRAINER_FRLG_OFFSET +   95)
#undef  TRAINER_HIKER_ALLEN
#define TRAINER_HIKER_ALLEN                          (TRAINER_FRLG_OFFSET +   96)
#undef  TRAINER_HIKER_ERIC
#define TRAINER_HIKER_ERIC                           (TRAINER_FRLG_OFFSET +   97)
#undef  TRAINER_HIKER_LENNY
#define TRAINER_HIKER_LENNY                          (TRAINER_FRLG_OFFSET +   98)
#undef  TRAINER_HIKER_OLIVER
#define TRAINER_HIKER_OLIVER                         (TRAINER_FRLG_OFFSET +   99)
#undef  TRAINER_HIKER_LUCAS
#define TRAINER_HIKER_LUCAS                          (TRAINER_FRLG_OFFSET +  100)
#undef  TRAINER_BIKER_JARED
#define TRAINER_BIKER_JARED                          (TRAINER_FRLG_OFFSET +  101)
#undef  TRAINER_BIKER_MALIK
#define TRAINER_BIKER_MALIK                          (TRAINER_FRLG_OFFSET +  102)
#undef  TRAINER_BIKER_ERNEST
#define TRAINER_BIKER_ERNEST                         (TRAINER_FRLG_OFFSET +  103)
#undef  TRAINER_BIKER_ALEX
#define TRAINER_BIKER_ALEX                           (TRAINER_FRLG_OFFSET +  104)
#undef  TRAINER_BIKER_LAO
#define TRAINER_BIKER_LAO                            (TRAINER_FRLG_OFFSET +  105)
#undef  TRAINER_BIKER_HIDEO
#define TRAINER_BIKER_HIDEO                          (TRAINER_FRLG_OFFSET +  106)
#undef  TRAINER_BIKER_RUBEN
#define TRAINER_BIKER_RUBEN                          (TRAINER_FRLG_OFFSET +  107)
#undef  TRAINER_BIKER_BILLY
#define TRAINER_BIKER_BILLY                          (TRAINER_FRLG_OFFSET +  108)
#undef  TRAINER_BIKER_NIKOLAS
#define TRAINER_BIKER_NIKOLAS                        (TRAINER_FRLG_OFFSET +  109)
#undef  TRAINER_BIKER_JAXON
#define TRAINER_BIKER_JAXON                          (TRAINER_FRLG_OFFSET +  110)
#undef  TRAINER_BIKER_WILLIAM
#define TRAINER_BIKER_WILLIAM                        (TRAINER_FRLG_OFFSET +  111)
#undef  TRAINER_BIKER_LUKAS
#define TRAINER_BIKER_LUKAS                          (TRAINER_FRLG_OFFSET +  112)
#undef  TRAINER_BIKER_ISAAC
#define TRAINER_BIKER_ISAAC                          (TRAINER_FRLG_OFFSET +  113)
#undef  TRAINER_BIKER_GERALD
#define TRAINER_BIKER_GERALD                         (TRAINER_FRLG_OFFSET +  114)
#undef  TRAINER_BURGLAR_QUINN
#define TRAINER_BURGLAR_QUINN                        (TRAINER_FRLG_OFFSET +  115)
#undef  TRAINER_BURGLAR_RAMON
#define TRAINER_BURGLAR_RAMON                        (TRAINER_FRLG_OFFSET +  116)
#undef  TRAINER_BURGLAR_DUSTY
#define TRAINER_BURGLAR_DUSTY                        (TRAINER_FRLG_OFFSET +  117)
#undef  TRAINER_BURGLAR_ARNIE
#define TRAINER_BURGLAR_ARNIE                        (TRAINER_FRLG_OFFSET +  118)
#undef  TRAINER_BURGLAR_SIMON
#define TRAINER_BURGLAR_SIMON                        (TRAINER_FRLG_OFFSET +  119)
#undef  TRAINER_BURGLAR_LEWIS
#define TRAINER_BURGLAR_LEWIS                        (TRAINER_FRLG_OFFSET +  120)
#undef  TRAINER_ENGINEER_BAILY
#define TRAINER_ENGINEER_BAILY                       (TRAINER_FRLG_OFFSET +  121)
#undef  TRAINER_ENGINEER_BRAXTON
#define TRAINER_ENGINEER_BRAXTON                     (TRAINER_FRLG_OFFSET +  122)
#undef  TRAINER_ENGINEER_BERNIE
#define TRAINER_ENGINEER_BERNIE                      (TRAINER_FRLG_OFFSET +  123)
#undef  TRAINER_FISHERMAN_DALE
#define TRAINER_FISHERMAN_DALE                       (TRAINER_FRLG_OFFSET +  124)
#undef  TRAINER_FISHERMAN_BARNY
#define TRAINER_FISHERMAN_BARNY                      (TRAINER_FRLG_OFFSET +  125)
#undef  TRAINER_FISHERMAN_NED
#define TRAINER_FISHERMAN_NED                        (TRAINER_FRLG_OFFSET +  126)
#undef  TRAINER_FISHERMAN_CHIP
#define TRAINER_FISHERMAN_CHIP                       (TRAINER_FRLG_OFFSET +  127)
#undef  TRAINER_FISHERMAN_HANK
#define TRAINER_FISHERMAN_HANK                       (TRAINER_FRLG_OFFSET +  128)
#undef  TRAINER_FISHERMAN_ELLIOT
#define TRAINER_FISHERMAN_ELLIOT                     (TRAINER_FRLG_OFFSET +  129)
#undef  TRAINER_FISHERMAN_RONALD
#define TRAINER_FISHERMAN_RONALD                     (TRAINER_FRLG_OFFSET +  130)
#undef  TRAINER_FISHERMAN_CLAUDE
#define TRAINER_FISHERMAN_CLAUDE                     (TRAINER_FRLG_OFFSET +  131)
#undef  TRAINER_FISHERMAN_WADE
#define TRAINER_FISHERMAN_WADE                       (TRAINER_FRLG_OFFSET +  132)
#undef  TRAINER_FISHERMAN_NOLAN
#define TRAINER_FISHERMAN_NOLAN                      (TRAINER_FRLG_OFFSET +  133)
#undef  TRAINER_FISHERMAN_ANDREW
#define TRAINER_FISHERMAN_ANDREW                     (TRAINER_FRLG_OFFSET +  134)
#undef  TRAINER_SWIMMER_MALE_LUIS
#define TRAINER_SWIMMER_MALE_LUIS                    (TRAINER_FRLG_OFFSET +  135)
#undef  TRAINER_SWIMMER_MALE_RICHARD
#define TRAINER_SWIMMER_MALE_RICHARD                 (TRAINER_FRLG_OFFSET +  136)
#undef  TRAINER_SWIMMER_MALE_REECE
#define TRAINER_SWIMMER_MALE_REECE                   (TRAINER_FRLG_OFFSET +  137)
#undef  TRAINER_SWIMMER_MALE_MATTHEW
#define TRAINER_SWIMMER_MALE_MATTHEW                 (TRAINER_FRLG_OFFSET +  138)
#undef  TRAINER_SWIMMER_MALE_DOUGLAS
#define TRAINER_SWIMMER_MALE_DOUGLAS                 (TRAINER_FRLG_OFFSET +  139)
#undef  TRAINER_SWIMMER_MALE_DAVID
#define TRAINER_SWIMMER_MALE_DAVID                   (TRAINER_FRLG_OFFSET +  140)
#undef  TRAINER_SWIMMER_MALE_TONY
#define TRAINER_SWIMMER_MALE_TONY                    (TRAINER_FRLG_OFFSET +  141)
#undef  TRAINER_SWIMMER_MALE_AXLE
#define TRAINER_SWIMMER_MALE_AXLE                    (TRAINER_FRLG_OFFSET +  142)
#undef  TRAINER_SWIMMER_MALE_BARRY
#define TRAINER_SWIMMER_MALE_BARRY                   (TRAINER_FRLG_OFFSET +  143)
#undef  TRAINER_SWIMMER_MALE_DEAN
#define TRAINER_SWIMMER_MALE_DEAN                    (TRAINER_FRLG_OFFSET +  144)
#undef  TRAINER_SWIMMER_MALE_DARRIN
#define TRAINER_SWIMMER_MALE_DARRIN                  (TRAINER_FRLG_OFFSET +  145)
#undef  TRAINER_SWIMMER_MALE_SPENCER
#define TRAINER_SWIMMER_MALE_SPENCER                 (TRAINER_FRLG_OFFSET +  146)
#undef  TRAINER_SWIMMER_MALE_JACK
#define TRAINER_SWIMMER_MALE_JACK                    (TRAINER_FRLG_OFFSET +  147)
#undef  TRAINER_SWIMMER_MALE_JEROME
#define TRAINER_SWIMMER_MALE_JEROME                  (TRAINER_FRLG_OFFSET +  148)
#undef  TRAINER_SWIMMER_MALE_ROLAND
#define TRAINER_SWIMMER_MALE_ROLAND                  (TRAINER_FRLG_OFFSET +  149)
#undef  TRAINER_CUE_BALL_KOJI
#define TRAINER_CUE_BALL_KOJI                        (TRAINER_FRLG_OFFSET +  150)
#undef  TRAINER_CUE_BALL_LUKE
#define TRAINER_CUE_BALL_LUKE                        (TRAINER_FRLG_OFFSET +  151)
#undef  TRAINER_CUE_BALL_CAMRON
#define TRAINER_CUE_BALL_CAMRON                      (TRAINER_FRLG_OFFSET +  152)
#undef  TRAINER_CUE_BALL_RAUL
#define TRAINER_CUE_BALL_RAUL                        (TRAINER_FRLG_OFFSET +  153)
#undef  TRAINER_CUE_BALL_ISAIAH
#define TRAINER_CUE_BALL_ISAIAH                      (TRAINER_FRLG_OFFSET +  154)
#undef  TRAINER_CUE_BALL_ZEEK
#define TRAINER_CUE_BALL_ZEEK                        (TRAINER_FRLG_OFFSET +  155)
#undef  TRAINER_CUE_BALL_JAMAL
#define TRAINER_CUE_BALL_JAMAL                       (TRAINER_FRLG_OFFSET +  156)
#undef  TRAINER_CUE_BALL_COREY
#define TRAINER_CUE_BALL_COREY                       (TRAINER_FRLG_OFFSET +  157)
#undef  TRAINER_CUE_BALL_CHASE
#define TRAINER_CUE_BALL_CHASE                       (TRAINER_FRLG_OFFSET +  158)
#undef  TRAINER_GAMER_HUGO
#define TRAINER_GAMER_HUGO                           (TRAINER_FRLG_OFFSET +  159)
#undef  TRAINER_GAMER_JASPER
#define TRAINER_GAMER_JASPER                         (TRAINER_FRLG_OFFSET +  160)
#undef  TRAINER_GAMER_DIRK
#define TRAINER_GAMER_DIRK                           (TRAINER_FRLG_OFFSET +  161)
#undef  TRAINER_GAMER_DARIAN
#define TRAINER_GAMER_DARIAN                         (TRAINER_FRLG_OFFSET +  162)
#undef  TRAINER_GAMER_STAN
#define TRAINER_GAMER_STAN                           (TRAINER_FRLG_OFFSET +  163)
#undef  TRAINER_GAMER_RICH
#define TRAINER_GAMER_RICH                           (TRAINER_FRLG_OFFSET +  164)
#undef  TRAINER_BEAUTY_BRIDGET
#define TRAINER_BEAUTY_BRIDGET                       (TRAINER_FRLG_OFFSET +  165)
#undef  TRAINER_BEAUTY_TAMIA
#define TRAINER_BEAUTY_TAMIA                         (TRAINER_FRLG_OFFSET +  166)
#undef  TRAINER_BEAUTY_LORI
#define TRAINER_BEAUTY_LORI                          (TRAINER_FRLG_OFFSET +  167)
#undef  TRAINER_BEAUTY_LOLA
#define TRAINER_BEAUTY_LOLA                          (TRAINER_FRLG_OFFSET +  168)
#undef  TRAINER_BEAUTY_SHEILA
#define TRAINER_BEAUTY_SHEILA                        (TRAINER_FRLG_OFFSET +  169)
#undef  TRAINER_SWIMMER_FEMALE_TIFFANY
#define TRAINER_SWIMMER_FEMALE_TIFFANY               (TRAINER_FRLG_OFFSET +  170)
#undef  TRAINER_SWIMMER_FEMALE_NORA
#define TRAINER_SWIMMER_FEMALE_NORA                  (TRAINER_FRLG_OFFSET +  171)
#undef  TRAINER_SWIMMER_FEMALE_MELISSA
#define TRAINER_SWIMMER_FEMALE_MELISSA               (TRAINER_FRLG_OFFSET +  172)
#undef  TRAINER_BEAUTY_GRACE
#define TRAINER_BEAUTY_GRACE                         (TRAINER_FRLG_OFFSET +  173)
#undef  TRAINER_BEAUTY_OLIVIA
#define TRAINER_BEAUTY_OLIVIA                        (TRAINER_FRLG_OFFSET +  174)
#undef  TRAINER_BEAUTY_LAUREN
#define TRAINER_BEAUTY_LAUREN                        (TRAINER_FRLG_OFFSET +  175)
#undef  TRAINER_SWIMMER_FEMALE_ANYA
#define TRAINER_SWIMMER_FEMALE_ANYA                  (TRAINER_FRLG_OFFSET +  176)
#undef  TRAINER_SWIMMER_FEMALE_ALICE
#define TRAINER_SWIMMER_FEMALE_ALICE                 (TRAINER_FRLG_OFFSET +  177)
#undef  TRAINER_SWIMMER_FEMALE_CONNIE
#define TRAINER_SWIMMER_FEMALE_CONNIE                (TRAINER_FRLG_OFFSET +  178)
#undef  TRAINER_SWIMMER_FEMALE_SHIRLEY
#define TRAINER_SWIMMER_FEMALE_SHIRLEY               (TRAINER_FRLG_OFFSET +  179)
#undef  TRAINER_PSYCHIC_JOHAN
#define TRAINER_PSYCHIC_JOHAN                        (TRAINER_FRLG_OFFSET +  180)
#undef  TRAINER_PSYCHIC_TYRON
#define TRAINER_PSYCHIC_TYRON                        (TRAINER_FRLG_OFFSET +  181)
#undef  TRAINER_PSYCHIC_CAMERON
#define TRAINER_PSYCHIC_CAMERON                      (TRAINER_FRLG_OFFSET +  182)
#undef  TRAINER_PSYCHIC_PRESTON
#define TRAINER_PSYCHIC_PRESTON                      (TRAINER_FRLG_OFFSET +  183)
#undef  TRAINER_ROCKER_RANDALL
#define TRAINER_ROCKER_RANDALL                       (TRAINER_FRLG_OFFSET +  184)
#undef  TRAINER_ROCKER_LUCA
#define TRAINER_ROCKER_LUCA                          (TRAINER_FRLG_OFFSET +  185)
#undef  TRAINER_JUGGLER_DALTON
#define TRAINER_JUGGLER_DALTON                       (TRAINER_FRLG_OFFSET +  186)
#undef  TRAINER_JUGGLER_NELSON
#define TRAINER_JUGGLER_NELSON                       (TRAINER_FRLG_OFFSET +  187)
#undef  TRAINER_JUGGLER_KIRK
#define TRAINER_JUGGLER_KIRK                         (TRAINER_FRLG_OFFSET +  188)
#undef  TRAINER_JUGGLER_SHAWN
#define TRAINER_JUGGLER_SHAWN                        (TRAINER_FRLG_OFFSET +  189)
#undef  TRAINER_JUGGLER_GREGORY
#define TRAINER_JUGGLER_GREGORY                      (TRAINER_FRLG_OFFSET +  190)
#undef  TRAINER_JUGGLER_EDWARD
#define TRAINER_JUGGLER_EDWARD                       (TRAINER_FRLG_OFFSET +  191)
#undef  TRAINER_JUGGLER_KAYDEN
#define TRAINER_JUGGLER_KAYDEN                       (TRAINER_FRLG_OFFSET +  192)
#undef  TRAINER_JUGGLER_NATE
#define TRAINER_JUGGLER_NATE                         (TRAINER_FRLG_OFFSET +  193)
#undef  TRAINER_TAMER_PHIL
#define TRAINER_TAMER_PHIL                           (TRAINER_FRLG_OFFSET +  194)
#undef  TRAINER_TAMER_EDGAR
#define TRAINER_TAMER_EDGAR                          (TRAINER_FRLG_OFFSET +  195)
#undef  TRAINER_TAMER_JASON
#define TRAINER_TAMER_JASON                          (TRAINER_FRLG_OFFSET +  196)
#undef  TRAINER_TAMER_COLE
#define TRAINER_TAMER_COLE                           (TRAINER_FRLG_OFFSET +  197)
#undef  TRAINER_TAMER_VINCENT
#define TRAINER_TAMER_VINCENT                        (TRAINER_FRLG_OFFSET +  198)
#undef  TRAINER_TAMER_JOHN
#define TRAINER_TAMER_JOHN                           (TRAINER_FRLG_OFFSET +  199)
#undef  TRAINER_BIRD_KEEPER_SEBASTIAN
#define TRAINER_BIRD_KEEPER_SEBASTIAN                (TRAINER_FRLG_OFFSET +  200)
#undef  TRAINER_BIRD_KEEPER_PERRY
#define TRAINER_BIRD_KEEPER_PERRY                    (TRAINER_FRLG_OFFSET +  201)
#undef  TRAINER_BIRD_KEEPER_ROBERT
#define TRAINER_BIRD_KEEPER_ROBERT                   (TRAINER_FRLG_OFFSET +  202)
#undef  TRAINER_BIRD_KEEPER_DONALD
#define TRAINER_BIRD_KEEPER_DONALD                   (TRAINER_FRLG_OFFSET +  203)
#undef  TRAINER_BIRD_KEEPER_BENNY
#define TRAINER_BIRD_KEEPER_BENNY                    (TRAINER_FRLG_OFFSET +  204)
#undef  TRAINER_BIRD_KEEPER_EDWIN
#define TRAINER_BIRD_KEEPER_EDWIN                    (TRAINER_FRLG_OFFSET +  205)
#undef  TRAINER_BIRD_KEEPER_CHESTER
#define TRAINER_BIRD_KEEPER_CHESTER                  (TRAINER_FRLG_OFFSET +  206)
#undef  TRAINER_BIRD_KEEPER_WILTON
#define TRAINER_BIRD_KEEPER_WILTON                   (TRAINER_FRLG_OFFSET +  207)
#undef  TRAINER_BIRD_KEEPER_RAMIRO
#define TRAINER_BIRD_KEEPER_RAMIRO                   (TRAINER_FRLG_OFFSET +  208)
#undef  TRAINER_BIRD_KEEPER_JACOB
#define TRAINER_BIRD_KEEPER_JACOB                    (TRAINER_FRLG_OFFSET +  209)
#undef  TRAINER_BIRD_KEEPER_ROGER
#define TRAINER_BIRD_KEEPER_ROGER                    (TRAINER_FRLG_OFFSET +  210)
#undef  TRAINER_BIRD_KEEPER_REED
#define TRAINER_BIRD_KEEPER_REED                     (TRAINER_FRLG_OFFSET +  211)
#undef  TRAINER_BIRD_KEEPER_KEITH
#define TRAINER_BIRD_KEEPER_KEITH                    (TRAINER_FRLG_OFFSET +  212)
#undef  TRAINER_BIRD_KEEPER_CARTER
#define TRAINER_BIRD_KEEPER_CARTER                   (TRAINER_FRLG_OFFSET +  213)
#undef  TRAINER_BIRD_KEEPER_MITCH
#define TRAINER_BIRD_KEEPER_MITCH                    (TRAINER_FRLG_OFFSET +  214)
#undef  TRAINER_BIRD_KEEPER_BECK
#define TRAINER_BIRD_KEEPER_BECK                     (TRAINER_FRLG_OFFSET +  215)
#undef  TRAINER_BIRD_KEEPER_MARLON
#define TRAINER_BIRD_KEEPER_MARLON                   (TRAINER_FRLG_OFFSET +  216)
#undef  TRAINER_BLACK_BELT_KOICHI
#define TRAINER_BLACK_BELT_KOICHI                    (TRAINER_FRLG_OFFSET +  217)
#undef  TRAINER_BLACK_BELT_MIKE
#define TRAINER_BLACK_BELT_MIKE                      (TRAINER_FRLG_OFFSET +  218)
#undef  TRAINER_BLACK_BELT_HIDEKI
#define TRAINER_BLACK_BELT_HIDEKI                    (TRAINER_FRLG_OFFSET +  219)
#undef  TRAINER_BLACK_BELT_AARON
#define TRAINER_BLACK_BELT_AARON                     (TRAINER_FRLG_OFFSET +  220)
#undef  TRAINER_BLACK_BELT_HITOSHI
#define TRAINER_BLACK_BELT_HITOSHI                   (TRAINER_FRLG_OFFSET +  221)
#undef  TRAINER_BLACK_BELT_ATSUSHI
#define TRAINER_BLACK_BELT_ATSUSHI                   (TRAINER_FRLG_OFFSET +  222)
#undef  TRAINER_BLACK_BELT_KIYO
#define TRAINER_BLACK_BELT_KIYO                      (TRAINER_FRLG_OFFSET +  223)
#undef  TRAINER_BLACK_BELT_TAKASHI
#define TRAINER_BLACK_BELT_TAKASHI                   (TRAINER_FRLG_OFFSET +  224)
#undef  TRAINER_BLACK_BELT_DAISUKE
#define TRAINER_BLACK_BELT_DAISUKE                   (TRAINER_FRLG_OFFSET +  225)
#undef  TRAINER_RIVAL_OAKS_LAB_SQUIRTLE
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE              (TRAINER_FRLG_OFFSET +  226)
#undef  TRAINER_RIVAL_OAKS_LAB_BULBASAUR
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR             (TRAINER_FRLG_OFFSET +  227)
#undef  TRAINER_RIVAL_OAKS_LAB_CHARMANDER
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER            (TRAINER_FRLG_OFFSET +  228)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE         (TRAINER_FRLG_OFFSET +  229)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR        (TRAINER_FRLG_OFFSET +  230)
#undef  TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER       (TRAINER_FRLG_OFFSET +  231)
#undef  TRAINER_RIVAL_CERULEAN_SQUIRTLE
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE              (TRAINER_FRLG_OFFSET +  232)
#undef  TRAINER_RIVAL_CERULEAN_BULBASAUR
#define TRAINER_RIVAL_CERULEAN_BULBASAUR             (TRAINER_FRLG_OFFSET +  233)
#undef  TRAINER_RIVAL_CERULEAN_CHARMANDER
#define TRAINER_RIVAL_CERULEAN_CHARMANDER            (TRAINER_FRLG_OFFSET +  234)
#undef  TRAINER_SCIENTIST_TED
#define TRAINER_SCIENTIST_TED                        (TRAINER_FRLG_OFFSET +  235)
#undef  TRAINER_SCIENTIST_CONNOR
#define TRAINER_SCIENTIST_CONNOR                     (TRAINER_FRLG_OFFSET +  236)
#undef  TRAINER_SCIENTIST_JERRY
#define TRAINER_SCIENTIST_JERRY                      (TRAINER_FRLG_OFFSET +  237)
#undef  TRAINER_SCIENTIST_JOSE
#define TRAINER_SCIENTIST_JOSE                       (TRAINER_FRLG_OFFSET +  238)
#undef  TRAINER_SCIENTIST_RODNEY
#define TRAINER_SCIENTIST_RODNEY                     (TRAINER_FRLG_OFFSET +  239)
#undef  TRAINER_SCIENTIST_BEAU
#define TRAINER_SCIENTIST_BEAU                       (TRAINER_FRLG_OFFSET +  240)
#undef  TRAINER_SCIENTIST_TAYLOR
#define TRAINER_SCIENTIST_TAYLOR                     (TRAINER_FRLG_OFFSET +  241)
#undef  TRAINER_SCIENTIST_JOSHUA
#define TRAINER_SCIENTIST_JOSHUA                     (TRAINER_FRLG_OFFSET +  242)
#undef  TRAINER_SCIENTIST_PARKER
#define TRAINER_SCIENTIST_PARKER                     (TRAINER_FRLG_OFFSET +  243)
#undef  TRAINER_SCIENTIST_ED
#define TRAINER_SCIENTIST_ED                         (TRAINER_FRLG_OFFSET +  244)
#undef  TRAINER_SCIENTIST_TRAVIS
#define TRAINER_SCIENTIST_TRAVIS                     (TRAINER_FRLG_OFFSET +  245)
#undef  TRAINER_SCIENTIST_BRAYDON
#define TRAINER_SCIENTIST_BRAYDON                    (TRAINER_FRLG_OFFSET +  246)
#undef  TRAINER_SCIENTIST_IVAN
#define TRAINER_SCIENTIST_IVAN                       (TRAINER_FRLG_OFFSET +  247)
#undef  TRAINER_BOSS_GIOVANNI
#define TRAINER_BOSS_GIOVANNI                        (TRAINER_FRLG_OFFSET +  248)
#undef  TRAINER_BOSS_GIOVANNI_2
#define TRAINER_BOSS_GIOVANNI_2                      (TRAINER_FRLG_OFFSET +  249)
#undef  TRAINER_LEADER_GIOVANNI
#define TRAINER_LEADER_GIOVANNI                      (TRAINER_FRLG_OFFSET +  250)
#undef  TRAINER_TEAM_ROCKET_GRUNT
#define TRAINER_TEAM_ROCKET_GRUNT                    (TRAINER_FRLG_OFFSET +  251)
#undef  TRAINER_TEAM_ROCKET_GRUNT_2
#define TRAINER_TEAM_ROCKET_GRUNT_2                  (TRAINER_FRLG_OFFSET +  252)
#undef  TRAINER_TEAM_ROCKET_GRUNT_3
#define TRAINER_TEAM_ROCKET_GRUNT_3                  (TRAINER_FRLG_OFFSET +  253)
#undef  TRAINER_TEAM_ROCKET_GRUNT_4
#define TRAINER_TEAM_ROCKET_GRUNT_4                  (TRAINER_FRLG_OFFSET +  254)
#undef  TRAINER_TEAM_ROCKET_GRUNT_5
#define TRAINER_TEAM_ROCKET_GRUNT_5                  (TRAINER_FRLG_OFFSET +  255)
#undef  TRAINER_TEAM_ROCKET_GRUNT_6
#define TRAINER_TEAM_ROCKET_GRUNT_6                  (TRAINER_FRLG_OFFSET +  256)
#undef  TRAINER_TEAM_ROCKET_GRUNT_7
#define TRAINER_TEAM_ROCKET_GRUNT_7                  (TRAINER_FRLG_OFFSET +  257)
#undef  TRAINER_TEAM_ROCKET_GRUNT_8
#define TRAINER_TEAM_ROCKET_GRUNT_8                  (TRAINER_FRLG_OFFSET +  258)
#undef  TRAINER_TEAM_ROCKET_GRUNT_9
#define TRAINER_TEAM_ROCKET_GRUNT_9                  (TRAINER_FRLG_OFFSET +  259)
#undef  TRAINER_TEAM_ROCKET_GRUNT_10
#define TRAINER_TEAM_ROCKET_GRUNT_10                 (TRAINER_FRLG_OFFSET +  260)
#undef  TRAINER_TEAM_ROCKET_GRUNT_11
#define TRAINER_TEAM_ROCKET_GRUNT_11                 (TRAINER_FRLG_OFFSET +  261)
#undef  TRAINER_TEAM_ROCKET_GRUNT_12
#define TRAINER_TEAM_ROCKET_GRUNT_12                 (TRAINER_FRLG_OFFSET +  262)
#undef  TRAINER_TEAM_ROCKET_GRUNT_13
#define TRAINER_TEAM_ROCKET_GRUNT_13                 (TRAINER_FRLG_OFFSET +  263)
#undef  TRAINER_TEAM_ROCKET_GRUNT_14
#define TRAINER_TEAM_ROCKET_GRUNT_14                 (TRAINER_FRLG_OFFSET +  264)
#undef  TRAINER_TEAM_ROCKET_GRUNT_15
#define TRAINER_TEAM_ROCKET_GRUNT_15                 (TRAINER_FRLG_OFFSET +  265)
#undef  TRAINER_TEAM_ROCKET_GRUNT_16
#define TRAINER_TEAM_ROCKET_GRUNT_16                 (TRAINER_FRLG_OFFSET +  266)
#undef  TRAINER_TEAM_ROCKET_GRUNT_17
#define TRAINER_TEAM_ROCKET_GRUNT_17                 (TRAINER_FRLG_OFFSET +  267)
#undef  TRAINER_TEAM_ROCKET_GRUNT_18
#define TRAINER_TEAM_ROCKET_GRUNT_18                 (TRAINER_FRLG_OFFSET +  268)
#undef  TRAINER_TEAM_ROCKET_GRUNT_19
#define TRAINER_TEAM_ROCKET_GRUNT_19                 (TRAINER_FRLG_OFFSET +  269)
#undef  TRAINER_TEAM_ROCKET_GRUNT_20
#define TRAINER_TEAM_ROCKET_GRUNT_20                 (TRAINER_FRLG_OFFSET +  270)
#undef  TRAINER_TEAM_ROCKET_GRUNT_21
#define TRAINER_TEAM_ROCKET_GRUNT_21                 (TRAINER_FRLG_OFFSET +  271)
#undef  TRAINER_TEAM_ROCKET_GRUNT_22
#define TRAINER_TEAM_ROCKET_GRUNT_22                 (TRAINER_FRLG_OFFSET +  272)
#undef  TRAINER_TEAM_ROCKET_GRUNT_23
#define TRAINER_TEAM_ROCKET_GRUNT_23                 (TRAINER_FRLG_OFFSET +  273)
#undef  TRAINER_TEAM_ROCKET_GRUNT_24
#define TRAINER_TEAM_ROCKET_GRUNT_24                 (TRAINER_FRLG_OFFSET +  274)
#undef  TRAINER_TEAM_ROCKET_GRUNT_25
#define TRAINER_TEAM_ROCKET_GRUNT_25                 (TRAINER_FRLG_OFFSET +  275)
#undef  TRAINER_TEAM_ROCKET_GRUNT_26
#define TRAINER_TEAM_ROCKET_GRUNT_26                 (TRAINER_FRLG_OFFSET +  276)
#undef  TRAINER_TEAM_ROCKET_GRUNT_27
#define TRAINER_TEAM_ROCKET_GRUNT_27                 (TRAINER_FRLG_OFFSET +  277)
#undef  TRAINER_TEAM_ROCKET_GRUNT_28
#define TRAINER_TEAM_ROCKET_GRUNT_28                 (TRAINER_FRLG_OFFSET +  278)
#undef  TRAINER_TEAM_ROCKET_GRUNT_29
#define TRAINER_TEAM_ROCKET_GRUNT_29                 (TRAINER_FRLG_OFFSET +  279)
#undef  TRAINER_TEAM_ROCKET_GRUNT_30
#define TRAINER_TEAM_ROCKET_GRUNT_30                 (TRAINER_FRLG_OFFSET +  280)
#undef  TRAINER_TEAM_ROCKET_GRUNT_31
#define TRAINER_TEAM_ROCKET_GRUNT_31                 (TRAINER_FRLG_OFFSET +  281)
#undef  TRAINER_TEAM_ROCKET_GRUNT_32
#define TRAINER_TEAM_ROCKET_GRUNT_32                 (TRAINER_FRLG_OFFSET +  282)
#undef  TRAINER_TEAM_ROCKET_GRUNT_33
#define TRAINER_TEAM_ROCKET_GRUNT_33                 (TRAINER_FRLG_OFFSET +  283)
#undef  TRAINER_TEAM_ROCKET_GRUNT_34
#define TRAINER_TEAM_ROCKET_GRUNT_34                 (TRAINER_FRLG_OFFSET +  284)
#undef  TRAINER_TEAM_ROCKET_GRUNT_35
#define TRAINER_TEAM_ROCKET_GRUNT_35                 (TRAINER_FRLG_OFFSET +  285)
#undef  TRAINER_TEAM_ROCKET_GRUNT_36
#define TRAINER_TEAM_ROCKET_GRUNT_36                 (TRAINER_FRLG_OFFSET +  286)
#undef  TRAINER_TEAM_ROCKET_GRUNT_37
#define TRAINER_TEAM_ROCKET_GRUNT_37                 (TRAINER_FRLG_OFFSET +  287)
#undef  TRAINER_TEAM_ROCKET_GRUNT_38
#define TRAINER_TEAM_ROCKET_GRUNT_38                 (TRAINER_FRLG_OFFSET +  288)
#undef  TRAINER_TEAM_ROCKET_GRUNT_39
#define TRAINER_TEAM_ROCKET_GRUNT_39                 (TRAINER_FRLG_OFFSET +  289)
#undef  TRAINER_TEAM_ROCKET_GRUNT_40
#define TRAINER_TEAM_ROCKET_GRUNT_40                 (TRAINER_FRLG_OFFSET +  290)
#undef  TRAINER_TEAM_ROCKET_GRUNT_41
#define TRAINER_TEAM_ROCKET_GRUNT_41                 (TRAINER_FRLG_OFFSET +  291)
#undef  TRAINER_COOLTRAINER_SAMUEL
#define TRAINER_COOLTRAINER_SAMUEL                   (TRAINER_FRLG_OFFSET +  292)
#undef  TRAINER_COOLTRAINER_GEORGE
#define TRAINER_COOLTRAINER_GEORGE                   (TRAINER_FRLG_OFFSET +  293)
#undef  TRAINER_COOLTRAINER_COLBY
#define TRAINER_COOLTRAINER_COLBY                    (TRAINER_FRLG_OFFSET +  294)
#undef  TRAINER_COOLTRAINER_PAUL
#define TRAINER_COOLTRAINER_PAUL                     (TRAINER_FRLG_OFFSET +  295)
#undef  TRAINER_COOLTRAINER_ROLANDO
#define TRAINER_COOLTRAINER_ROLANDO                  (TRAINER_FRLG_OFFSET +  296)
#undef  TRAINER_COOLTRAINER_GILBERT
#define TRAINER_COOLTRAINER_GILBERT                  (TRAINER_FRLG_OFFSET +  297)
#undef  TRAINER_COOLTRAINER_OWEN
#define TRAINER_COOLTRAINER_OWEN                     (TRAINER_FRLG_OFFSET +  298)
#undef  TRAINER_COOLTRAINER_BERKE
#define TRAINER_COOLTRAINER_BERKE                    (TRAINER_FRLG_OFFSET +  299)
#undef  TRAINER_COOLTRAINER_YUJI
#define TRAINER_COOLTRAINER_YUJI                     (TRAINER_FRLG_OFFSET +  300)
#undef  TRAINER_COOLTRAINER_WARREN
#define TRAINER_COOLTRAINER_WARREN                   (TRAINER_FRLG_OFFSET +  301)
#undef  TRAINER_COOLTRAINER_MARY
#define TRAINER_COOLTRAINER_MARY                     (TRAINER_FRLG_OFFSET +  302)
#undef  TRAINER_COOLTRAINER_CAROLINE
#define TRAINER_COOLTRAINER_CAROLINE                 (TRAINER_FRLG_OFFSET +  303)
#undef  TRAINER_COOLTRAINER_ALEXA
#define TRAINER_COOLTRAINER_ALEXA                    (TRAINER_FRLG_OFFSET +  304)
#undef  TRAINER_COOLTRAINER_SHANNON
#define TRAINER_COOLTRAINER_SHANNON                  (TRAINER_FRLG_OFFSET +  305)
#undef  TRAINER_COOLTRAINER_NAOMI
#define TRAINER_COOLTRAINER_NAOMI                    (TRAINER_FRLG_OFFSET +  306)
#undef  TRAINER_COOLTRAINER_BROOKE
#define TRAINER_COOLTRAINER_BROOKE                   (TRAINER_FRLG_OFFSET +  307)
#undef  TRAINER_COOLTRAINER_AUSTINA
#define TRAINER_COOLTRAINER_AUSTINA                  (TRAINER_FRLG_OFFSET +  308)
#undef  TRAINER_COOLTRAINER_JULIE
#define TRAINER_COOLTRAINER_JULIE                    (TRAINER_FRLG_OFFSET +  309)
#undef  TRAINER_ELITE_FOUR_LORELEI
#define TRAINER_ELITE_FOUR_LORELEI                   (TRAINER_FRLG_OFFSET +  310)
#undef  TRAINER_ELITE_FOUR_BRUNO
#define TRAINER_ELITE_FOUR_BRUNO                     (TRAINER_FRLG_OFFSET +  311)
#undef  TRAINER_ELITE_FOUR_AGATHA
#define TRAINER_ELITE_FOUR_AGATHA                    (TRAINER_FRLG_OFFSET +  312)
#undef  TRAINER_ELITE_FOUR_LANCE
#define TRAINER_ELITE_FOUR_LANCE                     (TRAINER_FRLG_OFFSET +  313)
#undef  TRAINER_LEADER_BROCK
#define TRAINER_LEADER_BROCK                         (TRAINER_FRLG_OFFSET +  314)
#undef  TRAINER_LEADER_MISTY
#define TRAINER_LEADER_MISTY                         (TRAINER_FRLG_OFFSET +  315)
#undef  TRAINER_LEADER_LT_SURGE
#define TRAINER_LEADER_LT_SURGE                      (TRAINER_FRLG_OFFSET +  316)
#undef  TRAINER_LEADER_ERIKA
#define TRAINER_LEADER_ERIKA                         (TRAINER_FRLG_OFFSET +  317)
#undef  TRAINER_LEADER_KOGA
#define TRAINER_LEADER_KOGA                          (TRAINER_FRLG_OFFSET +  318)
#undef  TRAINER_LEADER_BLAINE
#define TRAINER_LEADER_BLAINE                        (TRAINER_FRLG_OFFSET +  319)
#undef  TRAINER_LEADER_SABRINA
#define TRAINER_LEADER_SABRINA                       (TRAINER_FRLG_OFFSET +  320)
#undef  TRAINER_GENTLEMAN_THOMAS
#define TRAINER_GENTLEMAN_THOMAS                     (TRAINER_FRLG_OFFSET +  321)
#undef  TRAINER_GENTLEMAN_ARTHUR
#define TRAINER_GENTLEMAN_ARTHUR                     (TRAINER_FRLG_OFFSET +  322)
#undef  TRAINER_GENTLEMAN_TUCKER
#define TRAINER_GENTLEMAN_TUCKER                     (TRAINER_FRLG_OFFSET +  323)
#undef  TRAINER_GENTLEMAN_NORTON
#define TRAINER_GENTLEMAN_NORTON                     (TRAINER_FRLG_OFFSET +  324)
#undef  TRAINER_GENTLEMAN_WALTER
#define TRAINER_GENTLEMAN_WALTER                     (TRAINER_FRLG_OFFSET +  325)
#undef  TRAINER_RIVAL_SS_ANNE_SQUIRTLE
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE               (TRAINER_FRLG_OFFSET +  326)
#undef  TRAINER_RIVAL_SS_ANNE_BULBASAUR
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR              (TRAINER_FRLG_OFFSET +  327)
#undef  TRAINER_RIVAL_SS_ANNE_CHARMANDER
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER             (TRAINER_FRLG_OFFSET +  328)
#undef  TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE         (TRAINER_FRLG_OFFSET +  329)
#undef  TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR        (TRAINER_FRLG_OFFSET +  330)
#undef  TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER       (TRAINER_FRLG_OFFSET +  331)
#undef  TRAINER_RIVAL_SILPH_SQUIRTLE
#define TRAINER_RIVAL_SILPH_SQUIRTLE                 (TRAINER_FRLG_OFFSET +  332)
#undef  TRAINER_RIVAL_SILPH_BULBASAUR
#define TRAINER_RIVAL_SILPH_BULBASAUR                (TRAINER_FRLG_OFFSET +  333)
#undef  TRAINER_RIVAL_SILPH_CHARMANDER
#define TRAINER_RIVAL_SILPH_CHARMANDER               (TRAINER_FRLG_OFFSET +  334)
#undef  TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE          (TRAINER_FRLG_OFFSET +  335)
#undef  TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR         (TRAINER_FRLG_OFFSET +  336)
#undef  TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER        (TRAINER_FRLG_OFFSET +  337)
#undef  TRAINER_CHAMPION_FIRST_SQUIRTLE
#define TRAINER_CHAMPION_FIRST_SQUIRTLE              (TRAINER_FRLG_OFFSET +  338)
#undef  TRAINER_CHAMPION_FIRST_BULBASAUR
#define TRAINER_CHAMPION_FIRST_BULBASAUR             (TRAINER_FRLG_OFFSET +  339)
#undef  TRAINER_CHAMPION_FIRST_CHARMANDER
#define TRAINER_CHAMPION_FIRST_CHARMANDER            (TRAINER_FRLG_OFFSET +  340)
#undef  TRAINER_CHANNELER_PATRICIA
#define TRAINER_CHANNELER_PATRICIA                   (TRAINER_FRLG_OFFSET +  341)
#undef  TRAINER_CHANNELER_CARLY
#define TRAINER_CHANNELER_CARLY                      (TRAINER_FRLG_OFFSET +  342)
#undef  TRAINER_CHANNELER_HOPE
#define TRAINER_CHANNELER_HOPE                       (TRAINER_FRLG_OFFSET +  343)
#undef  TRAINER_CHANNELER_PAULA
#define TRAINER_CHANNELER_PAULA                      (TRAINER_FRLG_OFFSET +  344)
#undef  TRAINER_CHANNELER_LAUREL
#define TRAINER_CHANNELER_LAUREL                     (TRAINER_FRLG_OFFSET +  345)
#undef  TRAINER_CHANNELER_JODY
#define TRAINER_CHANNELER_JODY                       (TRAINER_FRLG_OFFSET +  346)
#undef  TRAINER_CHANNELER_TAMMY
#define TRAINER_CHANNELER_TAMMY                      (TRAINER_FRLG_OFFSET +  347)
#undef  TRAINER_CHANNELER_RUTH
#define TRAINER_CHANNELER_RUTH                       (TRAINER_FRLG_OFFSET +  348)
#undef  TRAINER_CHANNELER_KARINA
#define TRAINER_CHANNELER_KARINA                     (TRAINER_FRLG_OFFSET +  349)
#undef  TRAINER_CHANNELER_JANAE
#define TRAINER_CHANNELER_JANAE                      (TRAINER_FRLG_OFFSET +  350)
#undef  TRAINER_CHANNELER_ANGELICA
#define TRAINER_CHANNELER_ANGELICA                   (TRAINER_FRLG_OFFSET +  351)
#undef  TRAINER_CHANNELER_EMILIA
#define TRAINER_CHANNELER_EMILIA                     (TRAINER_FRLG_OFFSET +  352)
#undef  TRAINER_CHANNELER_JENNIFER
#define TRAINER_CHANNELER_JENNIFER                   (TRAINER_FRLG_OFFSET +  353)
#undef  TRAINER_CHANNELER_AMANDA
#define TRAINER_CHANNELER_AMANDA                     (TRAINER_FRLG_OFFSET +  354)
#undef  TRAINER_CHANNELER_STACY
#define TRAINER_CHANNELER_STACY                      (TRAINER_FRLG_OFFSET +  355)
#undef  TRAINER_CHANNELER_TASHA
#define TRAINER_CHANNELER_TASHA                      (TRAINER_FRLG_OFFSET +  356)
#undef  TRAINER_HIKER_JEREMY
#define TRAINER_HIKER_JEREMY                         (TRAINER_FRLG_OFFSET +  357)
#undef  TRAINER_PICNICKER_ALMA
#define TRAINER_PICNICKER_ALMA                       (TRAINER_FRLG_OFFSET +  358)
#undef  TRAINER_PICNICKER_SUSIE
#define TRAINER_PICNICKER_SUSIE                      (TRAINER_FRLG_OFFSET +  359)
#undef  TRAINER_PICNICKER_VALERIE
#define TRAINER_PICNICKER_VALERIE                    (TRAINER_FRLG_OFFSET +  360)
#undef  TRAINER_PICNICKER_GWEN
#define TRAINER_PICNICKER_GWEN                       (TRAINER_FRLG_OFFSET +  361)
#undef  TRAINER_BIKER_VIRGIL
#define TRAINER_BIKER_VIRGIL                         (TRAINER_FRLG_OFFSET +  362)
#undef  TRAINER_CAMPER_FLINT
#define TRAINER_CAMPER_FLINT                         (TRAINER_FRLG_OFFSET +  363)
#undef  TRAINER_PICNICKER_MISSY
#define TRAINER_PICNICKER_MISSY                      (TRAINER_FRLG_OFFSET +  364)
#undef  TRAINER_PICNICKER_IRENE
#define TRAINER_PICNICKER_IRENE                      (TRAINER_FRLG_OFFSET +  365)
#undef  TRAINER_PICNICKER_DANA
#define TRAINER_PICNICKER_DANA                       (TRAINER_FRLG_OFFSET +  366)
#undef  TRAINER_PICNICKER_ARIANA
#define TRAINER_PICNICKER_ARIANA                     (TRAINER_FRLG_OFFSET +  367)
#undef  TRAINER_PICNICKER_LEAH
#define TRAINER_PICNICKER_LEAH                       (TRAINER_FRLG_OFFSET +  368)
#undef  TRAINER_CAMPER_JUSTIN
#define TRAINER_CAMPER_JUSTIN                        (TRAINER_FRLG_OFFSET +  369)
#undef  TRAINER_PICNICKER_YAZMIN
#define TRAINER_PICNICKER_YAZMIN                     (TRAINER_FRLG_OFFSET +  370)
#undef  TRAINER_PICNICKER_KINDRA
#define TRAINER_PICNICKER_KINDRA                     (TRAINER_FRLG_OFFSET +  371)
#undef  TRAINER_PICNICKER_BECKY
#define TRAINER_PICNICKER_BECKY                      (TRAINER_FRLG_OFFSET +  372)
#undef  TRAINER_PICNICKER_CELIA
#define TRAINER_PICNICKER_CELIA                      (TRAINER_FRLG_OFFSET +  373)
#undef  TRAINER_GENTLEMAN_BROOKS
#define TRAINER_GENTLEMAN_BROOKS                     (TRAINER_FRLG_OFFSET +  374)
#undef  TRAINER_GENTLEMAN_LAMAR
#define TRAINER_GENTLEMAN_LAMAR                      (TRAINER_FRLG_OFFSET +  375)
#undef  TRAINER_TWINS_ELI_ANNE
#define TRAINER_TWINS_ELI_ANNE                       (TRAINER_FRLG_OFFSET +  376)
#undef  TRAINER_COOL_COUPLE_RAY_TYRA
#define TRAINER_COOL_COUPLE_RAY_TYRA                 (TRAINER_FRLG_OFFSET +  377)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES
#define TRAINER_YOUNG_COUPLE_GIA_JES                 (TRAINER_FRLG_OFFSET +  378)
#undef  TRAINER_TWINS_KIRI_JAN
#define TRAINER_TWINS_KIRI_JAN                       (TRAINER_FRLG_OFFSET +  379)
#undef  TRAINER_CRUSH_KIN_RON_MYA
#define TRAINER_CRUSH_KIN_RON_MYA                    (TRAINER_FRLG_OFFSET +  380)
#undef  TRAINER_YOUNG_COUPLE_LEA_JED
#define TRAINER_YOUNG_COUPLE_LEA_JED                 (TRAINER_FRLG_OFFSET +  381)
#undef  TRAINER_SIS_AND_BRO_LIA_LUC
#define TRAINER_SIS_AND_BRO_LIA_LUC                  (TRAINER_FRLG_OFFSET +  382)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN
#define TRAINER_SIS_AND_BRO_LIL_IAN                  (TRAINER_FRLG_OFFSET +  383)
#undef  TRAINER_YOUNGSTER_BEN_3
#define TRAINER_YOUNGSTER_BEN_3                      (TRAINER_FRLG_OFFSET +  384)
#undef  TRAINER_YOUNGSTER_BEN_4
#define TRAINER_YOUNGSTER_BEN_4                      (TRAINER_FRLG_OFFSET +  385)
#undef  TRAINER_YOUNGSTER_CHAD_2
#define TRAINER_YOUNGSTER_CHAD_2                     (TRAINER_FRLG_OFFSET +  386)
#undef  TRAINER_LASS_RELI_2
#define TRAINER_LASS_RELI_2                          (TRAINER_FRLG_OFFSET +  387)
#undef  TRAINER_LASS_RELI_3
#define TRAINER_LASS_RELI_3                          (TRAINER_FRLG_OFFSET +  388)
#undef  TRAINER_YOUNGSTER_TIMMY_2
#define TRAINER_YOUNGSTER_TIMMY_2                    (TRAINER_FRLG_OFFSET +  389)
#undef  TRAINER_YOUNGSTER_TIMMY_3
#define TRAINER_YOUNGSTER_TIMMY_3                    (TRAINER_FRLG_OFFSET +  390)
#undef  TRAINER_YOUNGSTER_TIMMY_4
#define TRAINER_YOUNGSTER_TIMMY_4                    (TRAINER_FRLG_OFFSET +  391)
#undef  TRAINER_YOUNGSTER_CHAD_3
#define TRAINER_YOUNGSTER_CHAD_3                     (TRAINER_FRLG_OFFSET +  392)
#undef  TRAINER_LASS_JANICE_2
#define TRAINER_LASS_JANICE_2                        (TRAINER_FRLG_OFFSET +  393)
#undef  TRAINER_LASS_JANICE_3
#define TRAINER_LASS_JANICE_3                        (TRAINER_FRLG_OFFSET +  394)
#undef  TRAINER_YOUNGSTER_CHAD_4
#define TRAINER_YOUNGSTER_CHAD_4                     (TRAINER_FRLG_OFFSET +  395)
#undef  TRAINER_HIKER_FRANKLIN_2
#define TRAINER_HIKER_FRANKLIN_2                     (TRAINER_FRLG_OFFSET +  396)
#undef  TRAINER_PKMN_PROF_PROF_OAK
#define TRAINER_PKMN_PROF_PROF_OAK                   (TRAINER_FRLG_OFFSET +  397)
#undef  TRAINER_TEAM_ROCKET_GRUNT_42
#define TRAINER_TEAM_ROCKET_GRUNT_42                 (TRAINER_FRLG_OFFSET +  398)
#undef  TRAINER_PSYCHIC_JACLYN
#define TRAINER_PSYCHIC_JACLYN                       (TRAINER_FRLG_OFFSET +  399)
#undef  TRAINER_CRUSH_GIRL_SHARON
#define TRAINER_CRUSH_GIRL_SHARON                    (TRAINER_FRLG_OFFSET +  400)
#undef  TRAINER_TUBER_AMIRA
#define TRAINER_TUBER_AMIRA                          (TRAINER_FRLG_OFFSET +  401)
#undef  TRAINER_PKMN_BREEDER_ALIZE
#define TRAINER_PKMN_BREEDER_ALIZE                   (TRAINER_FRLG_OFFSET +  402)
#undef  TRAINER_PKMN_RANGER_NICOLAS
#define TRAINER_PKMN_RANGER_NICOLAS                  (TRAINER_FRLG_OFFSET +  403)
#undef  TRAINER_PKMN_RANGER_MADELINE
#define TRAINER_PKMN_RANGER_MADELINE                 (TRAINER_FRLG_OFFSET +  404)
#undef  TRAINER_AROMA_LADY_NIKKI
#define TRAINER_AROMA_LADY_NIKKI                     (TRAINER_FRLG_OFFSET +  405)
#undef  TRAINER_RUIN_MANIAC_STANLY
#define TRAINER_RUIN_MANIAC_STANLY                   (TRAINER_FRLG_OFFSET +  406)
#undef  TRAINER_LADY_JACKI
#define TRAINER_LADY_JACKI                           (TRAINER_FRLG_OFFSET +  407)
#undef  TRAINER_PAINTER_DAISY
#define TRAINER_PAINTER_DAISY                        (TRAINER_FRLG_OFFSET +  408)
#undef  TRAINER_BIKER_GOON
#define TRAINER_BIKER_GOON                           (TRAINER_FRLG_OFFSET +  409)
#undef  TRAINER_BIKER_GOON_2
#define TRAINER_BIKER_GOON_2                         (TRAINER_FRLG_OFFSET +  410)
#undef  TRAINER_BIKER_GOON_3
#define TRAINER_BIKER_GOON_3                         (TRAINER_FRLG_OFFSET +  411)
#undef  TRAINER_BUG_CATCHER_ANTHONY
#define TRAINER_BUG_CATCHER_ANTHONY                  (TRAINER_FRLG_OFFSET +  412)
#undef  TRAINER_BUG_CATCHER_CHARLIE
#define TRAINER_BUG_CATCHER_CHARLIE                  (TRAINER_FRLG_OFFSET +  413)
#undef  TRAINER_TWINS_ELI_ANNE_2
#define TRAINER_TWINS_ELI_ANNE_2                     (TRAINER_FRLG_OFFSET +  414)
#undef  TRAINER_YOUNGSTER_JOHNSON
#define TRAINER_YOUNGSTER_JOHNSON                    (TRAINER_FRLG_OFFSET +  415)
#undef  TRAINER_BIKER_RICARDO
#define TRAINER_BIKER_RICARDO                        (TRAINER_FRLG_OFFSET +  416)
#undef  TRAINER_BIKER_JAREN
#define TRAINER_BIKER_JAREN                          (TRAINER_FRLG_OFFSET +  417)
#undef  TRAINER_TEAM_ROCKET_GRUNT_43
#define TRAINER_TEAM_ROCKET_GRUNT_43                 (TRAINER_FRLG_OFFSET +  418)
#undef  TRAINER_TEAM_ROCKET_GRUNT_44
#define TRAINER_TEAM_ROCKET_GRUNT_44                 (TRAINER_FRLG_OFFSET +  419)
#undef  TRAINER_TEAM_ROCKET_GRUNT_45
#define TRAINER_TEAM_ROCKET_GRUNT_45                 (TRAINER_FRLG_OFFSET +  420)
#undef  TRAINER_TEAM_ROCKET_GRUNT_46
#define TRAINER_TEAM_ROCKET_GRUNT_46                 (TRAINER_FRLG_OFFSET +  421)
#undef  TRAINER_TEAM_ROCKET_GRUNT_47
#define TRAINER_TEAM_ROCKET_GRUNT_47                 (TRAINER_FRLG_OFFSET +  422)
#undef  TRAINER_TEAM_ROCKET_GRUNT_48
#define TRAINER_TEAM_ROCKET_GRUNT_48                 (TRAINER_FRLG_OFFSET +  423)
#undef  TRAINER_TEAM_ROCKET_ADMIN
#define TRAINER_TEAM_ROCKET_ADMIN                    (TRAINER_FRLG_OFFSET +  424)
#undef  TRAINER_TEAM_ROCKET_ADMIN_2
#define TRAINER_TEAM_ROCKET_ADMIN_2                  (TRAINER_FRLG_OFFSET +  425)
#undef  TRAINER_SCIENTIST_GIDEON
#define TRAINER_SCIENTIST_GIDEON                     (TRAINER_FRLG_OFFSET +  426)
#undef  TRAINER_SWIMMER_FEMALE_AMARA
#define TRAINER_SWIMMER_FEMALE_AMARA                 (TRAINER_FRLG_OFFSET +  427)
#undef  TRAINER_SWIMMER_FEMALE_MARIA
#define TRAINER_SWIMMER_FEMALE_MARIA                 (TRAINER_FRLG_OFFSET +  428)
#undef  TRAINER_SWIMMER_FEMALE_ABIGAIL
#define TRAINER_SWIMMER_FEMALE_ABIGAIL               (TRAINER_FRLG_OFFSET +  429)
#undef  TRAINER_SWIMMER_MALE_FINN
#define TRAINER_SWIMMER_MALE_FINN                    (TRAINER_FRLG_OFFSET +  430)
#undef  TRAINER_SWIMMER_MALE_GARRETT
#define TRAINER_SWIMMER_MALE_GARRETT                 (TRAINER_FRLG_OFFSET +  431)
#undef  TRAINER_FISHERMAN_TOMMY
#define TRAINER_FISHERMAN_TOMMY                      (TRAINER_FRLG_OFFSET +  432)
#undef  TRAINER_CRUSH_GIRL_TANYA
#define TRAINER_CRUSH_GIRL_TANYA                     (TRAINER_FRLG_OFFSET +  433)
#undef  TRAINER_BLACK_BELT_SHEA
#define TRAINER_BLACK_BELT_SHEA                      (TRAINER_FRLG_OFFSET +  434)
#undef  TRAINER_BLACK_BELT_HUGH
#define TRAINER_BLACK_BELT_HUGH                      (TRAINER_FRLG_OFFSET +  435)
#undef  TRAINER_CAMPER_BRYCE
#define TRAINER_CAMPER_BRYCE                         (TRAINER_FRLG_OFFSET +  436)
#undef  TRAINER_PICNICKER_CLAIRE
#define TRAINER_PICNICKER_CLAIRE                     (TRAINER_FRLG_OFFSET +  437)
#undef  TRAINER_CRUSH_KIN_MIK_KIA
#define TRAINER_CRUSH_KIN_MIK_KIA                    (TRAINER_FRLG_OFFSET +  438)
#undef  TRAINER_AROMA_LADY_VIOLET
#define TRAINER_AROMA_LADY_VIOLET                    (TRAINER_FRLG_OFFSET +  439)
#undef  TRAINER_TUBER_ALEXIS
#define TRAINER_TUBER_ALEXIS                         (TRAINER_FRLG_OFFSET +  440)
#undef  TRAINER_TWINS_JOY_MEG
#define TRAINER_TWINS_JOY_MEG                        (TRAINER_FRLG_OFFSET +  441)
#undef  TRAINER_SWIMMER_FEMALE_TISHA
#define TRAINER_SWIMMER_FEMALE_TISHA                 (TRAINER_FRLG_OFFSET +  442)
#undef  TRAINER_PAINTER_CELINA
#define TRAINER_PAINTER_CELINA                       (TRAINER_FRLG_OFFSET +  443)
#undef  TRAINER_PAINTER_RAYNA
#define TRAINER_PAINTER_RAYNA                        (TRAINER_FRLG_OFFSET +  444)
#undef  TRAINER_LADY_GILLIAN
#define TRAINER_LADY_GILLIAN                         (TRAINER_FRLG_OFFSET +  445)
#undef  TRAINER_YOUNGSTER_DESTIN
#define TRAINER_YOUNGSTER_DESTIN                     (TRAINER_FRLG_OFFSET +  446)
#undef  TRAINER_SWIMMER_MALE_TOBY
#define TRAINER_SWIMMER_MALE_TOBY                    (TRAINER_FRLG_OFFSET +  447)
#undef  TRAINER_TEAM_ROCKET_GRUNT_49
#define TRAINER_TEAM_ROCKET_GRUNT_49                 (TRAINER_FRLG_OFFSET +  448)
#undef  TRAINER_TEAM_ROCKET_GRUNT_50
#define TRAINER_TEAM_ROCKET_GRUNT_50                 (TRAINER_FRLG_OFFSET +  449)
#undef  TRAINER_TEAM_ROCKET_GRUNT_51
#define TRAINER_TEAM_ROCKET_GRUNT_51                 (TRAINER_FRLG_OFFSET +  450)
#undef  TRAINER_BIRD_KEEPER_MILO
#define TRAINER_BIRD_KEEPER_MILO                     (TRAINER_FRLG_OFFSET +  451)
#undef  TRAINER_BIRD_KEEPER_CHAZ
#define TRAINER_BIRD_KEEPER_CHAZ                     (TRAINER_FRLG_OFFSET +  452)
#undef  TRAINER_BIRD_KEEPER_HAROLD
#define TRAINER_BIRD_KEEPER_HAROLD                   (TRAINER_FRLG_OFFSET +  453)
#undef  TRAINER_FISHERMAN_TYLOR
#define TRAINER_FISHERMAN_TYLOR                      (TRAINER_FRLG_OFFSET +  454)
#undef  TRAINER_SWIMMER_MALE_MYMO
#define TRAINER_SWIMMER_MALE_MYMO                    (TRAINER_FRLG_OFFSET +  455)
#undef  TRAINER_SWIMMER_FEMALE_NICOLE
#define TRAINER_SWIMMER_FEMALE_NICOLE                (TRAINER_FRLG_OFFSET +  456)
#undef  TRAINER_SIS_AND_BRO_AVA_GEB
#define TRAINER_SIS_AND_BRO_AVA_GEB                  (TRAINER_FRLG_OFFSET +  457)
#undef  TRAINER_AROMA_LADY_ROSE
#define TRAINER_AROMA_LADY_ROSE                      (TRAINER_FRLG_OFFSET +  458)
#undef  TRAINER_SWIMMER_MALE_SAMIR
#define TRAINER_SWIMMER_MALE_SAMIR                   (TRAINER_FRLG_OFFSET +  459)
#undef  TRAINER_SWIMMER_FEMALE_DENISE
#define TRAINER_SWIMMER_FEMALE_DENISE                (TRAINER_FRLG_OFFSET +  460)
#undef  TRAINER_TWINS_MIU_MIA
#define TRAINER_TWINS_MIU_MIA                        (TRAINER_FRLG_OFFSET +  461)
#undef  TRAINER_HIKER_EARL
#define TRAINER_HIKER_EARL                           (TRAINER_FRLG_OFFSET +  462)
#undef  TRAINER_RUIN_MANIAC_FOSTER
#define TRAINER_RUIN_MANIAC_FOSTER                   (TRAINER_FRLG_OFFSET +  463)
#undef  TRAINER_RUIN_MANIAC_LARRY
#define TRAINER_RUIN_MANIAC_LARRY                    (TRAINER_FRLG_OFFSET +  464)
#undef  TRAINER_HIKER_DARYL
#define TRAINER_HIKER_DARYL                          (TRAINER_FRLG_OFFSET +  465)
#undef  TRAINER_POKEMANIAC_HECTOR
#define TRAINER_POKEMANIAC_HECTOR                    (TRAINER_FRLG_OFFSET +  466)
#undef  TRAINER_PSYCHIC_DARIO
#define TRAINER_PSYCHIC_DARIO                        (TRAINER_FRLG_OFFSET +  467)
#undef  TRAINER_PSYCHIC_RODETTE
#define TRAINER_PSYCHIC_RODETTE                      (TRAINER_FRLG_OFFSET +  468)
#undef  TRAINER_AROMA_LADY_MIAH
#define TRAINER_AROMA_LADY_MIAH                      (TRAINER_FRLG_OFFSET +  469)
#undef  TRAINER_YOUNG_COUPLE_EVE_JON
#define TRAINER_YOUNG_COUPLE_EVE_JON                 (TRAINER_FRLG_OFFSET +  470)
#undef  TRAINER_JUGGLER_MASON
#define TRAINER_JUGGLER_MASON                        (TRAINER_FRLG_OFFSET +  471)
#undef  TRAINER_CRUSH_GIRL_CYNDY
#define TRAINER_CRUSH_GIRL_CYNDY                     (TRAINER_FRLG_OFFSET +  472)
#undef  TRAINER_CRUSH_GIRL_JOCELYN
#define TRAINER_CRUSH_GIRL_JOCELYN                   (TRAINER_FRLG_OFFSET +  473)
#undef  TRAINER_TAMER_EVAN
#define TRAINER_TAMER_EVAN                           (TRAINER_FRLG_OFFSET +  474)
#undef  TRAINER_POKEMANIAC_MARK_2
#define TRAINER_POKEMANIAC_MARK_2                    (TRAINER_FRLG_OFFSET +  475)
#undef  TRAINER_PKMN_RANGER_LOGAN
#define TRAINER_PKMN_RANGER_LOGAN                    (TRAINER_FRLG_OFFSET +  476)
#undef  TRAINER_PKMN_RANGER_JACKSON
#define TRAINER_PKMN_RANGER_JACKSON                  (TRAINER_FRLG_OFFSET +  477)
#undef  TRAINER_PKMN_RANGER_BETH
#define TRAINER_PKMN_RANGER_BETH                     (TRAINER_FRLG_OFFSET +  478)
#undef  TRAINER_PKMN_RANGER_KATELYN
#define TRAINER_PKMN_RANGER_KATELYN                  (TRAINER_FRLG_OFFSET +  479)
#undef  TRAINER_COOLTRAINER_LEROY
#define TRAINER_COOLTRAINER_LEROY                    (TRAINER_FRLG_OFFSET +  480)
#undef  TRAINER_COOLTRAINER_MICHELLE
#define TRAINER_COOLTRAINER_MICHELLE                 (TRAINER_FRLG_OFFSET +  481)
#undef  TRAINER_COOL_COUPLE_LEX_NYA
#define TRAINER_COOL_COUPLE_LEX_NYA                  (TRAINER_FRLG_OFFSET +  482)
#undef  TRAINER_RUIN_MANIAC_BRANDON
#define TRAINER_RUIN_MANIAC_BRANDON                  (TRAINER_FRLG_OFFSET +  483)
#undef  TRAINER_RUIN_MANIAC_BENJAMIN
#define TRAINER_RUIN_MANIAC_BENJAMIN                 (TRAINER_FRLG_OFFSET +  484)
#undef  TRAINER_PAINTER_EDNA
#define TRAINER_PAINTER_EDNA                         (TRAINER_FRLG_OFFSET +  485)
#undef  TRAINER_GENTLEMAN_CLIFFORD
#define TRAINER_GENTLEMAN_CLIFFORD                   (TRAINER_FRLG_OFFSET +  486)
#undef  TRAINER_LADY_SELPHY
#define TRAINER_LADY_SELPHY                          (TRAINER_FRLG_OFFSET +  487)
#undef  TRAINER_RUIN_MANIAC_LAWSON
#define TRAINER_RUIN_MANIAC_LAWSON                   (TRAINER_FRLG_OFFSET +  488)
#undef  TRAINER_PSYCHIC_LAURA
#define TRAINER_PSYCHIC_LAURA                        (TRAINER_FRLG_OFFSET +  489)
#undef  TRAINER_PKMN_BREEDER_BETHANY
#define TRAINER_PKMN_BREEDER_BETHANY                 (TRAINER_FRLG_OFFSET +  490)
#undef  TRAINER_PKMN_BREEDER_ALLISON
#define TRAINER_PKMN_BREEDER_ALLISON                 (TRAINER_FRLG_OFFSET +  491)
#undef  TRAINER_BUG_CATCHER_GARRET
#define TRAINER_BUG_CATCHER_GARRET                   (TRAINER_FRLG_OFFSET +  492)
#undef  TRAINER_BUG_CATCHER_JONAH
#define TRAINER_BUG_CATCHER_JONAH                    (TRAINER_FRLG_OFFSET +  493)
#undef  TRAINER_BUG_CATCHER_VANCE
#define TRAINER_BUG_CATCHER_VANCE                    (TRAINER_FRLG_OFFSET +  494)
#undef  TRAINER_YOUNGSTER_NASH
#define TRAINER_YOUNGSTER_NASH                       (TRAINER_FRLG_OFFSET +  495)
#undef  TRAINER_YOUNGSTER_CORDELL
#define TRAINER_YOUNGSTER_CORDELL                    (TRAINER_FRLG_OFFSET +  496)
#undef  TRAINER_LASS_DALIA
#define TRAINER_LASS_DALIA                           (TRAINER_FRLG_OFFSET +  497)
#undef  TRAINER_LASS_JOANA
#define TRAINER_LASS_JOANA                           (TRAINER_FRLG_OFFSET +  498)
#undef  TRAINER_CAMPER_RILEY
#define TRAINER_CAMPER_RILEY                         (TRAINER_FRLG_OFFSET +  499)
#undef  TRAINER_PICNICKER_MARCY
#define TRAINER_PICNICKER_MARCY                      (TRAINER_FRLG_OFFSET +  500)
#undef  TRAINER_RUIN_MANIAC_LAYTON
#define TRAINER_RUIN_MANIAC_LAYTON                   (TRAINER_FRLG_OFFSET +  501)
#undef  TRAINER_PICNICKER_KELSEY_2
#define TRAINER_PICNICKER_KELSEY_2                   (TRAINER_FRLG_OFFSET +  502)
#undef  TRAINER_PICNICKER_KELSEY_3
#define TRAINER_PICNICKER_KELSEY_3                   (TRAINER_FRLG_OFFSET +  503)
#undef  TRAINER_PICNICKER_KELSEY_4
#define TRAINER_PICNICKER_KELSEY_4                   (TRAINER_FRLG_OFFSET +  504)
#undef  TRAINER_CAMPER_RICKY_2
#define TRAINER_CAMPER_RICKY_2                       (TRAINER_FRLG_OFFSET +  505)
#undef  TRAINER_CAMPER_RICKY_3
#define TRAINER_CAMPER_RICKY_3                       (TRAINER_FRLG_OFFSET +  506)
#undef  TRAINER_CAMPER_RICKY_4
#define TRAINER_CAMPER_RICKY_4                       (TRAINER_FRLG_OFFSET +  507)
#undef  TRAINER_CAMPER_JEFF_2
#define TRAINER_CAMPER_JEFF_2                        (TRAINER_FRLG_OFFSET +  508)
#undef  TRAINER_CAMPER_JEFF_3
#define TRAINER_CAMPER_JEFF_3                        (TRAINER_FRLG_OFFSET +  509)
#undef  TRAINER_CAMPER_JEFF_4
#define TRAINER_CAMPER_JEFF_4                        (TRAINER_FRLG_OFFSET +  510)
#undef  TRAINER_PICNICKER_ISABELLE_2
#define TRAINER_PICNICKER_ISABELLE_2                 (TRAINER_FRLG_OFFSET +  511)
#undef  TRAINER_PICNICKER_ISABELLE_3
#define TRAINER_PICNICKER_ISABELLE_3                 (TRAINER_FRLG_OFFSET +  512)
#undef  TRAINER_PICNICKER_ISABELLE_4
#define TRAINER_PICNICKER_ISABELLE_4                 (TRAINER_FRLG_OFFSET +  513)
#undef  TRAINER_YOUNGSTER_YASU_2
#define TRAINER_YOUNGSTER_YASU_2                     (TRAINER_FRLG_OFFSET +  514)
#undef  TRAINER_YOUNGSTER_YASU_3
#define TRAINER_YOUNGSTER_YASU_3                     (TRAINER_FRLG_OFFSET +  515)
#undef  TRAINER_ENGINEER_BERNIE_2
#define TRAINER_ENGINEER_BERNIE_2                    (TRAINER_FRLG_OFFSET +  516)
#undef  TRAINER_GAMER_DARIAN_2
#define TRAINER_GAMER_DARIAN_2                       (TRAINER_FRLG_OFFSET +  517)
#undef  TRAINER_CAMPER_CHRIS_2
#define TRAINER_CAMPER_CHRIS_2                       (TRAINER_FRLG_OFFSET +  518)
#undef  TRAINER_CAMPER_CHRIS_3
#define TRAINER_CAMPER_CHRIS_3                       (TRAINER_FRLG_OFFSET +  519)
#undef  TRAINER_CAMPER_CHRIS_4
#define TRAINER_CAMPER_CHRIS_4                       (TRAINER_FRLG_OFFSET +  520)
#undef  TRAINER_PICNICKER_ALICIA_2
#define TRAINER_PICNICKER_ALICIA_2                   (TRAINER_FRLG_OFFSET +  521)
#undef  TRAINER_PICNICKER_ALICIA_3
#define TRAINER_PICNICKER_ALICIA_3                   (TRAINER_FRLG_OFFSET +  522)
#undef  TRAINER_PICNICKER_ALICIA_4
#define TRAINER_PICNICKER_ALICIA_4                   (TRAINER_FRLG_OFFSET +  523)
#undef  TRAINER_HIKER_JEREMY_2
#define TRAINER_HIKER_JEREMY_2                       (TRAINER_FRLG_OFFSET +  524)
#undef  TRAINER_POKEMANIAC_MARK_3
#define TRAINER_POKEMANIAC_MARK_3                    (TRAINER_FRLG_OFFSET +  525)
#undef  TRAINER_POKEMANIAC_HERMAN_2
#define TRAINER_POKEMANIAC_HERMAN_2                  (TRAINER_FRLG_OFFSET +  526)
#undef  TRAINER_POKEMANIAC_HERMAN_3
#define TRAINER_POKEMANIAC_HERMAN_3                  (TRAINER_FRLG_OFFSET +  527)
#undef  TRAINER_HIKER_TRENT_2
#define TRAINER_HIKER_TRENT_2                        (TRAINER_FRLG_OFFSET +  528)
#undef  TRAINER_LASS_MEGAN_2
#define TRAINER_LASS_MEGAN_2                         (TRAINER_FRLG_OFFSET +  529)
#undef  TRAINER_LASS_MEGAN_3
#define TRAINER_LASS_MEGAN_3                         (TRAINER_FRLG_OFFSET +  530)
#undef  TRAINER_SUPER_NERD_GLENN_2
#define TRAINER_SUPER_NERD_GLENN_2                   (TRAINER_FRLG_OFFSET +  531)
#undef  TRAINER_GAMER_RICH_2
#define TRAINER_GAMER_RICH_2                         (TRAINER_FRLG_OFFSET +  532)
#undef  TRAINER_BIKER_JAREN_2
#define TRAINER_BIKER_JAREN_2                        (TRAINER_FRLG_OFFSET +  533)
#undef  TRAINER_FISHERMAN_ELLIOT_2
#define TRAINER_FISHERMAN_ELLIOT_2                   (TRAINER_FRLG_OFFSET +  534)
#undef  TRAINER_ROCKER_LUCA_2
#define TRAINER_ROCKER_LUCA_2                        (TRAINER_FRLG_OFFSET +  535)
#undef  TRAINER_BEAUTY_SHEILA_2
#define TRAINER_BEAUTY_SHEILA_2                      (TRAINER_FRLG_OFFSET +  536)
#undef  TRAINER_BIRD_KEEPER_ROBERT_2
#define TRAINER_BIRD_KEEPER_ROBERT_2                 (TRAINER_FRLG_OFFSET +  537)
#undef  TRAINER_BIRD_KEEPER_ROBERT_3
#define TRAINER_BIRD_KEEPER_ROBERT_3                 (TRAINER_FRLG_OFFSET +  538)
#undef  TRAINER_PICNICKER_SUSIE_2
#define TRAINER_PICNICKER_SUSIE_2                    (TRAINER_FRLG_OFFSET +  539)
#undef  TRAINER_PICNICKER_SUSIE_3
#define TRAINER_PICNICKER_SUSIE_3                    (TRAINER_FRLG_OFFSET +  540)
#undef  TRAINER_PICNICKER_SUSIE_4
#define TRAINER_PICNICKER_SUSIE_4                    (TRAINER_FRLG_OFFSET +  541)
#undef  TRAINER_BIKER_LUKAS_2
#define TRAINER_BIKER_LUKAS_2                        (TRAINER_FRLG_OFFSET +  542)
#undef  TRAINER_BIRD_KEEPER_BENNY_2
#define TRAINER_BIRD_KEEPER_BENNY_2                  (TRAINER_FRLG_OFFSET +  543)
#undef  TRAINER_BIRD_KEEPER_BENNY_3
#define TRAINER_BIRD_KEEPER_BENNY_3                  (TRAINER_FRLG_OFFSET +  544)
#undef  TRAINER_BIRD_KEEPER_MARLON_2
#define TRAINER_BIRD_KEEPER_MARLON_2                 (TRAINER_FRLG_OFFSET +  545)
#undef  TRAINER_BIRD_KEEPER_MARLON_3
#define TRAINER_BIRD_KEEPER_MARLON_3                 (TRAINER_FRLG_OFFSET +  546)
#undef  TRAINER_BEAUTY_GRACE_2
#define TRAINER_BEAUTY_GRACE_2                       (TRAINER_FRLG_OFFSET +  547)
#undef  TRAINER_BIRD_KEEPER_CHESTER_2
#define TRAINER_BIRD_KEEPER_CHESTER_2                (TRAINER_FRLG_OFFSET +  548)
#undef  TRAINER_BIRD_KEEPER_CHESTER_3
#define TRAINER_BIRD_KEEPER_CHESTER_3                (TRAINER_FRLG_OFFSET +  549)
#undef  TRAINER_PICNICKER_BECKY_2
#define TRAINER_PICNICKER_BECKY_2                    (TRAINER_FRLG_OFFSET +  550)
#undef  TRAINER_PICNICKER_BECKY_3
#define TRAINER_PICNICKER_BECKY_3                    (TRAINER_FRLG_OFFSET +  551)
#undef  TRAINER_PICNICKER_BECKY_4
#define TRAINER_PICNICKER_BECKY_4                    (TRAINER_FRLG_OFFSET +  552)
#undef  TRAINER_CRUSH_KIN_RON_MYA_2
#define TRAINER_CRUSH_KIN_RON_MYA_2                  (TRAINER_FRLG_OFFSET +  553)
#undef  TRAINER_CRUSH_KIN_RON_MYA_3
#define TRAINER_CRUSH_KIN_RON_MYA_3                  (TRAINER_FRLG_OFFSET +  554)
#undef  TRAINER_CRUSH_KIN_RON_MYA_4
#define TRAINER_CRUSH_KIN_RON_MYA_4                  (TRAINER_FRLG_OFFSET +  555)
#undef  TRAINER_BIKER_RUBEN_2
#define TRAINER_BIKER_RUBEN_2                        (TRAINER_FRLG_OFFSET +  556)
#undef  TRAINER_CUE_BALL_CAMRON_2
#define TRAINER_CUE_BALL_CAMRON_2                    (TRAINER_FRLG_OFFSET +  557)
#undef  TRAINER_BIKER_JAXON_2
#define TRAINER_BIKER_JAXON_2                        (TRAINER_FRLG_OFFSET +  558)
#undef  TRAINER_CUE_BALL_ISAIAH_2
#define TRAINER_CUE_BALL_ISAIAH_2                    (TRAINER_FRLG_OFFSET +  559)
#undef  TRAINER_CUE_BALL_COREY_2
#define TRAINER_CUE_BALL_COREY_2                     (TRAINER_FRLG_OFFSET +  560)
#undef  TRAINER_BIRD_KEEPER_JACOB_2
#define TRAINER_BIRD_KEEPER_JACOB_2                  (TRAINER_FRLG_OFFSET +  561)
#undef  TRAINER_BIRD_KEEPER_JACOB_3
#define TRAINER_BIRD_KEEPER_JACOB_3                  (TRAINER_FRLG_OFFSET +  562)
#undef  TRAINER_SWIMMER_FEMALE_ALICE_2
#define TRAINER_SWIMMER_FEMALE_ALICE_2               (TRAINER_FRLG_OFFSET +  563)
#undef  TRAINER_SWIMMER_MALE_DARRIN_2
#define TRAINER_SWIMMER_MALE_DARRIN_2                (TRAINER_FRLG_OFFSET +  564)
#undef  TRAINER_PICNICKER_MISSY_2
#define TRAINER_PICNICKER_MISSY_2                    (TRAINER_FRLG_OFFSET +  565)
#undef  TRAINER_PICNICKER_MISSY_3
#define TRAINER_PICNICKER_MISSY_3                    (TRAINER_FRLG_OFFSET +  566)
#undef  TRAINER_FISHERMAN_WADE_2
#define TRAINER_FISHERMAN_WADE_2                     (TRAINER_FRLG_OFFSET +  567)
#undef  TRAINER_SWIMMER_MALE_JACK_2
#define TRAINER_SWIMMER_MALE_JACK_2                  (TRAINER_FRLG_OFFSET +  568)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_2
#define TRAINER_SIS_AND_BRO_LIL_IAN_2                (TRAINER_FRLG_OFFSET +  569)
#undef  TRAINER_SIS_AND_BRO_LIL_IAN_3
#define TRAINER_SIS_AND_BRO_LIL_IAN_3                (TRAINER_FRLG_OFFSET +  570)
#undef  TRAINER_SWIMMER_MALE_FINN_2
#define TRAINER_SWIMMER_MALE_FINN_2                  (TRAINER_FRLG_OFFSET +  571)
#undef  TRAINER_CRUSH_GIRL_SHARON_2
#define TRAINER_CRUSH_GIRL_SHARON_2                  (TRAINER_FRLG_OFFSET +  572)
#undef  TRAINER_CRUSH_GIRL_SHARON_3
#define TRAINER_CRUSH_GIRL_SHARON_3                  (TRAINER_FRLG_OFFSET +  573)
#undef  TRAINER_CRUSH_GIRL_TANYA_2
#define TRAINER_CRUSH_GIRL_TANYA_2                   (TRAINER_FRLG_OFFSET +  574)
#undef  TRAINER_CRUSH_GIRL_TANYA_3
#define TRAINER_CRUSH_GIRL_TANYA_3                   (TRAINER_FRLG_OFFSET +  575)
#undef  TRAINER_BLACK_BELT_SHEA_2
#define TRAINER_BLACK_BELT_SHEA_2                    (TRAINER_FRLG_OFFSET +  576)
#undef  TRAINER_BLACK_BELT_SHEA_3
#define TRAINER_BLACK_BELT_SHEA_3                    (TRAINER_FRLG_OFFSET +  577)
#undef  TRAINER_BLACK_BELT_HUGH_2
#define TRAINER_BLACK_BELT_HUGH_2                    (TRAINER_FRLG_OFFSET +  578)
#undef  TRAINER_BLACK_BELT_HUGH_3
#define TRAINER_BLACK_BELT_HUGH_3                    (TRAINER_FRLG_OFFSET +  579)
#undef  TRAINER_CRUSH_KIN_MIK_KIA_2
#define TRAINER_CRUSH_KIN_MIK_KIA_2                  (TRAINER_FRLG_OFFSET +  580)
#undef  TRAINER_CRUSH_KIN_MIK_KIA_3
#define TRAINER_CRUSH_KIN_MIK_KIA_3                  (TRAINER_FRLG_OFFSET +  581)
#undef  TRAINER_TUBER_AMIRA_2
#define TRAINER_TUBER_AMIRA_2                        (TRAINER_FRLG_OFFSET +  582)
#undef  TRAINER_TWINS_JOY_MEG_2
#define TRAINER_TWINS_JOY_MEG_2                      (TRAINER_FRLG_OFFSET +  583)
#undef  TRAINER_PAINTER_RAYNA_2
#define TRAINER_PAINTER_RAYNA_2                      (TRAINER_FRLG_OFFSET +  584)
#undef  TRAINER_YOUNGSTER_DESTIN_2
#define TRAINER_YOUNGSTER_DESTIN_2                   (TRAINER_FRLG_OFFSET +  585)
#undef  TRAINER_PKMN_BREEDER_ALIZE_2
#define TRAINER_PKMN_BREEDER_ALIZE_2                 (TRAINER_FRLG_OFFSET +  586)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_2
#define TRAINER_YOUNG_COUPLE_GIA_JES_2               (TRAINER_FRLG_OFFSET +  587)
#undef  TRAINER_YOUNG_COUPLE_GIA_JES_3
#define TRAINER_YOUNG_COUPLE_GIA_JES_3               (TRAINER_FRLG_OFFSET +  588)
#undef  TRAINER_BIRD_KEEPER_MILO_2
#define TRAINER_BIRD_KEEPER_MILO_2                   (TRAINER_FRLG_OFFSET +  589)
#undef  TRAINER_BIRD_KEEPER_CHAZ_2
#define TRAINER_BIRD_KEEPER_CHAZ_2                   (TRAINER_FRLG_OFFSET +  590)
#undef  TRAINER_BIRD_KEEPER_HAROLD_2
#define TRAINER_BIRD_KEEPER_HAROLD_2                 (TRAINER_FRLG_OFFSET +  591)
#undef  TRAINER_SWIMMER_FEMALE_NICOLE_2
#define TRAINER_SWIMMER_FEMALE_NICOLE_2              (TRAINER_FRLG_OFFSET +  592)
#undef  TRAINER_PSYCHIC_JACLYN_2
#define TRAINER_PSYCHIC_JACLYN_2                     (TRAINER_FRLG_OFFSET +  593)
#undef  TRAINER_SWIMMER_MALE_SAMIR_2
#define TRAINER_SWIMMER_MALE_SAMIR_2                 (TRAINER_FRLG_OFFSET +  594)
#undef  TRAINER_HIKER_EARL_2
#define TRAINER_HIKER_EARL_2                         (TRAINER_FRLG_OFFSET +  595)
#undef  TRAINER_RUIN_MANIAC_LARRY_2
#define TRAINER_RUIN_MANIAC_LARRY_2                  (TRAINER_FRLG_OFFSET +  596)
#undef  TRAINER_POKEMANIAC_HECTOR_2
#define TRAINER_POKEMANIAC_HECTOR_2                  (TRAINER_FRLG_OFFSET +  597)
#undef  TRAINER_PSYCHIC_DARIO_2
#define TRAINER_PSYCHIC_DARIO_2                      (TRAINER_FRLG_OFFSET +  598)
#undef  TRAINER_PSYCHIC_RODETTE_2
#define TRAINER_PSYCHIC_RODETTE_2                    (TRAINER_FRLG_OFFSET +  599)
#undef  TRAINER_JUGGLER_MASON_2
#define TRAINER_JUGGLER_MASON_2                      (TRAINER_FRLG_OFFSET +  600)
#undef  TRAINER_PKMN_RANGER_NICOLAS_2
#define TRAINER_PKMN_RANGER_NICOLAS_2                (TRAINER_FRLG_OFFSET +  601)
#undef  TRAINER_PKMN_RANGER_MADELINE_2
#define TRAINER_PKMN_RANGER_MADELINE_2               (TRAINER_FRLG_OFFSET +  602)
#undef  TRAINER_CRUSH_GIRL_CYNDY_2
#define TRAINER_CRUSH_GIRL_CYNDY_2                   (TRAINER_FRLG_OFFSET +  603)
#undef  TRAINER_TAMER_EVAN_2
#define TRAINER_TAMER_EVAN_2                         (TRAINER_FRLG_OFFSET +  604)
#undef  TRAINER_PKMN_RANGER_JACKSON_2
#define TRAINER_PKMN_RANGER_JACKSON_2                (TRAINER_FRLG_OFFSET +  605)
#undef  TRAINER_PKMN_RANGER_KATELYN_2
#define TRAINER_PKMN_RANGER_KATELYN_2                (TRAINER_FRLG_OFFSET +  606)
#undef  TRAINER_COOLTRAINER_LEROY_2
#define TRAINER_COOLTRAINER_LEROY_2                  (TRAINER_FRLG_OFFSET +  607)
#undef  TRAINER_COOLTRAINER_MICHELLE_2
#define TRAINER_COOLTRAINER_MICHELLE_2               (TRAINER_FRLG_OFFSET +  608)
#undef  TRAINER_COOL_COUPLE_LEX_NYA_2
#define TRAINER_COOL_COUPLE_LEX_NYA_2                (TRAINER_FRLG_OFFSET +  609)
#undef  TRAINER_BUG_CATCHER_COLTON_2
#define TRAINER_BUG_CATCHER_COLTON_2                 (TRAINER_FRLG_OFFSET +  610)
#undef  TRAINER_BUG_CATCHER_COLTON_3
#define TRAINER_BUG_CATCHER_COLTON_3                 (TRAINER_FRLG_OFFSET +  611)
#undef  TRAINER_BUG_CATCHER_COLTON_4
#define TRAINER_BUG_CATCHER_COLTON_4                 (TRAINER_FRLG_OFFSET +  612)
#undef  TRAINER_SWIMMER_MALE_MATTHEW_2
#define TRAINER_SWIMMER_MALE_MATTHEW_2               (TRAINER_FRLG_OFFSET +  613)
#undef  TRAINER_SWIMMER_MALE_TONY_2
#define TRAINER_SWIMMER_MALE_TONY_2                  (TRAINER_FRLG_OFFSET +  614)
#undef  TRAINER_SWIMMER_FEMALE_MELISSA_2
#define TRAINER_SWIMMER_FEMALE_MELISSA_2             (TRAINER_FRLG_OFFSET +  615)
#undef  TRAINER_ELITE_FOUR_LORELEI_2
#define TRAINER_ELITE_FOUR_LORELEI_2                 (TRAINER_FRLG_OFFSET +  616)
#undef  TRAINER_ELITE_FOUR_BRUNO_2
#define TRAINER_ELITE_FOUR_BRUNO_2                   (TRAINER_FRLG_OFFSET +  617)
#undef  TRAINER_ELITE_FOUR_AGATHA_2
#define TRAINER_ELITE_FOUR_AGATHA_2                  (TRAINER_FRLG_OFFSET +  618)
#undef  TRAINER_ELITE_FOUR_LANCE_2
#define TRAINER_ELITE_FOUR_LANCE_2                   (TRAINER_FRLG_OFFSET +  619)
#undef  TRAINER_CHAMPION_REMATCH_SQUIRTLE
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE            (TRAINER_FRLG_OFFSET +  620)
#undef  TRAINER_CHAMPION_REMATCH_BULBASAUR
#define TRAINER_CHAMPION_REMATCH_BULBASAUR           (TRAINER_FRLG_OFFSET +  621)
#undef  TRAINER_CHAMPION_REMATCH_CHARMANDER
#define TRAINER_CHAMPION_REMATCH_CHARMANDER          (TRAINER_FRLG_OFFSET +  622)
#undef  TRAINER_CUE_BALL_PAXTON
#define TRAINER_CUE_BALL_PAXTON                      (TRAINER_FRLG_OFFSET +  623)

#endif // GUARD_CONSTANTS_OPPONENTS_KANTO_H
