CeladonCity_Gym_Frlg_MapScripts::
	.byte 0

CeladonCity_Gym_EventScript_Erika::
	end

CeladonCity_Gym_EventScript_Erika_Defeated::
	end

CeladonCity_Gym_EventScript_GymStatue::
	end

CeladonCity_Gym_EventScript_GymStatuePostVictory::
	end

CeladonCity_Gym_EventScript_Jo::
	end

CeladonCity_Gym_EventScript_Julia::
	end

CeladonCity_Gym_EventScript_Michelle::
	end

CeladonCity_Gym_EventScript_Tanya::
	end

CeladonCity_Gym_EventScript_Zoe::
	end

CeladonCity_Gym_Text_GymStatue::
	end

CeladonCity_Gym_Text_GymStatuePlayerWon::
	end

