Route19_Frlg_MapScripts::
	.byte 0

CherryGroveCity_EventScript_Kingler::
	end

LakeOfRageLowTide_EventScript_Sage::
	end

Route19_EventScript_Dawn::
	end

Route19_EventScript_Fatman::
	end

Route19_EventScript_FatmanBefore::
	end

Route19_EventScript_Fisher::
	end

Route19_EventScript_FisherBefore::
	end

Route19_EventScript_Harold::
	end

Route19_EventScript_Jerome::
	end

Route19_EventScript_Sign::
	end

Route19_EventScript_SwimSign::
	end

Route19_EventScript_Tucker::
	end
