IndigoPlateau_PokemonCenter_Frlg_MapScripts::
	.byte 0



IndigoPlateau_EventScript_Abra::
	end

IndigoPlateau_EventScript_BlackBelt::
	end

IndigoPlateau_EventScript_Cooltrainer::
	end

IndigoPlateau_EventScript_Psychic::
	end

IndigoPlateau_EventScript_PsychicTeleport::
	end

IndigoPlateau_EventScript_ShigyNinja::
	end

IndigoPlateau_EventScript_Silver::
	end

IndigoPlateau_EventScript_SilverBeat::
	end

IndigoPlateau_Pokecenter_OnTransition::
	end

IndigoPlateau_PokemonCenter_Enter::
	end

IndigoPlateau_PokemonCenter_OnFrame::
	end

IndigoPlateau_Silver_Battle_Chikorita::
	end

IndigoPlateau_Silver_Battle_Cyndaquil::
	end

IndigoPlateau_Silver_Battle_Totodile::
	end


RuinsOfAlph_PuzzleAndRewardChambers_MapScript_StatueDescription::
	end
