Route10_PowerPlantEntrance_Frlg_MapScripts::
	.byte 0

Route10_PowerPlantEntrance_EventScript_Cop::
	end

Route10_PowerPlantEntrance_EventScript_Cop2::
	end

Route10_PowerPlantEntrance_EventScript_Cop2Done::
	end

Route10_PowerPlantEntrance_EventScript_CopAfterDone::
	end

Route10_PowerPlantEntrance_EventScript_CopDuringRocket::
	end

Route10_PowerPlantEntrance_EventScript_Engineer1::
	end

Route10_PowerPlantEntrance_EventScript_Engineer1Done::
	end

Route10_PowerPlantEntrance_EventScript_Engineer2::
	end

Route10_PowerPlantEntrance_EventScript_Engineer2Done::
	end

Route10_PowerPlantEntrance_EventScript_Engineer3::
	end

Route10_PowerPlantEntrance_EventScript_Engineer3Done::
	end

Route10_PowerPlantEntrance_Trigger_Cop::
	end
