RocketHideout_B1F_Frlg_MapScripts::
	.byte 0

RocketHideout_B1F_EventScript_DummyPanel::
	end

RocketHideout_B1F_EventScript_Grunt1::
	end

RocketHideout_B1F_EventScript_Grunt2::
	end

RocketHideout_B1F_EventScript_Grunt3::
	end

RocketHideout_B1F_EventScript_Grunt4::
	end

RocketHideout_B1F_EventScript_Grunt5::
	end

RocketHideout_B1F_EventScript_HeightAdjust::
	end

RocketHideout_B1F_EventScript_Item_BigNugget::
	end

RocketHideout_B1F_EventScript_Item_HyperPotion::
	end

RocketHideout_B1F_EventScript_Item_Revive::
	end

RocketHideout_B1F_EventScript_Persian::
	end

RocketHideout_B1F_EventScript_Rocket16::
	end

RocketHideout_B1F_EventScript_SetStatue1::
	end

RocketHideout_B1F_EventScript_SetStatue2::
	end

RocketHideout_B1F_EventScript_SetStatue3::
	end

RocketHideout_B1F_EventScript_SetStatue4::
	end

RocketHideout_B1F_EventScript_SetStatue5::
	end

RocketHideout_B1F_EventScript_SpawnGruntLeft::
	end

RocketHideout_B1F_EventScript_SpawnGruntRight::
	end

RocketHideout_B1F_EventScript_Switch::
	end

RocketHideout_B1F_EventScript_TrainerJed::
	end

RocketHideout_B1F_EventScript_TurnOffSwitch::
	end

RocketHideout_B1F_OnLoad::
	end

RocketHideout_B1F_TriggerTest::
	end

RocketHideout_B1F_Trigger_SpawnGruntStatue1::
	end

RocketHideout_B1F_Trigger_SpawnGruntStatue2::
	end

RocketHideout_B1F_Trigger_SpawnGruntStatue3::
	end

RocketHideout_B1F_Trigger_SpawnGruntStatue4::
	end

RocketHideout_B1F_Trigger_SpawnGruntStatue5::
	end

RocketHideout_B1F_Trigger_Statue1::
	end

RocketHideout_B1F_Trigger_Statue2::
	end

RocketHideout_B1F_Trigger_Statue3::
	end

RocketHideout_B1F_Trigger_Statue4::
	end

RocketHideout_B1F_Trigger_Statue5::
	end

RocketHideout_B1F_Trigger_StatueGruntLeft::
	end

RocketHideout_B1F_Trigger_StatueGruntRight::
	end
