Route25_BillsHouse_Frlg_MapScripts::
	.byte 0

Route25_BillsHouse_EventScript_Gramps::
	end

Route25_BillsHouse_EventScript_Gramps_Correctmon::
	end

Route25_BillsHouse_EventScript_Gramps_Declined::
	end

Route25_BillsHouse_EventScript_Gramps_ExtraLeafStones::
	end

Route25_BillsHouse_EventScript_Gramps_Growlithe::
	end

Route25_BillsHouse_EventScript_Gramps_Lotad::
	end

Route25_BillsHouse_EventScript_Gramps_Pichu::
	end

Route25_BillsHouse_EventScript_Gramps_Roselia::
	end

Route25_BillsHouse_EventScript_Gramps_ShownAll::
	end

Route25_BillsHouse_EventScript_Gramps_Spinda::
	end

Route25_BillsHouse_EventScript_Gramps_WrongMon::
	end

Route25_BillsHouse_Test::
	end
