RocketHideout_B2F_Frlg_MapScripts::
	.byte 0

RockerHideout2_DeactivateGenerator::
	end

RocketHideout_B2F_EventScript_ArianaTrainer::
	end

RocketHideout_B2F_EventScript_ChoosePartyForMultiBattle::
	end

RocketHideout_B2F_EventScript_DefeatedAriana::
	end

RocketHideout_B2F_EventScript_DoLanceMultiBattle::
	end

RocketHideout_B2F_EventScript_Electrode::
	end

RocketHideout_B2F_EventScript_ElectrodeDone::
	end

RocketHideout_B2F_EventScript_Grunt::
	end

RocketHideout_B2F_EventScript_Grunt14::
	end

RocketHideout_B2F_EventScript_Grunt15::
	end

RocketHideout_B2F_EventScript_Grunt16::
	end

RocketHideout_B2F_EventScript_GruntTrainer::
	end

RocketHideout_B2F_EventScript_Lance::
	end

RocketHideout_B2F_EventScript_LanceTriggerLeft::
	end

RocketHideout_B2F_EventScript_LanceTriggerRight::
	end

RocketHideout_B2F_EventScript_Ran_Electrode::
	end

RocketHideout_B2F_EventScript_ReadyForBattlePrompt::
	end

RocketHideout_B2F_HideGate::
	end

RocketHideout_B2F_MoveLanceDragonite::
	end

RocketHideout_B2F_OnLoad::
	end

RocketHideout_B2F_Trigger_Ariana::
	end

RocketHideout_B2F_Trigger_Electrode::
	end

RocketHideout_B2F_Trigger_MurkrowGate::
	end

RocketHideout_B2F_Trigger_MurkrowStairs::
	end

RocketHideout_B2F_Trigger_PlayerMoveLeft::
	end

RocketHideout_B2F_Trigger_PlayerMoveRight::
	end

RocketHideout_EventScript_Item_Thief::
	end
