SaffronCity_FightingDojo_Frlg_MapScripts::
	.byte 0

BattleFrontier_Lounge9_Heal::
	end

SaffronCity_FightingDojo_Ability_Man::
	end

SaffronCity_FightingDojo_EventScript_Alakazam_EV_SpecialAttack::
	end

SaffronCity_FightingDojo_EventScript_BattleAlakazam_EV_SpecialAttack::
	end

SaffronCity_FightingDojo_EventScript_BattleLickilicky_EV_HP::
	end

SaffronCity_FightingDojo_EventScript_BattleMachamp_EV_Attack::
	end

SaffronCity_FightingDojo_EventScript_BattlePidgeot_EV_Speed::
	end

SaffronCity_FightingDojo_EventScript_BattleSlowking_EV_SpecialDefense::
	end

SaffronCity_FightingDojo_EventScript_BattleSteelix_EV_Defense::
	end

SaffronCity_FightingDojo_EventScript_BlackBelt::
	end

SaffronCity_FightingDojo_EventScript_Cooltrainer::
	end

SaffronCity_FightingDojo_EventScript_Lickilicky_EV_HP::
	end

SaffronCity_FightingDojo_EventScript_Machamp_EV_Attack::
	end

SaffronCity_FightingDojo_EventScript_Pidgeot_EV_Speed::
	end

SaffronCity_FightingDojo_EventScript_Refused::
	end

SaffronCity_FightingDojo_EventScript_Slowking_EV_SpecialDefense::
	end

SaffronCity_FightingDojo_EventScript_StatueLeft::
	end

SaffronCity_FightingDojo_EventScript_StatueRight::
	end

SaffronCity_FightingDojo_EventScript_Steelix_EV_Defense::
	end

SaffronCity_FightingDojo_SetZeroNoMoney::
	end

SaffronCity_FightingDojo_Text_Cooltrainer::
	end

