PowerPlant_Frlg_MapScripts::
	.byte 0

PowerPlant_EventScript_DefeatedZapdos::
	end

PowerPlant_EventScript_Electrode1::
	end

PowerPlant_EventScript_Electrode2::
	end

PowerPlant_EventScript_FoughtElectrode1::
	end

PowerPlant_EventScript_FoughtElectrode2::
	end

PowerPlant_EventScript_RanFromZapdos::
	end

PowerPlant_EventScript_ShowElectrode1::
	end

PowerPlant_EventScript_ShowElectrode2::
	end

PowerPlant_EventScript_ShowZapdos::
	end

PowerPlant_EventScript_TryRemoveStaticMon::
	end

PowerPlant_EventScript_Zapdos::
	end

PowerPlant_OnResume::
	end

PowerPlant_OnTransition::
	end

