Route25_Frlg_MapScripts::
	.byte 0

Route25_AdjustPlayer::
	end

Route25_EventScript_BillsHouseSign::
	end

Route25_EventScript_Dudley::
	end

Route25_EventScript_Ellen::
	end

Route25_EventScript_Eusine::
	end

Route25_EventScript_Joe::
	end

Route25_EventScript_Kevin::
	end

Route25_EventScript_KevinAfter::
	end

Route25_EventScript_Laura::
	end

Route25_EventScript_Lloyd::
	end

Route25_EventScript_Misty::
	end

Route25_EventScript_MistyRematch::
	end

Route25_EventScript_Pat::
	end

Route25_EventScript_SetSuicuneSceneMid::
	end

Route25_EventScript_Shannon::
	end

Route25_EventScript_Suicune::
	end

Route25_EventScript_SuicuneMerge::
	end

Route25_EventScript_SuicunePostGame::
	end

Route25_EventScript_SuicuneRan::
	end

Route25_MapScript_OnTransition::
	end

Route25_Trigger_MistyLeft::
	end

Route25_Trigger_MistyRight::
	end

Route25_Trigger_SuicuneLeft::
	end

Route25_Trigger_SuicuneRight::
	end
