FuchsiaCity_SafariZoneEntrance_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZoneEntrance_EventScript_CheckHasRoomForPokemon::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_CorrectionLeft::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_CorrectionRight::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_EntranceCounterTrigger::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_ExitSafari::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_HasRoomForPokemon::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_MeetSteven::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_MovePlayerBackFromCounter::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_NoPokeblockCase::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_NotEnoughMoney::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_ReenterSafari::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_StevenGiveCase::
	end

FuchsiaCity_SafariZoneEntrance_EventScript_TryEnterSafariZone::
	end

FuchsiaCity_SafariZoneEntrance_FirstTime::
	end

FuchsiaCity_SafariZoneEntrance_OnFrame::
	end

FuchsiaCity_SafariZoneEntrance_OnTransition::
	end

FuchsiaCity_SafariZoneEntrance_Steven::
	end

FuchsiaCity_SafariZoneEntrance_StevenAfter::
	end

FuchsiaCity_SafariZoneEntrance_StevenChamp::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuy::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuy1::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuy2::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuy3::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuyDecline::
	end

FuchsiaCity_SafariZoneEntrance_UpgradeGuyNotEnoughMoney::
	end




Route121_SafariZoneGate_SafariZoneEntrance_EventScript_InfoAttendant::
	end
