Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_Carter::
	end

Route14_EventScript_Pidgeotto::
	end

Route14_EventScript_PidgeottoBlowPlayer::
	end

Route14_EventScript_PidgeottoBlowPlayerLeft::
	end

Route14_EventScript_PidgeottoDislikedBerry::
	end

Route14_EventScript_Roy::
	end

Route14_EventScript_Suicune::
	end

Route14_EventScript_Trevor::
	end

Route14_TriggerSuicune_1::
	end

Route14_TriggerSuicune_2::
	end

Route14_TriggerSuicune_3::
	end

Route14_TriggerSuicune_4::
	end

Route14_TriggerSuicune_5::
	end
