VictoryRoadKanto_1F_Frlg_MapScripts::
	.byte 0

VictoryRoadKanto_1F_EventScript_Item_MaxEther::
	end

VictoryRoadKanto_1F_EventScript_Item_RareCandy::
	end

VictoryRoadKanto_1F_EventScript_Item_UltraBall::
	end

VictoryRoadKanto_1F_EventScript_SilverEnterLeft::
	end

VictoryRoadKanto_1F_EventScript_SilverEnterMid::
	end

VictoryRoadKanto_1F_EventScript_SilverEnterRight::
	end

VictoryRoadKanto_1F_Silver_Battle_Chikorita::
	end

VictoryRoadKanto_1F_Silver_Battle_Cyndaquil::
	end

VictoryRoadKanto_1F_Silver_Battle_Totodile::
	end

VictoryRoadKanto_1F_Trigger::
	end
