PalletTown_Lab_Frlg_MapScripts::
	.byte 0

PalletTown_Lab_EventScript_Assistant1::
	end

PalletTown_Lab_EventScript_Assistant2::
	end

PalletTown_Lab_EventScript_Assistant3::
	end

PalletTown_Lab_EventScript_Oak::
	end

PalletTown_Lab_EventScript_Oak16Badges::
	end

PalletTown_Lab_EventScript_Oak9Badges::
	end

PalletTown_Lab_EventScript_OakBadgeCheck::
	end

PalletTown_Lab_EventScript_OakDex::
	end

PalletTown_Lab_EventScript_OakGiveNatDex_ForPlaytesters::
	end

PalletTown_Lab_EventScript_PC::
	end
