@ Local object IDs for seagallop.inc compatibility
        .set LOCALID_VERMILION_FERRY_SAILOR, 1
VermilionCity_Frlg_MapScripts::
	.byte 0

VermilionCity_EventScript_BadgeGuy::
	end

VermilionCity_EventScript_BadgeGuyAfter::
	end

VermilionCity_EventScript_BadgeGuyAll::
	end

VermilionCity_EventScript_BadgeGuyMost::
	end

VermilionCity_EventScript_BadgeGuySome::
	end

VermilionCity_EventScript_CitySign::
	end

VermilionCity_EventScript_DiglettsCaveSign::
	end

VermilionCity_EventScript_FanClubSign::
	end

VermilionCity_EventScript_GymSign::
	end

VermilionCity_EventScript_Machop::
	end

VermilionCity_EventScript_Nerd::
	end

VermilionCity_EventScript_OldSeaMap::
	end

VermilionCity_EventScript_Oldman::
	end

VermilionCity_EventScript_SetSuicuneScene::
	end

VermilionCity_EventScript_Snorlax::
	end

VermilionCity_EventScript_SnorlaxRan::
	end

VermilionCity_EventScript_SnorlaxWakeUp::
	end

VermilionCity_EventScript_SuicuneEpisode::
	end

VermilionCity_EventScript_Teacher::
	end

VermilionCity_MapScript_OnTransition::
	end

VermilionCity_TriggerSuicuneBot::
	end

VermilionCity_TriggerSuicuneMid::
	end

VermilionCity_TriggerSuicuneNorth_Left::
	end

VermilionCity_TriggerSuicuneNorth_Merge::
	end

VermilionCity_TriggerSuicuneNorth_Mid::
	end

VermilionCity_TriggerSuicuneNorth_Right::
	end

VermilionCity_TriggerSuicuneTop::
	end
