PokemonLeague_WillsRoom_Frlg_MapScripts::
	.byte 0

EliteFourRoom_CloseDoor::
	end

EliteFourRoom_CreateDoor::
	end

EliteFourRoom_OnFrame::
	end

EliteFourRoom_OnLoad::
	end

PokemonLeague_WillsRoom_EventScript_Will::
	end

PokemonLeague_WillsRoom_EventScript_WillDefeated::
	end

PokemonLeague_WillsRoom_EventScript_WillOnDefeat::
	end

PokemonLeague_WillsRoom_EventScript_WillRematch::
	end

PokemonLeague_WillsRoom_OnResume::
	end
