PokemonLeague_HallOfFame_Frlg_MapScripts::
	.byte 0

PokemonLeague_HallOfFame_EventScript_Cutscene::
	end

PokemonLeague_HallOfFame_EventScript_CutsceneKantoChamp::
	end

PokemonLeague_HallOfFame_EventScript_SetFirstGameClearFlags::
	end

PokemonLeague_HallOfFame_EventScript_SetGameClearFlags::
	end

PokemonLeague_HallOfFame_EventScript_SpawnKantoLeaderRematches::
	end

PokemonLeague_HallOfFame_EventScript_SpawnRoamers::
	end

PokemonLeague_HallOfFame_EventScript_SpawnSecondCelebi::
	end

PokemonLeague_HallOfFame_EventScript_SpawnSuicune::
	end

PokemonLeague_HallOfFame_OnFrame::
	end
