SaffronCity_TrainStation_Frlg_MapScripts::
	.byte 0

SaffronStation_EventScript_Attendant::
	end

SaffronStation_EventScript_Attendant2::
	end

SaffronStation_EventScript_AttendantTrainNotRunning::
	end

SaffronStation_EventScript_BoardTrain::
	end

SaffronStation_EventScript_ExitTrain::
	end

SaffronStation_EventScript_Lass::
	end

SaffronStation_EventScript_Nerd::
	end

SaffronStation_EventScript_Nerd2::
	end

SaffronStation_EventScript_Teacher::
	end

SaffronStation_OnFrame::
	end
