MtMoon_1F_Frlg_MapScripts::
	.byte 0

MtMoon_1F_EventScript_Iris::
	end

MtMoon_1F_EventScript_Josh::
	end

MtMoon_1F_EventScript_Jovan::
	end

MtMoon_1F_EventScript_Kent::
	end

MtMoon_1F_EventScript_Marcos::
	end

MtMoon_1F_EventScript_Miriam::
	end

MtMoon_1F_EventScript_Robby::
	end

MtMoon_1F_EventScript_ZubatSign::
	end

MtMoon_1F_OnTransition::
	end

MtMoon_1F_Text_IrisDefeat::
	end

MtMoon_1F_Text_IrisIntro::
	end

MtMoon_1F_Text_IrisPostBattle::
	end

MtMoon_1F_Text_JoshDefeat::
	end

MtMoon_1F_Text_JoshIntro::
	end

MtMoon_1F_Text_JoshPostBattle::
	end

MtMoon_1F_Text_JovanDefeat::
	end

MtMoon_1F_Text_JovanIntro::
	end

MtMoon_1F_Text_JovanPostBattle::
	end

MtMoon_1F_Text_KentDefeat::
	end

MtMoon_1F_Text_KentIntro::
	end

MtMoon_1F_Text_KentPostBattle::
	end

MtMoon_1F_Text_MarcosDefeat::
	end

MtMoon_1F_Text_MarcosIntro::
	end

MtMoon_1F_Text_MarcosPostBattle::
	end

MtMoon_1F_Text_MiriamDefeat::
	end

MtMoon_1F_Text_MiriamIntro::
	end

MtMoon_1F_Text_MiriamPostBattle::
	end

MtMoon_1F_Text_RobbyDefeat::
	end

MtMoon_1F_Text_RobbyIntro::
	end

MtMoon_1F_Text_RobbyPostBattle::
	end

MtMoon_1F_Text_ZubatIsABloodsucker::
	end

