CeruleanCity_Gym_Frlg_MapScripts::
	.byte 0

CeruleanCity_Gym_EventScript_DoNothing::
	end

CeruleanCity_Gym_EventScript_GymGuy::
	end

CeruleanCity_Gym_EventScript_GymGuyAfter::
	end

CeruleanCity_Gym_EventScript_GymStatuePostVictory::
	end

CeruleanCity_Gym_EventScript_MachinePart::
	end

CeruleanCity_Gym_EventScript_MachinePartItem::
	end

CeruleanCity_Gym_EventScript_Misty::
	end

CeruleanCity_Gym_EventScript_Misty_Defeated::
	end

CeruleanCity_Gym_EventScript_RocketGrunt::
	end

CeruleanCity_Gym_EventScript_Statue::
	end

CeruleanCity_Gym_EventScript_StatueDuringRocket::
	end

CeruleanCity_Gym_EventScript_TryMachinePart::
	end

CeruleanCity_Gym_OnFrame::
	end

CeruleanCity_Gym_SetSuicuneScene::
	end

CeruleanCity_Gym_Text_GymStatue::
	end

CeruleanCity_Gym_Text_GymStatuePlayerWon::
	end

CeruleanGym_EventScript_Briana::
	end

CeruleanGym_EventScript_Diana::
	end

CeruleanGym_EventScript_Parker::
	end

CherryGroveCity_EventScript_Corsola::
	end

CherryGroveCity_EventScript_Staryu::
	end

Route47_EventScript_Chinchou::
	end
