Route10_PowerPlantBackRoom_Frlg_MapScripts::
	.byte 0

Route10_PowerPlantBackRoom_EventScript_Engineer::
	end

Route10_PowerPlantBackRoom_EventScript_Manager::
	end

Route10_PowerPlantBackRoom_EventScript_ManagerCheckPart::
	end

Route10_PowerPlantBackRoom_EventScript_ManagerDone::
	end

Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket::
	end

Route10_PowerPlantBackRoom_EventScript_ManagerInitial::
	end
