VermilionCity_FanClub_Frlg_MapScripts::
	.byte 0

VermilionCity_FanClub_EventScript_Bayleef::
	end

VermilionCity_FanClub_EventScript_Chairman::
	end

VermilionCity_FanClub_EventScript_ChairmanAfter::
	end

VermilionCity_FanClub_EventScript_ChairmanRefused::
	end

VermilionCity_FanClub_EventScript_ClefairyAfter::
	end

VermilionCity_FanClub_EventScript_ClefairyGiveDoll::
	end

VermilionCity_FanClub_EventScript_ClefairyGuy::
	end

VermilionCity_FanClub_EventScript_Woman1::
	end

VermilionCity_FanClub_EventScript_Woman2::
	end
