VermilionCity_Gym_Frlg_MapScripts::
	.byte 0

VermilionCity_Gym_EventScript_FoundSwitchOne::
	end

VermilionCity_Gym_EventScript_FoundSwitchTwo::
	end

VermilionCity_Gym_EventScript_GiveTM::
	end

VermilionCity_Gym_EventScript_GiveThunderstone::
	end

VermilionCity_Gym_EventScript_Gregory::
	end

VermilionCity_Gym_EventScript_GymGuy::
	end

VermilionCity_Gym_EventScript_GymGuyPostVictory::
	end

VermilionCity_Gym_EventScript_GymStatue::
	end

VermilionCity_Gym_EventScript_GymStatuePostVictory::
	end

VermilionCity_Gym_EventScript_Horton::
	end

VermilionCity_Gym_EventScript_InitTrashCans::
	end

VermilionCity_Gym_EventScript_LocksAlreadyOpen::
	end

VermilionCity_Gym_EventScript_Return::
	end

VermilionCity_Gym_EventScript_SetBeamsOff::
	end

VermilionCity_Gym_EventScript_SetBeamsOn::
	end

VermilionCity_Gym_EventScript_SetOneBeamOff::
	end

VermilionCity_Gym_EventScript_Surge::
	end

VermilionCity_Gym_EventScript_Surge_Defeated::
	end

VermilionCity_Gym_EventScript_TrashCan::
	end

VermilionCity_Gym_EventScript_TrashCan1::
	end

VermilionCity_Gym_EventScript_TrashCan10::
	end

VermilionCity_Gym_EventScript_TrashCan11::
	end

VermilionCity_Gym_EventScript_TrashCan12::
	end

VermilionCity_Gym_EventScript_TrashCan13::
	end

VermilionCity_Gym_EventScript_TrashCan14::
	end

VermilionCity_Gym_EventScript_TrashCan15::
	end

VermilionCity_Gym_EventScript_TrashCan2::
	end

VermilionCity_Gym_EventScript_TrashCan3::
	end

VermilionCity_Gym_EventScript_TrashCan4::
	end

VermilionCity_Gym_EventScript_TrashCan5::
	end

VermilionCity_Gym_EventScript_TrashCan6::
	end

VermilionCity_Gym_EventScript_TrashCan7::
	end

VermilionCity_Gym_EventScript_TrashCan8::
	end

VermilionCity_Gym_EventScript_TrashCan9::
	end

VermilionCity_Gym_EventScript_TrySwitchTwo::
	end

VermilionCity_Gym_EventScript_Vincent::
	end

VermilionCity_Gym_OnLoad::
	end

VermilionCity_Gym_OnTransition::
	end

VermilionCity_Gym_Text_GymGuyAdvice::
	end

VermilionCity_Gym_Text_GymGuyPostVictory::
	end

VermilionCity_Gym_Text_GymStatue::
	end

VermilionCity_Gym_Text_GymStatuePlayerWon::
	end

VermilionCity_Gym_Text_NopeOnlyTrashHere::
	end

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
	end

VermilionCity_Gym_Text_SecondLockOpened::
	end

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
	end
