SaffronCity_FightingDojoVIP_Frlg_MapScripts::
        .byte 0

SaffronCity_FightingDojoVIP_EventScript_Brock::
        end

SaffronCity_FightingDojoVIP_EventScript_Surge::
        end

SaffronCity_FightingDojoVIP_EventScript_Erika::
        end

SaffronCity_FightingDojoVIP_EventScript_Janine::
        end

SaffronCity_FightingDojoVIP_EventScript_Sabrina::
        end

SaffronCity_FightingDojoVIP_EventScript_Blaine::
        end

SaffronCity_FightingDojoVIP_EventScript_Blue::
        end

SaffronCity_FightingDojoVIP_EventScript_Whitney::
        end

SaffronCity_FightingDojoVIP_EventScript_Falkner::
        end

SaffronCity_FightingDojoVIP_EventScript_Bugsy::
        end

SaffronCity_FightingDojoVIP_EventScript_Morty::
        end

SaffronCity_FightingDojoVIP_EventScript_Jasmine::
        end

SaffronCity_FightingDojoVIP_EventScript_Chuck::
        end

SaffronCity_FightingDojoVIP_EventScript_Clair::
        end

SaffronCity_FightingDojoVIP_EventScript_Pryce::
        end

SaffronCity_FightingDojoVIP_EventScript_Misty::
        end

SaffronCity_FightingDojoVIP_EventScript_Machamp::
        end

SaffronCity_FightingDojoVIP_EventScript_Poliwhirl::
        end

SaffronCity_FightingDojoVIP_EventScript_Raichu::
        end

SaffronCity_FightingDojoVIP_EventScript_Kingdra::
        end

SaffronCity_FightingDojoVIP_EventScript_Starmie::
        end

SaffronCity_FightingDojoVIP_EventScript_Victreebel::
        end

SaffronCity_FightingDojoVIP_EventScript_Scizor::
        end

SaffronCity_FightingDojoVIP_EventScript_Steelix::
        end

SaffronCity_FightingDojoVIP_EventScript_Kadabra::
        end

SaffronCity_FightingDojoVIP_EventScript_Onix::
        end

SaffronCity_FightingDojoVIP_EventScript_Miltank::
        end

SaffronCity_FightingDojoVIP_EventScript_Muk::
        end

SaffronCity_FightingDojoVIP_EventScript_Magmar::
        end

SaffronCity_FightingDojoVIP_EventScript_Dewgong::
        end

@ Typo preserved from map.json: EvetScript not EventScript
SaffronCity_FightingDojoVIP_EvetScript_Statue::
        end

SaffronCity_FightingDojo_EventScript_Chased::
        end

TrainerHill_Courtyard_EventScript_RightMoveTutor::
        end

TrainerHill_Courtyard_EventScript_ElementalMoveTutor::
        end

TrainerHill_Courtyard_EventScript_LeftMoveTutor::
        end

TrainerHill_Courtyard_ExchangeServiceCorner_EventScript_VitaminClerk::
        end

TrainerHill_Courtyard_ExchangeServiceCorner_EventScript_HoldItemClerk::
        end
