PokemonTower_1F_Frlg_MapScripts::
	.byte 0

PokemonTower_1F_EventScript_BaldingMan::
	end

PokemonTower_1F_EventScript_Channeler::
	end

PokemonTower_1F_EventScript_Woman1::
	end

PokemonTower_1F_EventScript_Woman2::
	end

PokemonTower_1F_EventScript_Woman2MalePlayer::
	end

PokemonTower_1F_EventScript_WorkerF::
	end

PokemonTower_1F_OnTransition::
	end

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
	end

PokemonTower_1F_Text_ComeToPayRespectsGirl::
	end

PokemonTower_1F_Text_ComeToPayRespectsSon::
	end

PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
	end

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
	end

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
	end

