PokemonLeague_ChampionsRoom_Frlg_MapScripts::
	.byte 0

ChampionRoom_CloseDoor::
	end

ChampionRoom_OnFrame::
	end

ChampionRoom_Trigger::
	end

PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingEast::
	end

PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingSouth::
	end

PokemonLeague_ChampionsRoom_EventScript_AdjustPlayerFacingWest::
	end

PokemonLeague_ChampionsRoom_OnResume::
	end

PokemonLeague_WillsRoom_EventScript_Lance::
	end

PokemonLeague_WillsRoom_EventScript_LanceOnDefeatJohto::
	end

PokemonLeague_WillsRoom_EventScript_LanceOnDefeatKanto::
	end

PokemonLeague_WillsRoom_EventScript_LanceRematch::
	end
