RocketHideout_B3F_Frlg_MapScripts::
	.byte 0

RocketHideout_B3F_EventScript_Door::
	end

RocketHideout_B3F_EventScript_DoorIsOpen::
	end

RocketHideout_B3F_EventScript_Eto::
	end

RocketHideout_B3F_EventScript_FacingEast::
	end

RocketHideout_B3F_EventScript_FacingEastMurkrow::
	end

RocketHideout_B3F_EventScript_FacingNorth::
	end

RocketHideout_B3F_EventScript_FacingWest::
	end

RocketHideout_B3F_EventScript_FacingWestMurkrow::
	end

RocketHideout_B3F_EventScript_Giovanni::
	end

RocketHideout_B3F_EventScript_Grunt1::
	end

RocketHideout_B3F_EventScript_Grunt2::
	end

RocketHideout_B3F_EventScript_GruntF5::
	end

RocketHideout_B3F_EventScript_IncrementPasswordEto::
	end

RocketHideout_B3F_EventScript_IncrementPasswordGruntF::
	end

RocketHideout_B3F_EventScript_Item_FullHeal::
	end

RocketHideout_B3F_EventScript_Item_GuardSpec::
	end

RocketHideout_B3F_EventScript_Item_HyperPotion::
	end

RocketHideout_B3F_EventScript_Item_IceHeal::
	end

RocketHideout_B3F_EventScript_Item_Protein::
	end

RocketHideout_B3F_EventScript_LancePassword::
	end

RocketHideout_B3F_EventScript_LeaveEast::
	end

RocketHideout_B3F_EventScript_LeaveWest::
	end

RocketHideout_B3F_EventScript_Mitch::
	end

RocketHideout_B3F_EventScript_Murkrow::
	end

RocketHideout_B3F_EventScript_OpenDoor::
	end

RocketHideout_B3F_EventScript_RocketKO::
	end

RocketHideout_B3F_EventScript_Ross::
	end

RocketHideout_B3F_HideGate::
	end

RocketHideout_B3F_HidePetrel::
	end

RocketHideout_B3F_OnFrame::
	end

RocketHideout_B3F_OnLoad::
	end

RocketHideout_B3F_Trigger_MurkrowStairs::
	end

RocketHideout_B3F_Trigger_Silver::
	end
