PokemonMansion_1F_Frlg_MapScripts::
	.byte 0

PokemonMansion_1F_EventScript_Johnson::
	end

PokemonMansion_1F_EventScript_Statue::
	end

PokemonMansion_1F_EventScript_Ted::
	end

PokemonMansion_1F_OnLoad::
	end

PokemonMansion_1F_OnTransition::
	end

PokemonMansion_1F_Text_JohnsonDefeat::
	end

PokemonMansion_1F_Text_JohnsonIntro::
	end

PokemonMansion_1F_Text_JohnsonPostBattle::
	end

PokemonMansion_1F_Text_TedDefeat::
	end

PokemonMansion_1F_Text_TedIntro::
	end

PokemonMansion_1F_Text_TedPostBattle::
	end

