PewterCity_Frlg_MapScripts::
	.byte 0

PewterCity_EventScript_BugCatcher::
	end

PewterCity_EventScript_Bugcatcher::
	end

PewterCity_EventScript_CityEnter::
	end

PewterCity_EventScript_CitySign::
	end

PewterCity_EventScript_Cooltrainer::
	end

PewterCity_EventScript_CooltrainerF::
	end

PewterCity_EventScript_Gramps::
	end

PewterCity_EventScript_GrampsDone::
	end

PewterCity_EventScript_GrampsRainbowWing::
	end

PewterCity_EventScript_GrampsSilverWing::
	end

PewterCity_EventScript_GymSign::
	end

PewterCity_EventScript_MtMoonSign::
	end

PewterCity_EventScript_MuseumSign::
	end

PewterCity_EventScript_WelcomeSign::
	end
