SeafoamIslands_Gym_Frlg_MapScripts::
	.byte 0

SeafoamIslands_Gym_EventScript_Blaine::
	end

SeafoamIslands_Gym_EventScript_Blaine_Defeated::
	end

SeafoamIslands_Gym_EventScript_GymStatue::
	end

SeafoamIslands_Gym_EventScript_GymStatuePostVictory::
	end

SeafoamIslands_Gym_Text_GymStatue::
	end

SeafoamIslands_Gym_Text_GymStatuePlayerWon::
	end

SeafomIslands2_EventScript_GymGuide::
	end

SeafomIslands2_EventScript_GymGuide2::
	end
