SaffronCity_Gym_Frlg_MapScripts::
	.byte 0

SaffronCity_Gym_EventScript_Doris::
	end

SaffronCity_Gym_EventScript_Franklin::
	end

SaffronCity_Gym_EventScript_GymGuy::
	end

SaffronCity_Gym_EventScript_GymGuy2::
	end

SaffronCity_Gym_EventScript_GymStatue::
	end

SaffronCity_Gym_EventScript_GymStatuePostVictory::
	end

SaffronCity_Gym_EventScript_Jared::
	end

SaffronCity_Gym_EventScript_Rebecca::
	end

SaffronCity_Gym_EventScript_Sabrina::
	end

SaffronCity_Gym_EventScript_Sabrina_Defeated::
	end

SaffronCity_Gym_Text_GymStatue::
	end

SaffronCity_Gym_Text_GymStatuePlayerWon::
	end
