PewterCity_Gym_Frlg_MapScripts::
	.byte 0

PewterCity_Gym_EventScript_Brock::
	end

PewterCity_Gym_EventScript_Brock_Defeated::
	end

PewterCity_Gym_EventScript_GymGuy::
	end

PewterCity_Gym_EventScript_GymGuyAfter::
	end

PewterCity_Gym_EventScript_GymStatue::
	end

PewterCity_Gym_EventScript_GymStatuePostVictory::
	end

PewterCity_Gym_EventScript_Jerry::
	end

PewterCity_Gym_Text_GymStatue::
	end

PewterCity_Gym_Text_GymStatuePlayerWon::
	end
