#ifndef GUARD_tilesets_H
#define GUARD_tilesets_H

extern const u32 gTilesetTiles_General[];
extern const u16 gTilesetPalettes_General[][16];

extern const struct Tileset *const gTilesetPointer_SecretBase;
extern const struct Tileset *const gTilesetPointer_SecretBaseRedCave;

extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_BuildingFrlg;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_GenericBuilding1;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_General_Frlg;
extern const struct Tileset gTileset_PalletTown;
extern const struct Tileset gTileset_ViridianCity;
extern const struct Tileset gTileset_PewterCity;
extern const struct Tileset gTileset_SaffronCity;
extern const struct Tileset gTileset_CeruleanCity;
extern const struct Tileset gTileset_LavenderTown;
extern const struct Tileset gTileset_VermilionCity;
extern const struct Tileset gTileset_CeladonCity;
extern const struct Tileset gTileset_FuchsiaCity;
extern const struct Tileset gTileset_CinnabarIsland;
extern const struct Tileset gTileset_SeviiIslands123;
extern const struct Tileset gTileset_SeviiIslands45;
extern const struct Tileset gTileset_SeviiIslands67;
extern const struct Tileset gTileset_DepartmentStore;
extern const struct Tileset gTileset_PokemonCenterFrlg;
extern const struct Tileset gTileset_SilphCo;
extern const struct Tileset gTileset_SSAnne;
extern const struct Tileset gTileset_SeaCottage;
extern const struct Tileset gTileset_TrainerTower;
extern const struct Tileset gTileset_Johto_General;
extern const struct Tileset gTileset_Johto_Building;
extern const struct Tileset gTileset_Johto_NorthEast;
extern const struct Tileset gTileset_Kanto_Building;

// FRLG secondary tilesets
extern const struct Tileset gTileset_Cave_Frlg;
extern const struct Tileset gTileset_CableClub_Frlg;
extern const struct Tileset gTileset_BikeShop_Frlg;
extern const struct Tileset gTileset_Lab_Frlg;
extern const struct Tileset gTileset_NavelRock_Frlg;
extern const struct Tileset gTileset_IslandHarbor_Frlg;
extern const struct Tileset gTileset_PalletTown_Frlg;
extern const struct Tileset gTileset_ViridianCity_Frlg;
extern const struct Tileset gTileset_PewterCity_Frlg;
extern const struct Tileset gTileset_CeruleanCity_Frlg;
extern const struct Tileset gTileset_LavenderTown_Frlg;
extern const struct Tileset gTileset_Vermilion_Frlg;
extern const struct Tileset gTileset_CeladonCity_Frlg;
extern const struct Tileset gTileset_Fuchsia_Frlg;
extern const struct Tileset gTileset_IndigoPlateau_Frlg;
extern const struct Tileset gTileset_SaffronCity_Frlg;
extern const struct Tileset gTileset_Museum_Frlg;
extern const struct Tileset gTileset_GameCorner_Frlg;
extern const struct Tileset gTileset_DepartmentStore_Frlg;
extern const struct Tileset gTileset_SeaCottage_Frlg;
extern const struct Tileset gTileset_ViridianForest_Frlg;
extern const struct Tileset gTileset_HallOfFame_Frlg;
extern const struct Tileset gTileset_PokemonLeague_Frlg;
extern const struct Tileset gTileset_VermilionCity_Gym_Frlg;
extern const struct Tileset gTileset_SaffronCity_Gym_Frlg;
extern const struct Tileset gTileset_FuchsiaCity_Gym_Frlg;
extern const struct Tileset gTileset_ViridianCity_Gym_Frlg;
extern const struct Tileset gTileset_CeruleanCity_Gym_Frlg;
extern const struct Tileset gTileset_SafariZoneJohto_Frlg;
extern const struct Tileset gTileset_SafariZone_Entrance_Frlg;
extern const struct Tileset gTileset_SaffronCity_FightingDojoVIP_Frlg;
extern const struct Tileset gTileset_Lavaridge_Frlg;
extern const struct Tileset gTileset_KantoMart_Frlg;
extern const struct Tileset gTileset_Kanto_PokemonCenter_Frlg;
extern const struct Tileset gTileset_PokemonDayCare_Frlg;
extern const struct Tileset gTileset_SilphCo_Frlg;
extern const struct Tileset gTileset_AzaleaTown_Gym_Frlg;
extern const struct Tileset gTileset_BlackthornGym_Frlg;
extern const struct Tileset gTileset_Blackthorn_Frlg;
extern const struct Tileset gTileset_Cafe_Frlg;
extern const struct Tileset gTileset_Cave_Default_Frlg;
extern const struct Tileset gTileset_Cave_Gray_Frlg;
extern const struct Tileset gTileset_Cave_Green_Frlg;
extern const struct Tileset gTileset_Cave_Ice_Frlg;
extern const struct Tileset gTileset_Cave_MtMoon_Frlg;
extern const struct Tileset gTileset_Cave_Sandy_Frlg;
extern const struct Tileset gTileset_CeladonApartments_Frlg;
extern const struct Tileset gTileset_CherrygroveCity_Frlg;
extern const struct Tileset gTileset_CyclingRoad_Frlg;
extern const struct Tileset gTileset_EcruteakTheater_Frlg;
extern const struct Tileset gTileset_Gate_Standard_Frlg;
extern const struct Tileset gTileset_GoldenrodCity_TrainStation_Frlg;
extern const struct Tileset gTileset_GoldenrodUndergroundRocket_Frlg;
extern const struct Tileset gTileset_GoldenrodUndergroundTunnel_Frlg;
extern const struct Tileset gTileset_House_2_Frlg;
extern const struct Tileset gTileset_House_Lab_Frlg;
extern const struct Tileset gTileset_NationalPark_Frlg;
extern const struct Tileset gTileset_NewBarkTown_Frlg;
extern const struct Tileset gTileset_PlayersHouse_Frlg;
extern const struct Tileset gTileset_PokemonCenter_White_Frlg;
extern const struct Tileset gTileset_PortIndoor_Frlg;
extern const struct Tileset gTileset_PowerPlant_GeneratorRoom_Frlg;
extern const struct Tileset gTileset_ShopRooftop_Frlg;
extern const struct Tileset gTileset_SoulHouse_Frlg;
extern const struct Tileset gTileset_WhirlIslands_Frlg;

#endif //GUARD_tilesets_H
