VermilionCity_PortInside_Frlg_MapScripts::
	.byte 0

VermilionPortIndoor_EventScript_Nerd::
	end

VermilionPortIndoor_EventScript_Teacher::
	end

VermilionPort_EventScript_ChoseBattleFrontier::
	end

VermilionPort_EventScript_ChoseBirthIsland::
	end

VermilionPort_EventScript_ChoseFarawayIsland::
	end

VermilionPort_EventScript_ChoseOlivine::
	end

VermilionPort_EventScript_ChoseSouthernIsland::
	end

VermilionPort_EventScript_EnterShip::
	end

VermilionPort_EventScript_Sailor::
	end

VermilionPort_EventScript_SailorCantSail::
	end

VermilionPort_EventScript_Sailor_AfterKanto::
	end

VermilionPort_EventScript_Sailor_MaidenVoyage::
	end

VermilionPort_EventScript_Sailor_NoCredentials::
	end

VermilionPort_EventScript_Sailor_Refused::
	end
