SaffronCity_SilphCo_Frlg_MapScripts::
	.byte 0

SaffronCity_SilphCo_EventScript_AfterStarterGiven::
	end

SaffronCity_SilphCo_EventScript_MudkipChosen::
	end

SaffronCity_SilphCo_EventScript_Officer::
	end

SaffronCity_SilphCo_EventScript_OfficerAfter::
	end

SaffronCity_SilphCo_EventScript_Receptionist::
	end

SaffronCity_SilphCo_EventScript_Refused::
	end

SaffronCity_SilphCo_EventScript_Sign1::
	end

SaffronCity_SilphCo_EventScript_Sign2::
	end

SaffronCity_SilphCo_EventScript_Steven::
	end

SaffronCity_SilphCo_EventScript_StevenChooseStone::
	end

SaffronCity_SilphCo_EventScript_TorchicChosen::
	end

SaffronCity_SilphCo_EventScript_TreeckoChosen::
	end
