Route22_Frlg_MapScripts::
	.byte 0

Route22_EventScript_DoNothing::
	end

Route22_EventScript_PlayerFaceEast::
	end

Route22_EventScript_PlayerFaceNorth::
	end

Route22_EventScript_PlayerFaceSouth::
	end

Route22_EventScript_PlayerFaceWest::
	end

Route22_EventScript_ResetActivation::
	end

Route22_EventScript_Scene::
	end

Route22_EventScript_Sign::
	end

Route22_EventScript_TriggerBottom::
	end

Route22_EventScript_TriggerMid::
	end

Route22_EventScript_TriggerTop::
	end
