FiveIsland_RocketWarehouse_Frlg_MapScripts::
	.byte 0

FiveIsland_RocketWarehouse_EventScript_Admin1::
	end

FiveIsland_RocketWarehouse_EventScript_Admin2::
	end

FiveIsland_RocketWarehouse_EventScript_Admin2Trigger::
	end

FiveIsland_RocketWarehouse_EventScript_AdminFacePlayerDown::
	end

FiveIsland_RocketWarehouse_EventScript_AdminFacePlayerLeft::
	end

FiveIsland_RocketWarehouse_EventScript_AdminFaceSwitch::
	end

FiveIsland_RocketWarehouse_EventScript_AdminWalkToSwitch::
	end

FiveIsland_RocketWarehouse_EventScript_AdminWalkToSwitchFar::
	end

FiveIsland_RocketWarehouse_EventScript_Cage::
	end

FiveIsland_RocketWarehouse_EventScript_CageUnlocked::
	end

FiveIsland_RocketWarehouse_EventScript_Computer::
	end

FiveIsland_RocketWarehouse_EventScript_DefeatedAdmin1::
	end

FiveIsland_RocketWarehouse_EventScript_DefeatedAdmin2::
	end

FiveIsland_RocketWarehouse_EventScript_DefeatedGideon::
	end

FiveIsland_RocketWarehouse_EventScript_Gideon::
	end

FiveIsland_RocketWarehouse_EventScript_Grunt1::
	end

FiveIsland_RocketWarehouse_EventScript_Grunt2::
	end

FiveIsland_RocketWarehouse_EventScript_Grunt3::
	end

FiveIsland_RocketWarehouse_EventScript_MentionGiovannisKid::
	end

FiveIsland_RocketWarehouse_EventScript_PlayerFaceAdmin1::
	end

FiveIsland_RocketWarehouse_EventScript_PlayerFaceAdmin2::
	end

FiveIsland_RocketWarehouse_EventScript_SetArrowsForReEntry::
	end

FiveIsland_RocketWarehouse_Movement_AdminWalkToSwitch::
	end

FiveIsland_RocketWarehouse_Movement_AdminWalkToSwitchFar::
	end

FiveIsland_RocketWarehouse_OnLoad::
	end

FiveIsland_RocketWarehouse_OnTransition::
	end

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
	end

FiveIsland_RocketWarehouse_Text_Admin1Intro::
	end

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
	end

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
	end

FiveIsland_RocketWarehouse_Text_Admin2Intro::
	end

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
	end

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
	end

FiveIsland_RocketWarehouse_Text_GideonDefeat::
	end

FiveIsland_RocketWarehouse_Text_GideonIntro::
	end

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
	end

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
	end

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
	end

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
	end

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
	end

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
	end

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
	end

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
	end

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
	end

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
	end

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
	end

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
	end

FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
	end

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
	end

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
	end

