FuchsiaCity_Gym_Frlg_MapScripts::
	.byte 0

FuchsiaCity_Gym_DefeatedAlice::
	end

FuchsiaCity_Gym_DefeatedBarry::
	end

FuchsiaCity_Gym_DefeatedCindy::
	end

FuchsiaCity_Gym_DefeatedLinda::
	end

FuchsiaCity_Gym_EventScript_Alice::
	end

FuchsiaCity_Gym_EventScript_Alice_J::
	end

FuchsiaCity_Gym_EventScript_Barry::
	end

FuchsiaCity_Gym_EventScript_Barry_J::
	end

FuchsiaCity_Gym_EventScript_Cindy::
	end

FuchsiaCity_Gym_EventScript_Cindy_J::
	end

FuchsiaCity_Gym_EventScript_GymGuy::
	end

FuchsiaCity_Gym_EventScript_GymGuyAfter::
	end

FuchsiaCity_Gym_EventScript_GymStatue::
	end

FuchsiaCity_Gym_EventScript_GymStatuePostVictory::
	end

FuchsiaCity_Gym_EventScript_Janine::
	end

FuchsiaCity_Gym_EventScript_Janine_Defeated::
	end

FuchsiaCity_Gym_EventScript_Linda::
	end

FuchsiaCity_Gym_EventScript_Linda_J::
	end

FuchsiaCity_Gym_OnTransition::
	end

FuchsiaCity_Gym_OnTransitionAfter::
	end

FuchsiaCity_Gym_Text_GymStatue::
	end

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
	end
