TrainerTower_Lobby_Frlg_MapScripts::
	.byte 0

TrainerTower_Lobby_EventScript_AllFloorsUsed::
	end

TrainerTower_Lobby_EventScript_AskEnterChallenge::
	end

TrainerTower_Lobby_EventScript_BaldingMan::
	end

TrainerTower_Lobby_EventScript_BeginChallenge::
	end

TrainerTower_Lobby_EventScript_ChallengeInfo::
	end

TrainerTower_Lobby_EventScript_ChooseChallenge::
	end

TrainerTower_Lobby_EventScript_CooltrainerF::
	end

TrainerTower_Lobby_EventScript_DeclineChallenge::
	end

TrainerTower_Lobby_EventScript_Enter::
	end

TrainerTower_Lobby_EventScript_EnterEnd::
	end

TrainerTower_Lobby_EventScript_EntryTrigger::
	end

TrainerTower_Lobby_EventScript_ExitChallenge::
	end

TrainerTower_Lobby_EventScript_ExitChallengeSpeakToReceptionist::
	end

TrainerTower_Lobby_EventScript_ExitElevator::
	end

TrainerTower_Lobby_EventScript_LostChallenge::
	end

TrainerTower_Lobby_EventScript_MartClerk::
	end

TrainerTower_Lobby_EventScript_Nurse::
	end

TrainerTower_Lobby_EventScript_Receptionist::
	end

TrainerTower_Lobby_EventScript_ReceptionistEnd::
	end

TrainerTower_Lobby_EventScript_ShowRecords::
	end

TrainerTower_Lobby_EventScript_ThanksForCompeting::
	end

TrainerTower_Lobby_Mart_Items::
	end

TrainerTower_Lobby_Movement_ExitElevator::
	end

TrainerTower_Lobby_Movement_FaceReceptionist::
	end

TrainerTower_Lobby_Movement_WalkDown::
	end

TrainerTower_Lobby_OnFrame::
	end

TrainerTower_Lobby_OnLoad::
	end

TrainerTower_Lobby_OnResume::
	end

TrainerTower_Lobby_OnResumeEnd::
	end

TrainerTower_Lobby_OnReturnToField::
	end

TrainerTower_Lobby_OnTransition::
	end

TrainerTower_Lobby_OpenCounterBarrier::
	end

TrainerTower_Lobby_Text_ExplainTrainerTower::
	end

TrainerTower_Lobby_Text_GiveItYourBest::
	end

TrainerTower_Lobby_Text_HereAreTheResults::
	end

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
	end

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
	end

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
	end

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
	end

TrainerTower_Lobby_Text_StartClockGetSetGo::
	end

TrainerTower_Lobby_Text_ThanksForCompeting::
	end

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
	end

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
	end

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
	end

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
	end

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
	end

